### ISSUE TITLE
Check dependencies for py3 compatibility

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1036]
Step one of python 3 is to figure out what we rely on that we have to drop. By now if a dependency doesn't support Py3, we either need to abandon it, adopt it, or send a PR.

**Comment by azeemba** [comment]
I was able to use `caniusepython3` tool to generate this report: https://gist.github.com/azeemba/06fad256105e2d60d9c5e2be34d1ed3d

The summary is that the tool thinks most dependencies are good except it had issues finding info on these dependencies:

- [psycopg2](https://pypi.org/project/psycopg2/): The tool just had trouble parsing the complex version string. Psycopg2 is a fine dependency
- [python-igraph](https://pypi.org/project/python-igraph/): While the [pypi](https://pypi.org/project/python-igraph/) page for this module is lacking in information, its GitHub repo's [CI](https://github.com/igraph/python-igraph/blob/master/.travis.yml) suggest they support python3
- [timeout-decorator](https://pypi.org/project/timeout-decorator/0.4.1/): GitHub repo's [CI](https://github.com/pnpnpn/timeout-decorator/blob/master/tox.ini) suggests they support python3
- [django-markdown-deux](https://pypi.org/project/django-markdown-deux/): This dependency probably should be **replaced**. It has not [updated](https://github.com/trentm/django-markdown-deux) since 2014.
- [usaddress](https://pypi.org/project/usaddress/): GitHub repo's [CI](https://github.com/datamade/usaddress/blob/master/appveyor.yml) suggests this module does support python3.4 but it has not been released since 2017 and python3.4 is already EOL. There is an open [PR](https://github.com/datamade/usaddress/pull/267) to upgrade to python3.7 but the lack of releases make this questionable. So this dependency should be **replaced**  though it is viable to keep this dependency since python3.4 code is almost always compatible with future versions

**Comment by mlissner** [comment]
Thanks! I totally forgot that tool existed! This is very helpful.

**Comment by drewsilcock** [comment]
Have you thought about what version(s) of Python 3 to target? If you're doing a big upgrade like this, you may as well go for the latest stable (currently 3.8) imo - in for a penny and all that - but maybe that's just me. Lots of projects support 3.6.1 + (e.g. [pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html)) as standard. If you're writing a library it makes sense to support as many versions as possible but this is a standalone application so there doesn't seem any real advantage.

I had a go at installing all the dependencies using 3.8.0 and found the following:

- `pydot==1.1.0` doesn't support Python 2. Support added in `1.2.0` but the latest is `20.9.0`.
- `pandas==0.18.1` only supports py2.7, py3.4 and py3.5. Latest is `1.1.2` which supports py3.6.1, py3.7 and 3py.8.
- Updating pandas to `1.1.2` requires updating `python-dateutil` to `>=2.7.3`. Latest is `2.8.1`.
- `psycopg2>=2.7,<2.8` doesn't work on py3.8 because support for py3.8 was added in `2.8.4`. Latest is `2.8.6`. Also, you don't need the `--no-binary` flag anymore. There's `psycopg2-binary` as a separate package now. See: https://www.psycopg.org/docs/install.html#change-in-binary-packages-between-psycopg-2-7-and-2-8
- `wsgiref` can be removed as a dependency - it's part of the stdlib now.
- `enum34` isn't needed anymore, as Python has enums in stdlib now.
- `seal-rookery` needs to be installed from git currently (issue open for this).
- `reporters-db` needs updating to work with py3. Also relies on `python-dateutil==2.5.0` which needs updating to be compatible with `pandas==1.1.2`.

On a general note, have you considered using [Poetry](https://python-poetry.org/) instead of `requirements.txt`? It's a very clean, modern solution that's increasingly appearing as the standard [PEP517 / PEP518 build tool](https://snarky.ca/what-the-heck-is-pyproject-toml/) going forwards. You've already got the `pyproject.toml` for it! 🙂 It has support for dev packages and you can collect the `requirements-flp.txt` dependencies into an optional extra. To show how this would look, I made a branch on my fork:

https://github.com/drewsilcock/courtlistener/tree/feature/update-to-python-3

I've written up these dependencies along with an explanation of Poetry and also some of the code changes that will be necessary to work with py3 here:

https://github.com/drewsilcock/courtlistener/blob/feature/update-to-python-3/UpdatingToPython3-8.md

**Comment by mlissner** [comment]
> Have you thought about what version(s) of Python 3 to target?

Ideally we'd want to target the most recent version, yep. I can't imagine why we wouldn't just try to keep up with the latest.

Looking through these:

> pydot==1.1.0 doesn't support Python 2. Support added in 1.2.0 but the latest is 20.9.0.

Drop this dep. We don't use pydot for anything and it shouldn't be in the requirements file.

> pandas==0.18.1 only supports py2.7, py3.4 and py3.5. Latest is 1.1.2 which supports py3.6.1, py3.7 and 3py.8.

Pandas isn't used except in import scripts. We can just upgrade it. If something breaks, a human will be in the loop.

> Updating pandas to 1.1.2 requires updating python-dateutil to >=2.7.3. Latest is 2.8.1.

Bummer. We *do* use dateutil in a number of places. Checking API compat might be smart here.

> psycopg2>=2.7,<2.8 doesn't work on py3.8 because support for py3.8 was added in 2.8.4. Latest is 2.8.6. Also, you don't need the --no-binary flag anymore. There's psycopg2-binary as a separate package now. 

I can't imagine a `psycopg` upgrade would break *any* APIs, let's upgrade it. Good that the binary thing is getting a little cleaner. Let's continue *not* installing the binary version.

> wsgiref can be removed as a dependency - it's part of the stdlib now.

Lovely.

> enum34 isn't needed anymore, as Python has enums in stdlib now.

This was a sub-dependency that shouldn't be in our dep list in the first place. Oof.

> have you considered using Poetry instead of requirements.txt

I don't think anybody has looked at it carefully, but it seems like it has the momentum to beat pip. I'm for it.

Thank you for all of this. It's something we've struggled with for a long time. I've looked at py3 upgrading a few times, but there's always some dependency that gets in the way. Looks like we may finally get over the hump.

**Comment by mlissner** [comment]
Poetry is now landed in a58f33cea12dd4bf7e27feba208eab42fd351d14. The rest of the above are taken care. I think our dependencies are there! Closing.
