### ISSUE TITLE
Add field for blocked pdf for LASC db model

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1043]

**Comment by mlissner** [comment]
This one deserves some explanation and expansion since it is about privacy in the LASC data. @brianwc, perk your ears. 

Here's the current thinking about privacy and dissemination of the LASC data, once it goes on our website:

1. Unlike PACER or even the opinion DB, *most* of the LASC stuff is for small stuff. Therefore, it makes sense to default to keeping all dockets and documents off of the Internet.

1. Everything should, of course, be searchable in CL and by default it should all be viewable. 

1. However, some documents are going to have privacy problems (SSNs, etc.). For those, we should just not let people download them. Instead, we show a message, "Get this from the court b/c we won't serve you PII." But we let people view the redacted text extraction from the document if they want. 

To accomplish all this, we need a field for blocked LASC PDFs. Unlike our other blocked fields, it doesn't have anything to do with Google since all of these documents will be private by default. Instead, it has to do with whether the document is available *at all*.
