### ISSUE TITLE
Merge Harvard Opinions

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1080]
Need code to merge Harvard Case law data into Courtlistener. 

Including changes to db model

**Comment by quevon24** [comment]
I have some comments regarding the docket numbers.

Currently the docket number is stored exactly as it is obtained from the json(https://github.com/freelawproject/courtlistener/blob/main/cl/corpus_importer/management/commands/harvard_opinions.py#L463) No pre-processing is done.

Some docket numbers were omitted, for example: we have _Slip Op. 18-165; Court No. 17-00031_ as docket numbers, but only _17-00031_ is stored in courtlistener, the other is missing.

Some docket numbers contains citations?, like this: _2 Div. 736, 3 Div. 474, 8 Div. 308_ You can see this here https://api.case.law/v1/cases/3590929/ or here https://api.case.law/v1/cases/3589844/

There are many incorrect docker numbers, for example in courtlistener we have a case with this docket number: _16SC916, Thompson_ but the correct docket no. is: _16SC916_ (https://api.case.law/v1/cases/12571899/) or we have a case with docket number: _18-1573P_ but the correct docket no. is: _18-1573_ (https://api.case.law/v1/cases/12519449/)

Some cases have multiple docket numbers, like _Nos. 2017-1715; 2017-1716_ or _Nos. 13AP-133; 13AP-134_ and these were normalized in courlistener as _13AP-133 and 13AP-134_ and _2017-1715 and 2017-1716_ but others have this format: _SJC 12440 & 12563_ using an & join the docket numbers, both ways are ok? or should we use only one symbol as a separator? 
Note: I couldn't find how did you do this because docker number is stored exactly as it is obtained in harvard importer.

I already identified many docket number variations:

- Appeal No. 3-17-0287
- Case Number: 116510
- Cause No. 18T-TA-00015
- Consol. Court No. 16-00075
- Court of Appeals Case No. 18A-MI-883
- Court of Appeals No. A-12600
- Docket No. 46021
- Docket Nos. 17-0922-cv
- No. 409PA17
- Nos. 17-6034/6079
- Nos. 2017-1715; 2017-1716
- NOS. C-170607
- PC 16-3967
- PP 14-4885
- Record No. 180062
- Slip Op. No. 18-176
- Supreme Court Nos. S-16713/S-16733

Already having identified the variations, we could use a simple regex to replace the variations to only keep the docket number, and in case of having multiple docket numbers separated by ; we could split them, replace the variations and join the docket numbers again.

**Comment by flooie** [comment]
We wrote a script to compare data from CL to Harvard, the bankruptcy court gave us the following gems. 

The CL data is the first tuple item and the harvard data is the right.  The script compared the data and only showed examples where data was present in both data sources but different. 


Cluster: 2196558 Harvard_id: 4181942
judges           ('Robert J. Faris', 'Faris')
case_name                ('In Re Maui Indus. Loan & Finance Co.', 'Field v. Trust Estate of Rose Kepoikai (In re Maui Industrial Loan & Finance Co.)')
docket_number            ('19-00179', 'Bankruptcy No. 10-00235; Adversary Nos. 10-90126, 10-90130, 10-90131, 10-90137')
/storage/harvard_corpus/law.free.cap.br.463/499.3672479.json
----
Cluster: 2195441 Harvard_id: 3672479
judges           ('Robert J. Faris', 'Faris')
case_name                ('In Re Maui Indus. Loan & Finance Co.', 'Field v. Levin (In re Maui Industrial Loan & Finance Co.)')
docket_number            ('19-00180', 'Bankruptcy No. 10-00235; Adversary No. 11-90032')
/storage/harvard_corpus/law.free.cap.br.15/732.6554605.json


In both examples, the judge information is fuller and better in CL, but the docket numbers dont appear correct.  

Now I checked the first one and the data source is RECAP and SCRAPER, so I'm not sure how to argue with the docket number generated here.  

This will be a challenge.  Perhaps we try to confirm the docket numbers via the original source material, and the content which seems to validate the Harvard data.

**Comment by quevon24** [comment]
For the judges, I saw that many are not stored in the cluster, we can save them directly as they are obtained but also implement the normalization of these within the import process to add them to panel.

For the attorneys, i found that in many cases the field is empty but we have the data in the json file, also, do we expect to extract only the names or only store the text? Because in many cases the attorneys comes with a larger text like:  

`Christopher J. Velez, of Law Office of Christopher J. Velez, of Garden City, was on the briefs for appellant., Tamara S. Hicks, assistant county attorney, Susan Lynn Hillier Richmeier, county attorney, and Derek Schmidt, attorney general, were on the brief for appellee.`

**Comment by mlissner** [comment]
I think if we start populating docket_number_core, that should help with a lot of the docket number cleanup, but it's still a really lousy field. Just in the federal district courts, the same docket number can be written in a bunch of ways. 

This docket number consists of five parts:

 - 2:19-cv-99999-MJL

The only parts that matter are the 19 and the 99999. The rest of the parts can be omitted, so these (and likely more) variations are all valid:

 - 19-99999
 - 19-cv-99999
 - 2:19-cv-99999

The docket_number_core field reduces these variations to just the core part of the docket number: 1999999. It works for district court dockets, but is blank for all other courts.

**Comment by flooie** [comment]
New issue to investigate, 

In at least one opinion, the opinion we have is Split into the Opinion and an Addendum opinion.  

`https://www.courtlistener.com/opinion/3246772/go/`

The harvard data makes no distinction although it does have a tag for the addendum.  

```
 <p id=\"ARX\">
```
and it does have a separate 
`<author>` tag for the addendum.  which may be the way to identify them. 

I'm not sure how Courtlistener would handle the situation if we were to add a new Combined opinion to the mix.  Would it take over.  

`https://ia803100.us.archive.org/33/items/law.free.cap.ala-app.19/380.8825727.json`

Further research is needed.
