### ISSUE TITLE
Add normalized judge values to Opinion and Cluster objects from harvard import

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1103]
We are currently populating their `_str` values. Need to go back and do them properly as well.

**Comment by mlissner** [comment]
Also need to do `panel` and `non_participating_judges` on the cluster.

**Comment by mlissner** [comment]
See also #633, which deals with a similar issue, I think, except for RECAP judges. Might be worth doing both of these at once.

**Comment by flooie** [comment]
This should wait until @janderse has imported magistrate and bankruptcy judges

**Comment by quevon24** [comment]
So far the lookup_judge_by_last_name() function used to find judges works very well, I only found some problems with last names containing unicode characters or accents, for example: `Spratléy` or `I\u2019Anson`

If it's not common to have accents in last names, these can be replaced with the unidecode library, this also applies to unicode characters, and this can be done directly in the mentioned functions or only in the management command.

There are also misspellings in the last name of the authors due to the ocr, for example in this opinion: https://www.courtlistener.com/api/rest/v3/opinions/6822926/ the author is: "Bich" but if you look at the original pdf: https://cite.case.law/pdf/6078810/United%20States%20v.%20Charles%20Garcia%20&%20Co.,%2048%20C.C.P.A.%20140%20(1961). pdf you will see that the correct last name is "Rich"

This type of error will be logged in order to see if the author could not be found, whether he is not registered in the system, has incomplete information, or the last name is incorrect.

**Comment by mlissner** [comment]
Glad to see that `lookup_judge_by_last_name` works well. 

For the judges with accents is it that we have the accents in our DB and the things we're looking up don't, or the opposite? 

Typos from OCR are out of our hands, but I like your idea of logging all the names we can't find and then figuring out if it's worth inputting or fixing them. This won't be like the effort to normalize courts or citations though. If we don't have a judge, we put their name in the `_str` field and we move on (thank goodness!). It's just too hard to have every judge ever.
