### ISSUE TITLE
Harvard citation parser for tax court generated multiple wrong citations

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1133]
See:
https://www.courtlistener.com/opinion/4554889/william-s-cook-v-commissioner/

**Comment by mlissner** [comment]
Just to flesh out the issue here for future-us. There appear to be two basic problem here:

1. The script isn't idempotent and we thought it was. We ran it multiple times and it was supposed to only add the first citation or do nothing. Instead, it would add the first citation it found that it didn't already have. So the first time you ran it, it'd add the first citation, then the second time, it'd add the second, etc.

2. We didn't have any guard against adding citations that were in the body of the text of the documents. We wanted to find citations that were essentially on their own line — those represent the citations *of* the document itself. Instead we added citations to other decisions that were in the body of the case. 

The fix seems to be to identify the latter, and to re-run the script in a way that can figure out how bad the problem is. With that done, we can think about how to clean it up.

**Comment by mlissner** [comment]
There's two classes of cases that need to be cleaned up. Those that have one erroneous citation and those that have multiple citations, some of which are wrong. For the latter, we can pretty easily identify them with:

```
ocs = OpinionCluster.objects.filter(docket__court_id='tax').annotate(Count('citations')).filter(citations__count__gt=1)
```

Currently it finds the following:

```
In [14]: ocs.count()
Out[14]: 21

In [15]: for oc in ocs:
   ....:     for cite in oc.citations.all():
   ....:         print cite
   ....:         
KeyboardInterrupt

In [15]: for oc in ocs:
    print(oc)                      
    for cite in oc.citations.all():
        print '  %s' % cite
   ....:         
4554889: William S. Cook v. Commissioner
  79 T.C. 298
  56 T.C. 1324
4556308: Lee Nelson Shaw v. Commissioner
  90 T.C. 698
  2001 T.C. Memo. 287
4561935: Ensyc Technologies v. Commissioner
  130 T.C. 44
  2012 T.C. Summary Opinion 55
4562075: William M. Hirsch v. Commissioner
  61 T.C. 861
  2012 T.C. Summary Opinion 89
4562119: Marvin Morris Bartosovsky v. Commissioner
  61 T.C. 861
  2012 T.C. Summary Opinion 101
4562174: Terrance Dale Moore, Jr., and Rhonda R. Moore v. Commissioner
  117 T.C. 183
  2012 T.C. Summary Opinion 116
4562187: Robert P. Duplicki v. Commissioner
  114 T.C. 604
  2012 T.C. Summary Opinion 117
4562288: Deborah L. Anderson v. Commissioner
  61 T.C. 861
  2013 T.C. Summary Opinion 24
4562289: Norma C. Hennessey v. Commissioner
  61 T.C. 861
  2013 T.C. Summary Opinion 23
4562500: Andrew Lewis Havard v. Commissioner
  114 T.C. 176
  2014 T.C. Summary Opinion 48
4562525: James William Harrison v. Commissioner
  90 T.C. 678
  2014 T.C. Summary Opinion 69
4562816: Minnie Mae Howell v. Commissioner
  129 T.C. 107
  2015 T.C. Summary Opinion 45
4562834: Valentine C. Anyanwu v. Commissioner
  114 T.C. 604
  2015 T.C. Summary Opinion 56
4562845: Lucrezia Iona Canaday v. Commissioner
  61 T.C. 861
  2015 T.C. Summary Opinion 57
4563012: Victor M. Crown v. Commissioner
  114 T.C. 176
  2016 T.C. Summary Opinion 15
4563252: Gregor MacInnis v. Commissioner
  61 T.C. 861
  2016 T.C. Summary Opinion 78
4563459: Alan David Snow v. Commissioner
  114 T.C. 176
  2017 T.C. Summary Opinion 38
4563593: David L. Jones v. Commissioner
  61 T.C. 861
  2017 T.C. Summary Opinion 75
4563649: James Lloyd Phillips v. Commissioner
  98 T.C. 518
  2017 T.C. Memo. 230
4563756: Michelle M. Moreno v. Commissioner
  61 T.C. 861
  2018 T.C. Summary Opinion 19
4563762: Allen A. Vest v. Commissioner
  114 T.C. 176
  2018 T.C. Summary Opinion 18
```

**Comment by mlissner** [comment]
This is done. There's a new `--fix` flag that we can run to nuke old citations and replace them with new ones. Works well after a few iterations.
