### ISSUE TITLE
URL pattern for opinions and dockets confusing

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1136]
Currently to access an opinion (and the same pattern applies for dockets) I can go to:

```
https://www.courtlistener.com/opinion/108713/roe-v-wade/
https://www.courtlistener.com/opinion/108713/roe/
https://www.courtlistener.com/opinion/108713/x/
```
but not the following to access the example case Roe v. Wade.

```
https://www.courtlistener.com/opinion/108713/
https://www.courtlistener.com/opinion/108713
```

I should be able to go to either of the second grouping without having to add a random string to the next slug.

**Comment by mlissner** [comment]
What happened to the PR you had for this? Trying to remember why we didn't merge it already, assuming it exists.

**Comment by nathreed** [comment]
Is this still open? It seems like PR #1137 was going to address this, but then it had lots of other changes and a clean one was going to be made. The issue is still apparent on the website (just tested). I know there were scraper concerns in the discussion of the previous PR, so I'm not sure if that's why you ultimately didn't merge it.

Happy to make a clean PR with the changes from the old one if this is still up for fixing. If not, I think the issue should be closed.

**Comment by mlissner** [comment]
Yeah, this never got done if it's not deployed. I'd still welcome it. Probably best done via a redirect to the current URLs from the truncated ones?
