### ISSUE TITLE
Bootstrap should be upgraded to the the current version

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1149]
3.3 is great but the improvements in layout are worthy of a painful upgrade.

**Comment by mlissner** [comment]
This should be great. I think we can do this incrementally by starting with a new base.html and then upgrading the chain of templates to use bootstrap4 for certain pages that we've upgraded, then once we get further along we can work on upgrading *all* the pages.

**Comment by mlissner** [comment]
So I read the BS4 documentation and upgraded our jQuery version to support BS4. It's not terribly, incredibly different, but it's enough that when you try it out the homepage looks like this:

![Screenshot from 2020-01-28 16-17-09](https://user-images.githubusercontent.com/236970/73318008-f3682f00-41ec-11ea-8bbb-0b3f3770f1f6.png)

My hope was that I could create a new base template and then start using it on new pages, but that's going to be really painful because it means you have to recreate the site as it is now so that the new pages blend in seamlessly with the old. I tried that for about 15 minutes and decided it was crazy.

So the way to do this is going to be as part of building a new site. The good news is we can start dropping BS4 into CourtListener whenever we're ready. The bad news is that we'll have to do the whole site all at once. 

@litewarp, perhaps you have feelings here. I suspect you'll want to just redesign the whole thing and throw bootstrap out?

**Comment by mlissner** [comment]
I just realized we've been down this path before: https://github.com/freelawproject/courtlistener/issues/296

**Comment by mlissner** [comment]
Closing. We're going to move to tailwind instead.
