### ISSUE TITLE
Avoid race conditions in citation incrementation

### ISSUE THREAD

**Issue by mattdahl** [freelawproject/courtlistener#1224]
Re: https://github.com/freelawproject/courtlistener/pull/1187#discussion_r381100495, the citation incrementation code could be improved (around here: https://github.com/freelawproject/courtlistener/blob/master/cl/citations/tasks.py#L121). As Mike said there, I think several things could be done:

1. Move the incrementation logic to be inside the `if citations:` block below.
2. Use F expressions to perform an atomic increment instead.
3. Extract `opinion.opinions_cited.all()` into its own variable.
4. Replace the `if matched_opinion not in opinion.opinions_cited.all():` logic with a count of `OpinionsCited` objects, as in ffad2edee7a53c60a90949b493642205119fd376. This may actually hurt performance, however.

Thoughts about any of those changes?

**Comment by mlissner** [comment]
As discussed in Slack, it seems like 1-3 are good, easy things to do and the fourth might be trouble. 

The other thing that jumps out at my is that doing `all()` pulls back all of the fields when we only need to pull back the IDs to do the `in` test you mention in number 4 above. So, I'd say when we cache in number 3, we should just pull in the IDs, then make a set from them, and find the conjunction of that set with the matched items in order to do our updates.

I think once 1-3 are in place, taking another look for performance/issues will make sense.

**Comment by mlissner** [comment]
This was merged and has been live for a few weeks with no issues we've identified. Anything left you want to do here, @mattdahl ?

**Comment by mattdahl** [comment]
Nope, looks good to me!
