### ISSUE TITLE
Should we add django-pgtrigger to all or part of CL db

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1239]
See: https://django-simple-history.readthedocs.io/

I am testing a versioning django integration as a way to handle issues with our opinions project db ingestion.  See branch simple-history.

**Comment by mlissner** [comment]
A few observations today:

1. When you set up this system for a model, it creates new tables with `historical` prepended to the name. For example, `search_docket` yields `search_historicaldocket`. That new table has all the columns of the original table, plus another four or so that contain details of the history, and a PK field for the historical row itself. Because it has its own PK field, the PK of the original item can be preserved while reverting or changing the item. Thank goodness.

2. Some fields can be excluded from the historical table. Not from *creating* it, mind you, but from being stored with each version. For example, if you exclude the date_filed field, and then change it, you'll get a new row in the historical table, it just won't have a column for that field. That's kind of interesting because it means it's unclear *what* actually changed

3. Aside from the excluded fields and the additional `history` fields mentioned above, the history tables are pretty much identical to the regular tables, and have migrations just like them. That makes sense. The only bummer is that it also means that we create in-memory indexes for all the columns that would normally have them. This takes memory and memory is expensive.

4. When you save an object, there's a special save function they want us to use. It feels a bit silly though to me since we're already overriding the `save()` function itself. Since we're doing that, we can probably avoid having a whole new function and instead just add a new flag to the save function. (`skip_history_log`, say? Or similar?)

----------

# Additional experiments?

There are a lot of other ones that are worth doing so that we really understand how this will work:

 - [ ] What happens when you add a new column and then migrate? Do you get two migrations? Does your migration have double the work to do? 

 - [ ] Can you have the history information under an attribute that's not named `history`? This is important b/c one of our tables *already* has a history field, so we either have to change that field's name or we have to not use `history` as the new field's name. I think the latter should work, but let's prove it.

**Comment by flooie** [comment]
A few comments of my own. 

- [x] What happens when you add a new column and migrate?  It would appear to do double the work.
```
cl/search/migrations/0101_auto_20200323_1137.py
    - Add field sample_column to docket
    - Add field sample_column to historicaldocket
```

- [x] Can you have the history information under an attribute that's not named `history`? 
I dont think so.  I tested it out and I searched the documentation and was not able to recreate historical tables.  It appears to be baked in.

**Comment by mlissner** [comment]
Shoot, that's not great if that's the case. If so, it's worth seeing if we can figure out where it's baked in, and how hard it'd be to change.

**Comment by mlissner** [comment]
When we add this, we should also investigate adding DB history tracking to the various user tables. An issue that arose today is that somebody got an email from us saying that their email address had been changed. Oddly, they claimed it had not. I don't know *what* happened in there because we don't keep history of that table, but I wish we did.

**Comment by mlissner** [comment]
The problem described in my last comment just happened again today. I was able to handle it by looking at their donations (which have emails associted with them in Stripe's system), but it wasn't great. Upping priority here a bit more.

**Comment by quevon24** [comment]
@mlissner I think we won’t be able to implement history in a separate database, this is because even if Django is capable of working with multiple database, the problem is that Django doesn’t have any support for foreign keys or many to many relationships in multiple databases, and that’s a problem because many of courtlistener models have foreign key relations. The documentation mentions that is not possible to enforce it because postgresql have database level constraints.(https://docs.djangoproject.com/en/3.2/topics/db/multi-db/#cross-database-relations)

I already setup a new postgres service and new database to do some tests  and indeed you can’t save objects with foreign keys in other db, always throws an IntegrityError because the related object is not in the other database.

And maybe it is not a problem, but I saw that if you delete a field from model, it is also deleted from the history model, I think this is not a problem because if a field is deleted it is because we wanted to do it, right?

**Comment by quevon24** [comment]
As expected, django-simple-history doesn't work with F expressions.

I found that many of the F-expressions are used to update the view count of user tags, dockets and scotusmap objects.

I did a lot of testing and the conclusion is that every time you try to save something with a F expression, you will get a nasty ValueError with a message like this:

> ValueError at /tags/admin/tag_test/
> Failed to insert expression "Col(favorites_historicalusertag, favorites.HistoricalUserTag.view_count) + Value(1)" on favorites.HistoricalUserTag.view_count. F() expressions can only be used to update, not to insert.

That's why i decided to try the following two popular libraries that almost do the same thing: django-auditlog and django-reversion.

This is the conclusion for django-auditog (https://github.com/jazzband/django-auditlog):

This library stores the only the changes by serializing the data into json format, the problem is that this library doesn't operate on DB level, causing to store the F-expression as a string like this:

`{"view_count": ["0", "F(view_count) + Value(1)"]}
`
Also this library only works for audit purposes, meaning that we can revert the changes.


With django-reversion (https://github.com/etianen/django-reversion) the issue is almost the same:

The library doesn't operate on DB level, so is not able to store the changes when you use F-expressions, this library stores all the data from the object by serializing the data in a json field, something like this:

`{"date_created": "2022-12-24T03:35:31.215Z", "date_modified": "2022-12-24T04:03:42.568Z", "user": 3, "name": "ora", "title": "", "description": "", "view_count": "F(view_count) + Value(1)", "published": true}`

As you can see, the F-expression is stored as a string, so it's not possible to do the calculations.

I will look for more alternatives but they all seem to work the same, they do not have support for F expressions.

Any suggestion is always welcome  👍

**Comment by mlissner** [comment]
We may need to go to a lower level of abstraction and use db triggers instead. Forget python, forget Django. Let the database do it.

**Comment by quevon24** [comment]
I'm done testing the excluded_fields parameter (https://django-simple-history.readthedocs.io/en/latest/historical_model.html?highlight=excluded_fields#excluded-fields) from django-simple-history to avoid storing the fields that use a F expression, and this part works, when you generate a new migration, the field is not created in Simple History table of the model.

The problem? Well, we don't create the field in the table, for example: modifying the model favorites.UserTag we exclude the "view_count" field, so we don't have the count stored, the problem is that eveytime the user refreshes the user's tag page it creates many duplicates, the rows looks the same because we excluded the value that changes: "view_count". This behavior is normal because the creation of a new history object is triggered when we call the save method and we are calling it when a user refreshes the tag page, to store the count.

To remove that duplicates we have this management command (https://django-simple-history.readthedocs.io/en/3.2.0/utils.html#clean-duplicate-history)

The problem is that we will need to schedule the command to specify the model/models and the excluded fields to remove the possible duplicates generated, something like this:

`docker-compose -f docker/courtlistener/docker-compose.yml exec cl-django python manage.py clean_duplicate_history favorites.usertag --excluded_fields view_count`

To prevent them from being duplicated, we can override the save method to check if any other field other than "view_count" changed, if that's not the case, we don't call super() save method to not save the object, and then don't create duplicates, the problem with this is that we need to get the current object to compare against the changes.

**Comment by mlissner** [comment]
This is great, thanks Kevin. Are you working on the trigger-based options next?

**Comment by quevon24** [comment]
Yes, i'm working on that option, i'll post here as soon as i have an update

**Comment by quevon24** [comment]
@mlissner  Looking for more information about triggers, I came across a great Django library that seems to do exactly what we want with triggers and doesn't have any problems with F expressions and we won't have any problems updating multiple records either, all this is because all this is performed at the database level using triggers.

This is the library: https://github.com/Opus10/django-pghistory

It's really easy to use, we just need to add a decorator on the models that we want to track, then we need to create some migrations, the migrations will contain a new table where the data will be copied  with almost the same name as original the model, in this format: <model_name>Event or we can specify a name.

The migration will also contain the triggers that need to be created in the database.

And that's it, we can start adding or updating objects and those will be copied to the new table without issues, and we can also revert objects.

This and other things can be done using its base library: https://github.com/Opus10/django-pgtrigger

What are your thoughts?

**Comment by mlissner** [comment]
I read through the docs today and yes, this looks like an excellent solution. Can you give it a shot on one model and we'll go from there? Something simple to start?
