### ISSUE TITLE
Allow sorting search by document date, not just filed case date

### ISSUE THREAD

**Issue by ikeboy** [freelawproject/courtlistener#1260]
Currently, courtlistener.com search allows sorting by date the case was filed, along with filters for the filed date. However, there's no way to search for _documents_ filed recently but perhaps in older cases. I want to search for all recent documents containing various keywords, but can't. Seems like a relatively simple addition to the website.

**Comment by mlissner** [comment]
OK, so that code is what's being used to sort the groupings, but I think there's less impact there than if we used that field to sort results. I think! We could try this out and see what happens.

Do you want to do a PR to add this feature behind a `is_tester` flag in the drop down? If the performance were fine, we could release it widely, if not, we'd have to re-index the entire archive before launching it widely. But either way, we'd get the feature closer to live?

**Comment by ikeboy** [comment]
I'm not sure why the direct link is failing. Just adding the front-end ability to sort by that field won't fix the backend error. 

I'm guessing it's erroring out because it times out? I tested on a few other "unofficial" fields, it works on dateArgued but nothing else.

**Comment by mlissner** [comment]
OK, so on cl.search.views:189 it crashes because `cd` is not defined. Why? Because the form is invalid (and because the failure case isn't handled properly). Why? Because in `SearchForm()` it lists all the possible sorting values and the one you provided ain't in the list:

https://github.com/freelawproject/courtlistener/blob/f189080fa8693e2675196ffb0d20c1c16306d45b/cl/search/forms.py#L18-L30

**Comment by ikeboy** [comment]
I'll write a quick PR adding this to the list

**Comment by mlissner** [comment]
Can you put it behind the `is_tester` flag too, and make sure it actually works? We have docs on how to get a working system up in DEVELOPERS.md ?

**Comment by ikeboy** [comment]
This works on my machine

**Comment by mlissner** [comment]
This is deployed to testers. Performance seems fine. I'm going to remove the beta checks and release widely.

**Comment by mlissner** [comment]
This is now deploying. Thank you for this contribution! Great little feature!

**Comment by ikeboy** [comment]
I kind of want to be able to sort by the date a document was uploaded, vs the date it was filed. Any objection to adding that to the backend? It's probably too advanced to show as an option. 

Made a quick PR for that.
