### ISSUE TITLE
opinions-cited lacks any filters; date-modified; bulk-data IDs

### ISSUE THREAD

**Issue by saizai** [freelawproject/courtlistener#1274]
For opinions-cited:
a) the API has no filters, including on id
b) there is no date-modified field
c) the bulk data lacks the IDs present in the API, so it's not possible to sync to live from bulk without downloading the whole thing through the API first.

**Comment by saizai** [comment]
Correction: it does have id exact. But not e.g. id__gte etc, so it's still not possible to get updates other than by just using a high page index w/ order by id.

**Comment by mlissner** [comment]
Good points. Want to do a PR adding filters for ID? That'd fix most of this, right?

**Comment by saizai** [comment]
@mlissner Sorry, but I don't have the energy to make a PR for this myself. :(

**Comment by saizai** [comment]
(Also, I assume that doing this would require changing your solr [or whatever you're using] configuration and executing an index, which can't be done just by a PR.)

**Comment by mlissner** [comment]
Yeah, I won't have energy either, unless it gets more traction. But this should be doable by adding needed columns to the correct table and doing a Django migration. We wouldn't need to do anything with Solr. If you just want to add filters to the `id` field, that is just a python tweak.

**Comment by saizai** [comment]
Could you point me to an example that does this on something else? I can more easily copy & tweak than create ex nihilo. (I'm not familiar with Django; I use Rails. IIRC you have a similar MVC + migrations structure, though.)

Are the necessary DB indices already there?

**Comment by mlissner** [comment]
If you look in any filters.py file, you should see how to make filters for a field. The documentation for the filters is from Django REST Framework and Django REST Framework Filters, but copy/pasting should be pretty clear. The ID field is a primary key, so it should have indexes, yes.

Migrating the DB would be hard if you're not familiar with Django. I think I'd advise against that unless you wanted a bigger project.

**Comment by saizai** [comment]
Would this require also writing a migration?

If yes, are you saying that if I PR the filters you'll handle the migration aspects? 😉

**Comment by mlissner** [comment]
I don't have time to work on this one, sorry. But if all you want to do is add filters to id fields, that wouldn't require a migration.

**Comment by mlissner** [comment]
I sort of assume this was fixed a long time ago, but let's double check as part of the v4 migration.

**Comment by albertisfu** [comment]
I checked the opinions-cited endpoint to confirm that all the points described here are already resolved:

**Regarding filters:**
  -  We already have filters for:
     - ID:
       - https://www.courtlistener.com/api/rest/v3/opinions-cited/?id=213918123
       - https://www.courtlistener.com/api/rest/v3/opinions-cited/?id__gte=213918122
     - citing_opinion:
       -  https://www.courtlistener.com/api/rest/v3/opinions-cited/?citing_opinion=9978098
     - cited_opinion:
       -  https://www.courtlistener.com/api/rest/v3/opinions-cited/?cited_opinion=621599
     
**Sorting, it can be sorted by:**
- ID asc and desc
  - https://www.courtlistener.com/api/rest/v3/opinions-cited/?order_by=id 
- citing_opinion asc and desc
  - https://www.courtlistener.com/api/rest/v3/opinions-cited/?order_by=citing_opinion 
- cited_opinion asc and desc
  - https://www.courtlistener.com/api/rest/v3/opinions-cited/?order_by=cited_opinion 
- depth: asc and desc
  - https://www.courtlistener.com/api/rest/v3/opinions-cited/?order_by=-depth
  
However, filtering or sorting by `date_modified` or `date_created` is not available because the `OpinionsCited` model does not have those fields, we'd require to added them in model.

**About bulk data.**
I confirmed that it now contains the same fields as in the API:
`id,depth,cited_opinion_id,citing_opinion_id`

Let me know if we need to do something here.

**Comment by mlissner** [comment]
After about four years we haven't seen any more requests for this, and we hit most of the important points, so I'm going to close until it comes up again.

Thanks Alberto.
