### ISSUE TITLE
Add links to last and first pages in pagination footer

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1368]
Boy I'm rusty on Django's pagination system, but we need links to last and first on dockets at least. Perhaps elsewhere too (not on search results).

**Comment by johnhawkinson** [comment]
Also should have pagination at the tops of pages.
And we need to fix ascending/descending icons to have the arrows go in opposite directions, not the numbers, so they are distinguishable on mobile.

**Comment by mlissner** [comment]
Probably doable, but tricky since we already have the filter box up there and it'd probably need to get integrated into it, but yeah, the page is LONG. Maybe the filter/pagination just goes at the top and is sticky when you scroll so it's not needed at the bottom and it's always visible.

**Comment by mlissner** [comment]
Looks like the icon is fixed in the latest font awesome version, so that's good.

**Comment by mlissner** [comment]
See also: https://github.com/freelawproject/courtlistener/issues/1434

**Comment by troglodite2** [comment]
This is the current pagination:
![image](https://user-images.githubusercontent.com/82225842/230732313-90826b67-6a9a-4199-a507-16b9b82e6efd.png)

The recommended Django method is to pass in the paginator to the template.  Then the footer would have a "First","Previous", list of pages limit X, "Next", and "Last".

I suggest that we have a simple template that will take two context variables "page","paginator" and create a div with that content.

Then we can just included it on the different lists as needed once the views.py has been updated to pass the paginator.

**Comment by troglodite2** [comment]
It is also possible to add an input to take a page number in that bar.

**Comment by troglodite2** [comment]
![image](https://user-images.githubusercontent.com/82225842/230753738-da58d05b-a4ff-46b4-a2ac-8994a36d1b69.png)

Something like this?

**Comment by mlissner** [comment]
That looks great, thanks. For reference, Yahoo! (paragon of good design choices) does this:

![image](https://user-images.githubusercontent.com/236970/230922618-95753b5c-16db-4288-89e0-03e151bf0851.png)

Bing (which has an OK design does this):

![image](https://user-images.githubusercontent.com/236970/230922719-a9c65484-6948-4587-8964-0bf13803400d.png)

(That `...` thing *is* a button, and I've clicked it, but it's really not clear what it does. Maybe it goes back to the page you were last on? I'm not sure without playing some more.)

Yandex:

![image](https://user-images.githubusercontent.com/236970/230923235-7cadf6d1-17d0-4e01-a528-84dd66dbc27d.png)

Google and DDG just have a button at the bottom that says, "More Results".

I think Bing is the winner by having an extra spot where they put page 1, but their `...` button is weird. 

It's also worth noting that none of the search engines put the Last Page. I assume that's both a UX thing and a performance thing, and I know we don't want to put that on our search engine pagination footer either. 

As far as your screenshot goes, I think it looks good. Maybe we just don't want the disabled `...` buttons though, and to include it on search pages, we'll need to remove the Last Page button? 

Thanks for mocking this up.

**Comment by troglodite2** [comment]
Not a mock up.  Coded.  I would have to go find the other calls to `includes/pagination.html` and update them but once that is done it is ready for pushing and a PR.

Search engines don't put a "last page" because they don't know what the last page might be.

Because design is hard:
1. do you like the double left and double right caret indicating first and last.  
2. would you prefer something like |< and >| for first and last
3. Do you want the ellipses before and after the page list
4. Do you want text with the first, previous, next, and last buttons
5. Do you want a different look/feel from `btn btn-default` for the numbers?  If so do you have a CSS class string for me to use?

**Comment by johnhawkinson** [comment]
Our pagination is a little different from most, in that we have docket entries indexed by numbers that mean something, and some of our users care about those numbers.

E.g. I am on page 1 and I want to see docket entry 354 and surrounding entries: which page number do I click on? I don't want to bother to limit the doc range to 300-400, but I could do that, it's just annoying.

So, it might be nice for us to have some way to indicate what docket entry range a given page indicated. As all things, mouseovers are not preferred, but maybe the design would be too cluttered otherwise.

I do like the idea of having an input to accept a page number—all too often in the past I have edited the URL by hand, which is annoying. Perhaps that input could be combined with the `…`.

I do not make good UI judgments when presented with a single choice, but there are people better at UI design than I.

**Comment by troglodite2** [comment]
@johnhawkinson Something like this:  NOTE this is not styled or positioned correctly, just a UI option
![image](https://user-images.githubusercontent.com/82225842/230929234-bdfc6fe8-bb6a-4c80-ae10-0b1add70ec06.png)

There are some real coding issues involved.  I've seen a docket where entry number was some huge value which didn't seem to make sense.  My guess is that it was a reference back to the pacer document.

In addition, this has to be generic for different lists.  Asking for a page number is very generic, asking for a Docket Entry is not.

**Comment by mlissner** [comment]
Talking to @johnhawkinson via chat, it seems like his use case will be sufficiently satisfied by the `Last` buttons. 

A few other replies:

> Search engines don't put a "last page" because they don't know what the last page might be.

Yeah, that's a good point. We actually do, but if people try to go to it, that makes our server explode unless the result set is small. :)

Other questions:

>     do you like the double left and double right caret indicating first and last.
>     would you prefer something like |< and >| for first and last

I think the double is better.

>     Do you want the ellipses before and after the page list

No, let's yank those. They seem confusing to me.

>     Do you want text with the first, previous, next, and last buttons

We do this currently on larger screens but not mobile. I think that's a good approach?

> Do you want a different look/feel from btn btn-default for the numbers? If so do you have a CSS class string for me to 
> use?

No, they look great to me.

**Comment by troglodite2** [comment]
I thought I had replied, sorry.

![image](https://user-images.githubusercontent.com/82225842/231030022-8b0ef26a-71ec-40ac-bda4-0b74a2a9d57d.png)

If this is a go, then I will either do a PR with just docket or if you prefer I'll search out the other uses of pagination.html and replace them with new_pagination.html.  NOTE: I have not brought webhooks processing over to the new_pagination.html.

**Comment by mlissner** [comment]
Yeah, that looks great to me. If you don't mind checking around to see where else this should be applied, that'd be great. Could you do one include with a variable that's passed into it? 

So:
```
{% include blah.html with numbers=on show_last_page_link=off %}
```
Or something like that?
