### ISSUE TITLE
Nebraska Scraping Fail

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1452]
[307 Neb 1 over and over](https://www.courtlistener.com/c/Neb./307/1/)

I stumbled onto a duplicating opinion bug that is repeatedly allowing cases to be collected over and over and over again.  The case above has been scraped and added to our system 21 times as of 11/9/20 at 3:22 PM EST.

**Comment by flooie** [comment]
This may just a Nebraska issue but a but in the REST API is curtailing a deeper dive into the problem.  

It appears that in 2017 we started capturing the same opinion multiple times, and it is now becoming a larger issue for anyone that wants to research Nebraska case law. 

```
Volume 294 has 71 opinions.
Volume 300 has 1719 opinions.
Volume 307 the current volume already has 460 opinions.
```

Additionally, we have listed in volumes, Volume 925- which is not real.  The volume should have been added to Vol 295. 

It is unclear how or why this is happening.  This needs further investigation

**Comment by flooie** [comment]
This is still quite a problem.  And should be addressed because its causing issues in the opinion import.

**Comment by quevon24** [comment]
The problem is caused because the sha generated from content mismatch causing the creation of duplicates.

The sha doesn’t match because the stamp on the document changed

For example, in https://www.courtlistener.com/opinion/9303423/bleich-v-bleich/ we have:
![image](https://user-images.githubusercontent.com/6474994/206011675-e23f339a-93b6-488c-b321-c127fc64106a.png)

And in the duplicate: https://www.courtlistener.com/opinion/9303466/bleich-v-bleich/
![image](https://user-images.githubusercontent.com/6474994/206011697-bebae90f-cf04-4631-929e-303b5c50092d.png)

**Comment by quevon24** [comment]
The problem started in volume 292: https://www.courtlistener.com/c/neb/292/

This volumes are missing: 281, 282, 283, 284, 287, 288, 289, 290, 291

And the volumes, starting from 280, are incomplete.
