### ISSUE TITLE
Escape arrows in opinion HTML

### ISSUE THREAD

**Issue by mattdahl** [freelawproject/courtlistener#1491]
I was recently perusing Alito's dissent in _Bostock_ (as one does) and noticed that the HTML for his opinion is horribly broken: https://www.courtlistener.com/opinion/4760997/bostock-v-clayton-county/

It would seem that Alito quoted a dictionary containing the string `respectively  designated  male or female <a member of the opposite ~> 2: the` and the `<a` part became interpreted and rendered as the beginning of an `a` tag.

I think this could be fixed by simply escaping the `<` and `>` characters when we import the opinion text?

**Comment by mlissner** [comment]
Wow. Yeah, I know that one of our vulnerabilities is that a court could embed nasty stuff in one of their opinions. I guess it finally happened sort of. I'm not sure that we have a particularly good fix for this. The easy solution, I suppose is to do what you say though, and to start encoding opinion text before putting it in the DB. We can't easily do that for all historical cases (it'd take an ETL script), but we can certainly start doing it going forward. 

Do you want to take a stab at it, @mattdahl? I'm going to fix this one by hand right now.

**Comment by mlissner** [comment]
OK, so the plaintext is not currently considered safe in our HTML (see last if block):

```
<div id="opinion-content"> {# used by Zotero, Juris-M #}
                                {% if sub_opinion.html_with_citations %}
                                  {% if cluster.source == "C" %}
                                    {# It's a PDF with no HTML enrichment #}
                                    <div class="plaintext">{{ sub_opinion.html_with_citations|safe }}</div>
                                  {% else %}
                                    <div class="serif-text">{{ sub_opinion.html_with_citations|safe }}</div>
                                  {% endif %}
                                {% elif sub_opinion.html_columbia %}
                                  <div class="serif-text">{{ sub_opinion.html_columbia|safe }}</div>
                                {% elif sub_opinion.html_lawbox %}
                                  <div class="serif-text">{{ sub_opinion.html_lawbox|safe }}</div>
                                {% elif sub_opinion.xml_harvard %}
                                  <div class="serif-text">{{ sub_opinion.xml_harvard|safe }}</div>
                                {% elif sub_opinion.html_anon_2020 %}
                                  <div class="serif-text">{{ sub_opinion.html_anon_2020|safe }}</div>
                                {% elif sub_opinion.html %}
                                  <div class="serif-text">{{sub_opinion.html|safe}}</div>
                                {% else %}
                                    <!-- NOTE here: This lacks the |safe filter -->
                                    <pre>{{sub_opinion.plain_text}}</pre>
                                {% endif %}
                            </div>
```

So if you put `&gt;` into it, you see `&gt;` on the front end. This means that deleting the rendered HTML is all it takes to fix this issue, so that's what I did in this case. So I think we have a choice to make:

1. If we want the plaintext to contain HTML entities, we need to add the `safe` filter to it on the front end.

1. If we just want the HTML to be correct, we need to encode `<`, `>` and whatever else as part of our transformation pipeline.

I think I prefer the later route. It lets us continue having a plaintext field in the DB, and it fixes the issue in the narrowest way possible.

Thoughts?

**Comment by mattdahl** [comment]
Sorry for the slow response. Either of those approaches seem fine to me, so I will defer to you when you say you prefer the second.

I think I can fix this, but I can't do anything until this weekend. This is the pipeline function where the encoding should happen, prior to each doc's `opinion.plain_text` being set, right? https://github.com/freelawproject/courtlistener/blob/c336e7f8728a45b0492ff5a78146f2cbc68b3cd5/cl/scrapers/tasks.py#L278

Do you think there are any other HTML entities besides `<` and `>` that need to be encoded?

**Comment by mlissner** [comment]
Probably ampersands too? I suspect Django has a utility for this. Before you work on this though, @flooie can you chime in about whether @mattdahl is targeting the right method and indeed whether that method has a future? Perhaps this needs to get done in BTE?

**Comment by cweider** [comment]
The OWASP [recommendation](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.md) is for these characters to be escaped:

```
& --> &amp;
< --> &lt;
> --> &gt;
" --> &quot;
' --> &#x27;
```

Aside: I was shocked to learn that forward slash was [*removed* in 2020](https://github.com/OWASP/CheatSheetSeries/commit/d7a6823db92af82da3f9538b23b03851d7556d78). Evidently, this is because HTML5 is ubiquitous and nobody need worry about [weird SGML implementations that were the rationale](https://security.stackexchange.com/a/151424).
