### ISSUE TITLE
More informative error message on recap-fetch POST

### ISSUE THREAD

**Issue by hjohns12** [freelawproject/courtlistener#1542]
When inputting the wrong PACER username/password on a recap-fetch POST, the HTML returned gives: 

`<title>Server Error 500 – CourtListener.com</title>`

A more informative error message would be great here!

You can test this by putting in the wrong username or password into a one-liner such as this one: 

`curl -X POST --data 'request_type=1' --data 'pacer_username=USERNAME' --data 'pacer_password=PASSWORD' --data 'docket_number=5:18-cr-00765' --data 'court=ohnd' --data 'show_parties_and_counsel=true' --header 'Authorization: Token TOKEN' https://www.courtlistener.com/api/rest/v3/recap-fetch/
`

**Comment by mlissner** [comment]
This was weird enough I wanted to figure out what was going on. Turns out that we were catching a login exception, but then accessing an attribute of the exception that didn't exist. Fixed in c69b3687a866d42073fbfc0887ab55a867729811. 

This also identified two other places we had the same pattern that are now fixed. Both low impact (again, related to logging exceptions).
