### ISSUE TITLE
Citation Look Up Tool: return opinion with contained page number

### ISSUE THREAD

**Issue by handofthecode** [freelawproject/courtlistener#1599]
This url https://www.courtlistener.com/c/U.S./407/143 returns Adams v. Williams, 407 U.S. 143
 
It would be really useful if there was a way to return the same opinion if a different page within the Adams v. Williams opinion was queried.

Right now https://www.courtlistener.com/c/U.S./407/146 doesn't work.

The next opinion in the volume is page 163 so .../U.S./407/143 to 162 would return Adams v. Williams, and 163 would return Moose Lodge No. 107 v. Irvis, 407 U.S. 163.

Is this a possible feature?

**Comment by mlissner** [comment]
So I guess this is technically feasible. We'd just have to do something like:

 - Query the requested citation
 - If no results, try a range query with some upper limit of page numbers (maybe 50 pages, say?)
 - If that has results, return the highest one.

I think in practice, this looks like:

```
In [5]: ocs = OpinionCluster.objects.filter(citations__reporter="U.S.", citations__volume="407", citations__page
   ...: __range=[100, 145]).latest('citations__page')

In [6]: ocs
Out[6]: <OpinionCluster: 108571: Adams v. Williams>
```

That's a bit of a mouthful, but it returned the right item at the end, and you can see we did page 100 to 145. The performance was fine. 

This would get merged into the code around here:

https://github.com/freelawproject/courtlistener/blob/master/cl/opinion_page/views.py#L651-L662

------------

I have a couple questions though, before we did that:

1. How many pages backwards would we want to go? I guess we could just pick a big number. The trade off is performance mostly.

2. Is there any way to catch false positives with this? Say we're missing Adams v. Williams. If so, we'd probably return the prior case. That's not great and might be enough to sink this whole concept until we're certain we have every citation.

3. How do we communicate this to the user, both in the website and to computers? A message to users might do it and would be pretty easy: "We were unable to find that citation, but we were able to find this case slightly earlier in the book." We could do better there.

    For computers, we could use the 303 status code, "See Other", and redirect to the other location. That feels about right, and might be fine if documented.

--------------

The other, much larger, approach to this would be to parse for ending page numbers, so that we know how many pages each case is, and then we can store that in the DB. 

I suppose we could do that larger fix as a safety mechanism to resolve number 2 above. That is, if we find an earlier hit, we check how many pages it has by parsing it and only return it if it's reasonable. Ugh, messy though.

**Comment by handofthecode** [comment]
I think you've nailed it. Once you have the ending page, (or total pages would work too) for each opinion can you use a comparison operator in the db query to get the correct opinion with one query?

`ending page > query page && starting page < query page`

**Comment by mlissner** [comment]
Yep, that'd be really cool. I don't think this is a priority for us right now, but if you wanted to run with it, we'd be happy to provide guidance and work to get a PR pulled through.

**Comment by flooie** [comment]
I think this is the wrong approach, but I had an idea that works - atleast some of the time.

We can just query for any opinion in the reporter that has html citations with page numbers.   

```
page = XXX <-- the page we want 

OpinionCluster.objects.filter(
   citations__reporter=reporter,
   citations__volume=volume,
    sub_opinions__html_with_citations__contains=f"*{page}"
)
```

@mlissner @handofthecode

**Comment by flooie** [comment]
This works on my machine - we just slot it into the citation opinion page view - if the cluster count is returned as 0 and viola...?

**Comment by mlissner** [comment]
That's interesting. So instead of looking for the citation, you look for the reporter and volume where the text contains the star pagination. It seems like a good step as part of a heuristic approach to this look up. The performance might not be great — if volume & reporter returns 1,000 pages of content, our query will have to parse through all of those, but maybe that's fine. I wonder which approach is better, the range query approach I proposed or this. One will be more accurate. One will be faster....

**Comment by flooie** [comment]
My original idea this morning was to do an alphanumeric sort, Identify the immediate preceding opinion (if any) pull all the page citations and check if it is contained.  You could do a hybrid approach where you find the immediate preceding opinion and check the star pagination on that one case- otherwise return 🤷 to the user.

I was just attracted to the simplicity of the code here.

**Comment by flooie** [comment]
@mlissner 

I have a split the baby solution.  After some face to face conversations I think we settled on using both methods.
