### ISSUE TITLE
Swagger (OpenAPI) schema contain wrong URLs

### ISSUE THREAD

**Issue by elibrin** [freelawproject/courtlistener#1616]
The Swagger (OpenAPI) schema contain wrong URLs to the API.
For example: https://www.courtlistener.com/api/rest/v3/api/rest/{version}/dockets/

Step to reproduce:
1.  Browse to:  https://www.courtlistener.com/api/swagger/
2.  See the links in the returned json.
3.  Link points to wrong location. and
4.  {version} is in the path

**Comment by cite-reader** [comment]
The duplication of the `/api/v3/` fragment isn't the only issue with the paths object. Field names of the paths object (that is, the urls at which the API endpoints may be found) are not meant to be absolute URLs: "A relative path to an individual endpoint. The field name MUST begin with a slash. The path is appended (no relative URL resolution) to the expanded URL from the [Server Object](https://spec.openapis.org/oas/v3.0.2#serverObject)’s url field in order to construct the full URL." ([OpenAPI specification version 3.0.2, § 4.7.8 Paths Object](https://spec.openapis.org/oas/v3.0.2#paths-object)). _That_ issue is a result of encode/django-rest-framework#7631; the issue is marked as stale, but the maintainers seemed amenable to receiving a PR that fixes it in their last comment, so I'll see if I can get that fixed myself.
