### ISSUE TITLE
Monitoring and reliability of recap.email

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1636]
How do we make sure that recap.email is as reliable as possible, and how do we make sure that failure modes are as loud as possible?

**Comment by albertisfu** [comment]
@mlissner  I’ve analyzed which actions we could take to improve the monitoring and reliability of recap.email:

**Metrics about inbound emails from PACER:**

I check that it’s possible to monitor the number of emails we receive from PACER.  I did some tests with my AWS testing account. It’s possible to add a rule to SES that publish into an SNS topic every time we get an inbound message (in addition to saving it to S3 and sending it to Lambda).  It’s possible to monitor that metric afterwards on Cloudwatch.

Seems that it has some delay to count the inbound messages but it works. It might be useful to have statistics about the number of inbound messages we receive from PACER over a period of time.
![cloud](https://user-images.githubusercontent.com/486004/180495127-fa5cc473-9b37-440e-b948-02636d50a1eb.png)

**Lambda:**
To monitor that the Lambda function works well I think the best thing to do is to add Sentry (If free law account allows it) I’ve checked and the implementation it’s pretty simple.

It’s just necessary to create a new project for AWS Lambda Python.
Create a new ***environment variable*** SENTRY_DSN for the Lambda and sentry to the lambda.

I’ve submitted a PR with the changes that are needed to the lambda function, I tested it in my testing function and it works well. [#8](https://github.com/freelawproject/awscloud/pull/8)

**CL**
On Courlistener side I think we are covered with sentry but If we want to be sure that every message that we receive from PACER is properly processed or to find out how many messages failed to be processed or to get their document.

It might be useful to add a Django command that every day/every week counts the number of new messages that are stored in S3 and compare with the number of new entries on `/api/rest/v3/recap-email/` also might be possible to check if every message got a recap document (PDF) or how many failed, so we could send a report to admins every day or every week.

**About webhooks:**

To make them reliable we need to implement a retry policy and also report logs, these will apply in general for all our webhooks.

The logs proposal is [here](https://github.com/freelawproject/courtlistener/pull/2156#issuecomment-1185769913)

About the retry policy, I’ve read how other services handle retries. 

e.g: Stripe shows when a webhook fails and when it’s going to be retried, also the webhook is disabled after a certain number of errors in a period of time.

So I think we have two options:

**Don’t retry celery tasks and use an external exponential backoff retry method:**

If we want to let users know when a webhook fails and when it’s going to be retried again or when we've stopped retries we would need to use the following approach:

- Don’t retry the `send_docket_to_webhook` celery task if it fails, so the WebhookEvent is created and it’ll be shown on the user's webhook panel as failed.
- We can use an external exponential backoff retry similar that the one we use to retry emails so that when a Webhook event fails we schedule a new task that will retry the failed webhook after e.g: 2 hours, if it fails again it would be retried after 4, 8, 16, 32 hours, etc.
- So we could inform users about the WebhookEvent status, when it’s going to be retried again or if no more retries will be attempted.

**Use celery retries as our exponential backoff policy and count errors.**

This option might be easier to implement but not as clear for users that the previous one.

Here we could take advantage of the celery retry system by adding an exponential backoff policy for the task, so in case of a failure, celery will retry automatically following an exponential backoff until the task succeeds or the max num of retries is reached.

The problem here is that since the Webhook event it’s not created until the task succeeds we are not going to be able to inform users about fail events until it succeeds or definitely fails.

For example, if we have a backoff policy to retry a task for 72 hours, the user wouldn’t be able to see the failed task before 72 hours.

**About disabling a Webhook**
- I think it could be triggered based on the total number of failures of a webhook or the number of failures over a period of time. So that when a webhook reaches a defined threshold we automatically disabled the webhook and we can send an email to the user to inform them about the decision and possible actions to follow.

Let me know what you think about these proposals.

**Comment by mlissner** [comment]
>  It might be useful to have statistics about the number of inbound messages we receive from PACER over a period of time.

Agreed, that seems great.

### Sentry...

Great. Merged.

### Celery retries...

Let's create a new issue for this, but would a solution like this work? I hate the empty exception, but maybe it'd do what we want: https://stackoverflow.com/a/27951681/64911

### Disabling webhooks...

Let's create an issue for this too, but I know stripe is very strict about this. If a webhook fails after retrying a few times, they send an email about it. Their disable logic is described as:

> In live and test mode, Stripe will attempt to notify you of a misconfigured endpoint via email if an endpoint has not responded with a 2xx HTTP status code for multiple days in a row. The email also states when the endpoint will be automatically disabled.

https://stripe.com/docs/webhooks/best-practices

**Comment by albertisfu** [comment]
Thank you for your answers and opinion!  I've opened the issues for retries  #2207  and webhook disabling #2208

About the metrics for the inbound recap.email messages, let me know if I should try to add it on the SES panel, I'm not sure if I have the right permissions but I could try it if you agree.

**Comment by mlissner** [comment]
Sure, see if you can. If not, let's just do it together?

**Comment by albertisfu** [comment]
Seems that there is a permission issue when trying to add the SNS topic, so let me know when you're available and we can it together!

**Comment by mlissner** [comment]
I was going to close this issue, but I didn't see this before:

> It might be useful to add a Django command that every day/every week counts the number of new messages that are stored in S3 and compare with the number of new entries on /api/rest/v3/recap-email/ also might be possible to check if every message got a recap document (PDF) or how many failed, so we could send a report to admins every day or every week.

I think that's a good idea. How many hours would you expect it to take, roughly?

**Comment by albertisfu** [comment]
Yeah, I think it might be useful!  I'm not totally sure how hours it would take because sometimes it pops up some issues to solve that I haven't considered. But for now, I think it might take two days to have the first draft, roughly.

**Comment by mlissner** [comment]
> I think it might take two days to have the first draft, roughly.

Let's just remember that this is possible. I think between Sentry and our other monitoring systems, we'll be OK without this. Closing this issue!
