### ISSUE TITLE
Develop feature/method to share original PACER HTML

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1701]
We've received a request from researchers to access the HTML that we receive from the RECAP extension. 

In the past, we have never shared this data because we believed it simply wasn't worth the effort to anonymize the HTML so that it could be shared properly. (For example, it has usernames and PACER account information in the footers.)

Now that we have a client that is interested in contracting us to do this work, we need to consider whether there are any issues with actually doing this work. I think if we pull out the usernames before sharing the data and if we disallow rapid access to the data, we should be OK. We won't be sharing anything like IP addresses — just the static HTML.

I'd be happy to hear alternate views or concerns.

**Comment by mlissner** [comment]
It's worth noting, I suppose, that we share PDFs from the extension by default and that's been the purpose of it for a decade. Sharing HTML feels quite analogous (but of course HTML has more identifiers).

**Comment by johnhawkinson** [comment]
I think it would be very helpful to have access to docket HTML, especially because of limitations of Juriscraper's parser, which loses information. I would tend to think the answer is to cut off the receipt table entirely (if present).

I do note that we have historically had some concern about personal information of parties from docket reports — we omit email addresses when we show those reports. I don't know to what extent that is still a concern. Certainly not for researchers, but maybe if we made it generally public. But redacting emails on the fly by regexp is not a heavy lift.

**Comment by berkough** [comment]
> I think it would be very helpful to have access to docket HTML, especially because of limitations of Juriscraper's parser, which loses information. I would tend to think the answer is to cut off the receipt table entirely (if present).

I agree with this. I think NextGen systems have less information in the receipt portion, but if there is an obvious client code and a simple username, that data could be used to extrapolate quite a bit, and is cause for concern if that information were publicly available (especially if it were possible to compile on a username basis). It also contains search criteria that may not be a straight forward case number query.

**Comment by johnhawkinson** [comment]
@berkough:
> I think NextGen systems have less information in the receipt portion,

Really? Do you have an example, that is not my experience.

Here are a pair of receipts from adjacent NextGen and CurrentGen courts, which one do you think has less information?

<img width="454" alt="Screen Shot 2021-06-03 at 14 37 23" src="https://user-images.githubusercontent.com/1270718/120695530-836d5700-c479-11eb-8b60-3b8ba8703891.png">
<img width="470" alt="Screen Shot 2021-06-03 at 14 37 30" src="https://user-images.githubusercontent.com/1270718/120695534-8405ed80-c479-11eb-8d27-351b5b793400.png">

> but if there is an obvious client code and a simple username, that data could be used to extrapolate quite a bit, and is cause for concern if that information were publicly available (especially if it were possible to compile on a username basis). It also contains search criteria that may not be a straight forward case number query.

Oh, that brings up an important point. The search criteria in the docket report would be helpful to most people parsing, especially if they produce a partial result and the reader wants to know how partial it is. So it would be better to redact the client code and username (err, and PACER userid, if present) from the receipt, rather than to omit the receipt entirely.

**Comment by berkough** [comment]
> Really? Do you have an example, that is not my experience.

You're correct, the PACER userid is the difference. I was thinking of the "Docket Activity Report" and not specifically the "Docket Report."

>So it would be better to redact the client code and username (err, and PACER userid, if present) from the receipt, rather than to omit the receipt entirely.

Definitely redact or omit this data entirely.

**Comment by johnhawkinson** [comment]
> You're correct, the PACER userid is the difference. I was thinking of the "Docket Activity Report" and not specifically the "Docket Report."

It is somewhat of a running joke in these parts that I do not understand why anyone would ever run the _Docket History Report_ ("History/Documents..." menu option) in preference to the _Docket Report_. But the _Docket Activity Report_ is a different beast (that's the one with hour/minute/seconds timestamps!), not available in every court (and sometimes available but unlisted in the menus), and not transmitted or parsed by RECAP.

<img width="255" alt="Screen Shot 2021-06-03 at 15 45 06" src="https://user-images.githubusercontent.com/1270718/120703057-d13a8d00-c482-11eb-913f-2dfbdd71faba.png">
<img width="358" alt="Screen Shot 2021-06-03 at 15 45 17" src="https://user-images.githubusercontent.com/1270718/120703058-d13a8d00-c482-11eb-981c-0d9a1145bd24.png">


Indeed, this discussion does beg the question of whether the extension should send all (most?) unknown HTML to the RECAP server which can the save it and somebody else can parse it later. E.g. _Docket Activity Reports_ or other cool things.

**Comment by mlissner** [comment]
I haven't built this into our pipeline, but we have code now for anonymizing dockets and we've shared a bunch of HTML that way. For now the safe thing is to keep it limited that way, so we're not removing data from dockets by default. When we feel more confident about the system or when we get more push to use it by default, we can put it in our pipeline, but for now I'm closing this because it's good enough.
