### ISSUE TITLE
Financial Disclosure Release Fix List

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1788]
We've released the financial disclosure database.  Hooray.  

Now it's time to fix all the bugs we've now found.  

- [x] Select the most recent disclosure instead of the oldest disclosure. 
- [x] Instant search results sometimes start halfwidth before expanding to full width
- [x] People don't like S's when $ are correct  (this was processed once already with a given set of rules)
- [x] Need to decide if 5 judges in the dropdown is still enough.
- [x] transaction_during_reporting_period missing from investment field. ******** Not sure how this happened 
- [x] Should reorder tables to reflect order in disclosure.  Investments (when large) dwarf the rest of the page
- [x] Crowdsourced corrections?

**Comment by mlissner** [comment]
Well, you found the edge case we were after. Good one. I don't see any solutions I love:

 - Paginated results (hard to do, kind of annoying)
 - Sort of like pagination, you could put a link on the bottom of the drop down when there are more results from the API. The link could load more results into the drop down (harder, probably annoying), or maybe it could just take you to the judge search page for the query (not great, but workable).
 - More results (these get longer, but they could be in a scrollable drop down)
 - Better relevancy (scotus goes first? Still, kinda hard to use. Maybe put last name matches first? Seems annoying to tinker with.)

I guess I like option 3 best. Just return like 50 results by default (assuming performance is fine), and then let people scroll inside the drop down. I bet performance would be fine.

**Comment by mlissner** [comment]
> so if you do C Thomas,  it'll return him exactly.

I'm not sold on this. It feels like a patch to make a specific way to query work better, but it doesn't fix the general problem of too many matches for whatever weird idea somebody has. Why not add a scrollbar in there? 

I'm also seeing weird results for the query `thomas c`. I think it's because the `c` returns lots of weird results. Should these queries be using `__istartswith` instead of `__icontains`?

**Comment by flooie** [comment]
Thats an excellent point.  I think there is some good cleanup ability in this without having to hack it.

**Comment by mlissner** [comment]
I just closed this, but I might as well use it to track a few more items I just found:

- [ ] Longer disclosure pages have really bad react loading. They need some sort of spinner or something. See [here](https://www.courtlistener.com/person/189/disclosure/28428/maryanne-trump-barry/)
- [ ] When we don't know the page number for a row, we have links that say `page=undefined` on the end. Not ideal.
- [ ] The investments table is hard to read since it scrolls left/right. I'm not sure the solution here. Either you give it more horizontal space (which means no sidebar) — maybe this is a solution — or you make scrolling easier (sticky scrollbar? buttons?) or you make the table narrower (better wrapping?)
- [ ] This string on the Person page should be tweaked a bit:
    > An annual financial disclosure by Federal judges, magistrates and clerks of the court.

    Probably it could say this instead:

    > Annually filed financial disclosure records for federal judges, magistrates and clerks of the court.

**Comment by mlissner** [comment]
For these last three items:

1. We can probably live without improving the load, I guess. It might be nice if the sidebar didn't show up on the left and then flash to the right, but I guess we can live with it for now.

2. This should be an easy fix we should do.

3. I don't know how to make these tables narrower unfortunately. We could use the value codes instead of writing out `1-15000 (A)` or whatever, but that only gets you so far.

Maybe we just fix #2, and we say the rest are...fine.

**Comment by mlissner** [comment]
Did you verify this one is fixed? I don't recall seeing a fix for it come through: 

> When we don't know the page number for a row, we have links that say page=undefined on the end. Not ideal.

**Comment by flooie** [comment]
@mlissner I can't find an example to take a look at the page=undefined.  But im also a little baffled by it because page must be saved as an integer to be in the database.

**Comment by mlissner** [comment]
yeah, weird. I see that in the model. 

Check out Mrs. Trump though: 

https://www.courtlistener.com/person/189/disclosure/25285/maryanne-trump-barry/

If you hover over the first little icon in the Positions table, it takes you to:

https://storage.courtlistener.com/us/federal/judicial/financial-disclosures/189/maryanne-trump-barry-disclosure.2003.pdf#page=undefined

**Comment by mlissner** [comment]
Maybe it's just that positions don't ever have page numbers and so shouldn't get page number links. Looks like that's the case. :)

**Comment by flooie** [comment]
yes.  its an investments field... I think.
