### ISSUE TITLE
Timezones in email alerts seem off from even the website

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1790]
It's well-known that our timezones aren't what they need to be, but we have a particular bug that's interesting today. In entry 522 of this docket, the date in PACER is the same as the one on the docket, but the one in the email is different:

https://www.courtlistener.com/docket/6157768/sinco-technologies-pte-ltd-v-sinco-electronics-dongguan-co-ltd/?filed_after=&filed_before=&entry_gte=522&entry_lte=522&order_by=asc

PACER and Docket show the 15th:
![Screenshot 2021-10-16 8 37 48 AM](https://user-images.githubusercontent.com/236970/137815339-e978880d-e331-49a8-9962-f9a8973be1e0.png)
![Screenshot from 2021-10-18 15-29-47](https://user-images.githubusercontent.com/236970/137815340-b1783f71-23ae-4306-a6ac-8787c74d9bd8.png)

Email shows the 16th:
![Screenshot from 2021-10-18 15-30-10](https://user-images.githubusercontent.com/236970/137815353-7f9a1226-c1e8-4bba-a169-731d9ddcf5f4.png)

**Comment by albertisfu** [comment]
I've reviewed this issue in detail. 

I checked RECAP uploads HTML docket files related to this docket and in all the uploads from Oct 15-Oct16, 2021 the 522 entry has the `date_filed`: Oct 15, 2021. 

I don't believe this is a Timezone issue since the date_filed is a `DateField` field it doesn't store time zone data. So in this case the data stored is `2021-10-15`, so it's shown in the email template as is stored, with no timezone conversion.

I think the problem here was the docket entry date_filed was wrong (2021-10-16) from the original source (maybe the RSS scraper) you can notice the description in the Docket alert in your screenshot is short "Notice (Other)" while in PACER and in the RECAP docket the description is now longer, so the `date_filed` would have been fixed afterward with a RECAP upload.

I triggered the same docket alert using uploading the docket HTML file from RECAP uploads, where the date is correct, and the docket alert filed date looks good:

![Screen Shot 2023-01-11 at 16 50 19](https://user-images.githubusercontent.com/486004/211934930-558443b4-10af-4de9-ac6d-0cbd69982e33.png)

I tried to find the RSS stored for this court that might contain the wrong date, however from the admin is not possible to filter by date and court, so maybe if we want we could get all the RSS stored via Django shell for `cand` and the day `2021-10-15`.

Let me know what do you think.

**Comment by mlissner** [comment]
I forget do you have access to the S3 bucket where we store the RSS items?

**Comment by albertisfu** [comment]
Yeah, I do have access to S3. However, looking for the right RSS within S3 seems a bit complicated since there can be hundreds of files in a single day and files don't have a name that could help to identify those ones that belong to a specific court (Is there a trick that I may be overlooking?)

Also, the `RssFeedData` is only linked to a court so the only way to look for an RSS object that might contain data from a docket we are interested in is through the `date_created`, it might be a good idea to add a possibility to filter `RSSFeedData` objects by a date range in the admin.

So, if we can identify objects related to the court and dates of interest it would be easier to find the file in S3 using the file name.

**Comment by mlissner** [comment]
> (Is there a trick that I may be overlooking?)

No, they're just a UUID b/c I'm lazy and didn't want to think about better file names.

> it might be a good idea to add a possibility to filter RSSFeedData objects by a date range in the admin.

Sure. Want to add that, then we can return here? 

I think when I need to do this, I usually wind up grepping a bunch of RSS feeds. The RssFeedData object has a method, I think, for easily getting its content.

**Comment by albertisfu** [comment]
Yes, of course, I'll add the date range filter so we can find the source.

Thanks!

**Comment by albertisfu** [comment]
Ok, working on this I realized the data range filter was not needed since it's possible to filter by date range now using the admin, I was just passing the params incorrectly.

You can filter by the court and data range by passing the following params:
```
https://www.courtlistener.com/admin/recap_rss/rssfeeddata/?court=cand&date_created__gte=2021-10-15&date_created__lt=2021-10-16
```
So I was able to find the `RssFeedData` that originally added the docket entry, so now I understand the problem.

This is the entry in the feed:
```
<item>
<title>3:17-cv-05517 Sinco Technologies Pte Ltd. v. Sinco Electronics (Dongguan) Co. Ltd., et al</title>
<link>https://ecf.cand.uscourts.gov/cgi-bin/DktRpt.pl?317399</link>
<description>[Notice (Other)] (&#x3C;a href=&#x22;https://ecf.cand.uscourts.gov/doc1/035121178264?caseid=317399&#x26;de_seq_num=1709&#x22; &#x3E;522&#x3C;/a&#x3E;)</description>
<guid isPermaLink="true">https://ecf.cand.uscourts.gov/cgi-bin/DktRpt.pl?317399&#x26;1709</guid>
<pubDate>Sat, 16 Oct 2021 02:46:51 GMT</pubDate>
</item>
```
Dates are in` GTM/UTC` timezone.

And we just store the docket entry  `date_filed` using the day, month, and year, that's why the docket alert was triggered with the date: `Oct 16, 21`

So the solution for this issue I think is:

Convert the `date_filed` to a DateTimeField.

We'll need a DB migration and a query to convert current dates to DateTime format.

It would be good to also add the timezone to the docket alerts.
So it says something like: **Date Filed:** `Oct. 15, 2021, 11:46 p.m. PDT` otherwise if we only show the date `Oct. 15, 2021` depending on the court timezone that published the docket entry, the day may change e.g:

If a court is in New York and publishes a docket entry on `Jan 14, 2023,  01:00 am  EST` -> `Jan 14, 2023, 06:00 am UTC`
We'll store the UTC date-time on DB: `Jan 14, 06:00 am UTC`

Since the server works on PDT time the date-time will be: `Jan 13, 2023,  10:00 PM  PDT `

So if we only show the date without the time zone in the docket alert it will say: `Jan 13, 2023,` when the right date according to the court time zone should be: `Jan 14, 2023`

So adding the timezone in the docket alert will be helpful: `Jan 13, 2023,  10:00 PM  PDT `

Let me know what you think about this proposed solution.

**Comment by mlissner** [comment]
Well, OK, this has been an issue for a long time, unfortunately, and one that @johnhawkinson has been bugging me about for equally as long. I guess we need to think about all of our inputs and outputs for this field and decide how to handle them. 

A few thoughts:

1. We have filing dates that come to us as datetimes and ones that come just as dates. For example, when we scrape emails or RSS feeds, we get datetimes, but when we scrape HTML dockets, we only get the date, which would need to be converted. How do we convert the dates into something reasonable, if we have to decide on a particular time before putting it in the DB?

2. The API currently returns a date. Do we just continue it this way by coercing the new datetime field into a date, and then when we release a breaking API change down the road, we include this fix too? 

    If so, that's OK for me, but replication users might have more trouble with the change to the field.

4. Do we use the date fields to look things up or do ordering? If so, how do those things break?

5. We should store these times as UTC in the DB. When we present the dates to users, ideally we use the timezone of the court, which we have in a variable somewhere. So if it's an alert for a NY court, the dates should be in eastern timezone. If CA, they should be in Pacific timezone. There's one court that spans a timezone. I think we just do our best with that one.

Ultimately, this isn't an easy change at all, but it'd be a nice thing to do. Also, if we're going to ingest the Troller BK data, which is all RSS feeds, I guess we should do this first, probably.

Do you want to analyze the questions above and see where you land?

**Comment by albertisfu** [comment]
Great, I've analyzed the points above.

Since HTML dockets only have a date, yes we need to decide which time are we going to append to the date, maybe just adding `00:00:00:000000` as time? 

The API thing seems like a breakthrough change for users, so yes it should be handled carefully. But if we start using datetimes for the docket entries API we should also consider that some objects will have a fake time (the ones extracted from HTML dockets). So it won't be a reliable field if users want to do something with it, so maybe this change won't add value for API users?

About using the `date_field` for ordering or looking for objects, I think it won't be an issue, since we use the `entry_number` or the `recap_sequence_number` to order docket entries, and the `recap_sequence_number` could be also generated using the `datetime` however we might consider doing a conversion before using the court time zone, so the `recap_sequence_number` is reliable.

I agree about using the `Court` timezone to present these datetimes to users (including the docket alert), is the right thing to do.

**In another hand, I think we could handle this issue from a different perspective.** 

What if instead of storing `date_filed` in a `datetime` field, we continue using just the date field and do a `datetime` conversion before storing the date?  If we're going to do the conversion before presenting the data to users (using the Court timezone), wouldn't be better to do that conversion before storing the `date`? For instance, if we scrape an RSS feed from a court in New York (since we know the timezone for each court) we could convert the UTC `datetime` to `EST` and store that `date` in DB. 

In that way, we'll have the correct dates for the `date_filed` field and we could avoid having other issues changing the field in DB, especially related to the API. 

What do you think?

**Comment by mlissner** [comment]
Closing as a dup of #1282. More comments there in a sec.
