### ISSUE TITLE
cl_find_citations changed the content of citations

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1796]
It's unclear how widespread this problem is but a user identified that 

cl_find_citations - method that generates html_with_citations content converted 

(47 O.S. 1991, § 11-903)
to
(47 Ohio St. 1991, § 11-903) 

The first is a citation for a Oklahoma Statutes, the latter is an Ohio Court citation.  At some point this fixed it self but we need to re-run cl_find_citations on the incorrect files to fix the html_with_citaitons.  

This leaves us with a couple questions as to how this occurred, and how many other cases are affected.

**Comment by mlissner** [comment]
We should verify if this is an ongoing problem and if it's fixed by re-running the citation code. If so, let's re-run the citation finder.

**Comment by flooie** [comment]
Well the good news ... is that `cl_find_citaitons` doesn't appear to mess around with the Oklahoma Statutes citations anymore.  But the eye cite still identifies Oklahoma statutes as Ohio State Citations. 

But... I think we need to delete and reprocess all the Oklahoma opinions html-with-citations and reprocess them all.

**Comment by mlissner** [comment]
Thanks for checking. If you want to give that a go via a Python terminal, go for it. Otherwise, we'll get to it eventually. No need to delete the content though, it'll just get updated when the citation finder is run. We could do that now or just let it happen naturally when we're ready to do so. I imagine there have been a LOT of changes to eyecite and the reporters-db that warrant a re-run of the citation finder across everything. 

We could do that now, or it might be wise to wait until more fixes land in reporters-db.

**Comment by flooie** [comment]
That makes sense to me @mlissner

**Comment by mlissner** [comment]
We'll get this fixed just by re-running things. Good.
