### ISSUE TITLE
@recap.email addresses need to be lowercased

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1923]
In https://github.com/freelawproject/courtlistener/issues/1805, we developed our approach to generating recap.email email addresses, but we forgot one thing: Lower-casing the email addresses. Already our first user is complaining.

Sooooo...:

 - we need to update the function that does this so that everything is lower cased
 - we need to lowercase everything in the DB.
 - If there are collisions, we need to just handle that

Should be fairly straightforward.

**Comment by albertisfu** [comment]
Great, working on it, just a couple of questions:

- currently, all of your existing users  have a recap.email address assigned?  or are only new users going to have a recap.email address?

I found the signal: `generate_recap_email` but seems it only triggers when a user is created through `assign_recap_email ` signal

- so I would like to know which method are you using to assign a recap.email address for existing users in order to use the same approach to lowercase those existing addresses

**Comment by mlissner** [comment]
All have usernames assigned. I just did it via commandline a few weeks ago. I guess the fix here is to fix the generation function for future folks, and to re-run it for existing ones.

**Comment by mlissner** [comment]
OK, this is re-run for existing folks, so they should all now be lowercased. Woo!
