### ISSUE TITLE
@recap.email: Ignore emails from the courts that aren't notifications

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1934]
Now that we're in testing, we're getting some emails that aren't actually case-related notifications. For example, one court just sent this:

> In accordance with Volume 3, Chapter 4, § 420.30 of Judicial Conference Regulations, the United States District Court for the District of Colorado is accepting submissions from qualified professionals interested in serving on the court's merit selection panel.  
> 
> [...]
> 
> Interested persons should email a resume and letter of interest to xxx@cod.uscourts.gov no later than Friday, March 11th, at 5:00 pm MST.

I think we should just ignore these for now. We're a secondary recipient, so the user will be getting the email too. It might make sense to eventually forward the message or the text of it or something, but for now the simple thing is to ignore it.

**Comment by mlissner** [comment]
I guess this is basically done in freelawproject/awscloud#9, right?

**Comment by albertisfu** [comment]
Yeah, the email described above seems to be an update email sent by a court through [uscourts@updates.uscourts.gov](mailto:uscourts@updates.uscourts.gov) this kind of email is now being ignored since they are from a not-valid PACER court ID `updates`.

There are other similar emails that come from a valid PACER court ID (ncwd_ecf@ncwd.uscourts.gov) so they are being processed:
![Screen Shot 2022-12-19 at 15 40 45](https://user-images.githubusercontent.com/486004/208529440-4550f23a-ba32-4a94-8483-2474de301f88.png)

So in order to ignore them I added in https://github.com/freelawproject/juriscraper/pull/597/ the following string to `NotificationEmail` `ERROR_STRINGS`:
`This is an announcement e-mail message generated by Court action through the CM/ECF system`

So once that is merged we'll also ignore these announcement emails.

**Comment by mlissner** [comment]
I think we're done here, right?

**Comment by albertisfu** [comment]
Yeah, this is done!
