### ISSUE TITLE
Defining a reliable SES sending email architecture for recap.email

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#1942]
In order to properly handle recap.email notifications we should take some considerations to avoid affecting recap.email reputation sender and offer a reliable service for recap.emails users.

We are going to hear SES notifications for bounced emails, complaints and delivery.

Depending on each type of notification, the proposal is to take the following actions:

| Soft/Hard | Category                 | Action                                                                                                                      |
|-----------|--------------------------|-----------------------------------------------------------------------------------------------------------------------------|
| Unclear   | Undetermined             | Exponential backoff                                                                                                         |
| Hard      | General                  | Stop sending, put banner notice in account                                                                                  |
| Hard      | NoEmail                  | Stop sending, put banner notice in account                                                                                  |
| Hard      | Suppressed               | Probably won’t get these (we’re not using the suppression list feature, but if we do, log a warning for admins to evaluate) |
| Hard      | OnAccountSuppressionList | Probably won’t get these (we’re not using the suppression list feature, but if we do, log a warning for admins to evaluate) |
| Soft      | General                  | Exponential backoff                                                                                                         |
| Soft      | MailboxFull              | Exponential backoff                                                                                                         |
| Soft      | MessageTooLarge          | Resend email, set account to not get attachments                                                                            |
| Soft      | ContentRejected          | Probably won’t get these, just log a warning and decide what to do later.                                                   |
| Soft      | AttachmentRejected       | Probably won’t get these, just log a warning and decide what to do later.                                                   |
| n/a       | Complaints               | Stop sending, mark the user account or something                                                                            |

We also have to take into account how to handle exponential backoff and failed emails when a user's email server goes down, a proposal for this is in the following events timeline:

- 8am; Your server goes down.
- 9am: CL sends an email.
- 10am: CL sends an email at 10am.
- 11am: CL gets bounce notifications for 9am email and 10am email
  - CL starts doing exponential backoff with two hour delay (no more emails until 1pm)
- 11:30am: CL gets a notification, but does not send an email, due to exponential backoff.
- 12am: Your server comes back.
- 12:30am: CL get another notification, no email goes out due to exponential backoff
- 1:05pm: CL gets another notification, sends it! 
- 1:06pm: CL gets delivery notification for 1:05pm email.
 - TRIGGER!
   - Send email failure report explaining that their server was down and that we'll be resending the emails.
   - Slowly resend bounced or emails skipped due to exponential backoff.

We're going to use delivery notifications to detect when the user's email server comes back, to retry send all failed and skipped emails, these emails are going to be sent distributed during a defined period of time that could be equal to the time user's email server was down or just define a fixed time interval for example next 24 hours or 1 email per second.

As the next step, I'm going to start working on defining this architecture and figuring out if there is something more that we should care about.

**Comment by johnhawkinson** [comment]
> We also have to take into account how to handle exponential backoff and failed emails when a user's email server goes down

I think it's important to think about these proposals realistically, because otherwise we'll probably make improper inferences and draw erroneous conclusions:

>  a proposal for this is in the following events timeline:
> 
>     * 8am; Your server goes down.
> 
>     * 9am: CL sends an email.
> 
>     * 10am: CL sends an email at 10am.
> 
>     * 11am: CL gets bounce notifications for 9am email and 10am email

That's not how it works. In that fact pattern, SES would periodically retry to send the email for, my memory says, _up to four days_. If the server comes back up in a few hours, SES won't tell you and if even if it does you shouldn't change your behavior.

Now, if the email server is _misconfigured_ and starts bouncing mail when it should be accepting it or deferring it, that's a different story. That's the kind of thing that's not supposed to happen, but sometimes does, like e.g. a disk fails and the server reboots and comes back up and accept connections but then dumps mail on the floor. I'm not sure if this the kind of scenario you are considering?

Also, looking at your chart:

> Soft 	General 	Exponential backoff
> Soft 	MailboxFull 	Exponential backoff
> Soft 	MessageTooLarge 	Resend email, set account to not get attachments
> Soft 	ContentRejected 	Probably won’t get these, just log a warning and decide what to do later.
> Soft 	AttachmentRejected 	Probably won’t get these, just log a warning and decide what to do later.=

Why would we do anything for the soft failures? Don't they mean SES is going to handle the resending?
Am I paying too little attention here and do I need to read more closely?

**Comment by mlissner** [comment]
> Why would we do anything for the soft failures? Don't they mean SES is going to handle the resending?

The way SES handles it is that it retries a bunch during soft failures, and then gives up and sends us a soft bounce notification. So when we start getting soft bounces, we move into exponential backoff mode until we figure out that the server is back. When it is (because an email got delivered), we resend anything that soft-bounced.

> That's not how it works. In that fact pattern, SES would periodically retry to send the email for, my memory says, up to four days.

Yeah, the timeline is compressed in the example, but the approach holds. The general idea is that we slow down on sending emails as long as we're getting bounces and we keep track of emails that never got delivered. Once the bounces stop, we slowly resend the bounced emails so that they at least all go through. 

I'd like to also include something in those re-sent emails that says, e.g.:

> This email originally sent at XYZ time, but your email server bounced due to your [full mailbox, unknown error, etc]. We are resending it now to ensure you get all your essential notifications.

**Comment by mlissner** [comment]
I think we've got this figured out and no further discussion is happening here, but we can reopen it if we have further things to say.
