### ISSUE TITLE
Develop parenthetical search feature

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1955]
This issue serves as the high-level spec and discussion space for a new search UI for parentheticals. There are two high-level features to focus on here:

1. Adding parentheticals to our current [opinion search][ops] so that when you place a search:
    - Relevancy gets boosted if it matches a summary of an opinion
    - Opinion results *appear* if your search tokens only appear in the summary (but not in the opinion itself)
2. A stand-alone parenthetical search interface (this is akin to the ["holdings" search][ct] that Casetext provides).

## Adding to our existing search interface

This should be done as part of our move to Elastic search. This shouldn't be too hard:

1. For every parenthetical group there is a representative opinion. Add these as a list to the opinion when it is indexed.
2. Add a new fielded query parameter for searching these. Off the cuff this could be `parenthetical:` (see [here][adv] for examples).
3. Possibly: Add a new input box on the front end for searching just parentheticals.
4. Add a boost for hits that occur on parentheticals.
5. Show the top-scoring representative parenthetical in the results set (I'm not sure how to do this without pulling it from the DB at query time [that might not be terrible]).

## The new stand-alone parenthetical search

The idea here is that sometimes just searching the summaries is all you need to do! To implement this, we need to:

1. Create a new search index in Elastic and add everything in the parentheticals table to it, including their group ID and various other relevant bits of metadata that people might want to search on (more on this below).
2. In the CL navbar, add a new item to the opinions drop down for "Parentheticals Search" and rename the existing one as "Opinions Search"
3. Make a new homepage for parentheticals search, similar to the ones we have for RECAP, Opinions, Judges, etc.
4. In the front end, use Elastic grouping (or similar technology) to group search results, similar to how we do docket grouping. This will result in parentheticals that are grouped semantically in the front end. So imagine something like this:

    ![Screenshot from 2022-03-09 11-23-55](https://user-images.githubusercontent.com/236970/157524415-e0584f7a-ef67-4372-8afc-2a93e9304805.png)

    That's from the docket search, but the idea is the same. Instead of grouping documents into dockets as above, we group parentheticals into groups and show the top five or so. The advantage of doing this is that we provide semantic results per case instead of providing 1,000 flat results that all summarize the same case. 

### Search facets for parentheticals (with join paths):

2. Opinion -> OpinionCluster.precedential_status
3. Opinion -> OpinionCluster.date_filed
4. Opinion -> OpinionCluster -> Docket.court
6. It's worth indexing Opinion.extracted_by_ocr for our own purposes and not showing it to users.

### Solr/Elastic stored fields

Solr (and I believe Elastic) has the concept of unsearchable fields that are just stored. Because of the flattening of the DB that we're doing to put this content into Elastic, I don't think we should do this. For example, we could put the Docket.case_name field into Elastic, but if we do, it will get massively duplicated. Since nobody wants to search it, we can just pull it from postgresql when folks make queries in search and merge the postgres data with the solr data in our application code.

# Comments

Bring 'em! 

[ops]: https://www.courtlistener.com/opinion/
[ct]: https://casetext.com/search?q=ineffective%20assistance%20claim&p=1&tab=keyword&jxs=&sort=relevance&type=holding
[adv]: https://www.courtlistener.com/help/search-operators/#fielded-queries-fieldname-term

**Comment by albertisfu** [comment]
@mlissner, while working on this, some questions arose. I would appreciate your opinion on which search approach would be more helpful for users.

For context these are the parenthetical models:
```
class Parenthetical(models.Model):
    describing_opinion
    described_opinion
    group
    text
    score


class ParentheticalGroup(models.Model):
    opinion
    representative (opinion)
    score
    size
```

**The current search approach is as follows:**

- Look for `Parentheticals` objects in which the query matches the `text` field and add additional filters based on:
    - `date`, using the `Parenthetical.described_opinion.date_filed` field
    - `court_id`, using the `Parenthetical.described_opinion.docket.court` field
    - `docket_number`, using the `Parenthetical.described_opinion.cluster.docket.docket_number` field
    - and the new one, `precedential_status`, using the `Parenthetical.described_opinion.cluster.precedential_status` field

Results are aggregated by `group_id` and shows the group with the top five parentheticals (by score). Instead of showing single parentheticals, groups of parentheticals that include the matched parentheticals in the search are shown.

However, after enabling grouped results, I noticed that the search order field, which includes the following options: Relevance (score), Newest cases first, and Oldest cases first, is not working properly.

This is an order for aggregated results that need to be set differently than single results. Therefore, some questions arise:

How should we order groups of parentheticals? Each group of results can contain one or multiple parentheticals, for example, "Relevance (score)." Which score should we choose to order the group across other groups? Should we choose the higher score within the parentheticals in the group matched by the search or the group representative parenthetical score?

For the newest cases first and oldest cases first, I checked some examples and noticed that for every parenthetical that belongs to a group, their described opinion is the same, including the group representative parenthetical. Therefore, I think it would be okay if we just select the group representative parenthetical's described opinion date filed to set this order.

**The second approach that came to my mind thinking about this is that we could look for `ParentheticalGroup` directly instead of searching for single Parentheticals.**

To implement this approach, we can create an index that looks for the query within the representative `Parenthetical` of a `ParentheticalGroup`. For example, the query will look for `ParentheticalGroups` where the query text matches the `ParentheticalGroup` representative `Parenthetical` text. Other filters like `date_filed`, `court_id`, `docket_number`, and `precedential_status` can be applied directly to the ParentheticalGroup.opinion.

The results will return `ParentheticalGroups` instead of `Parentheticals` (as in the previous approach). We could then show every group matched by the search with their top five parentheticals (which may not be directly related to the search).

**In a brief, should we either?**

- Look for single `Parentheticals` that fit a search and then group the results by `ParentheticalGroup` (Current approach). If following this approach is it ok to short groups, by the group opinion (filters), and representative Parenthetical (text query relevance)?

- Look for `ParentheticalGroups`, using the linked opinion and representative parenthetical to look for search coincidences and order. Then show `ParentheticalGroups` as results alongside their top 5 Parentheticals.

**Comment by mlissner** [comment]
## Groups vs Members?

Good questions. Yes, I think it's a good idea to make this a search for `ParentheticalGroup`s instead of parentheticals. The idea of the groups is that lots of opinions will summarize an opinion in nearly identical ways, so you wind up with dozens or hundreds of references to an opinion that are almost all the same. You can see that in action here:

https://www.courtlistener.com/opinion/108713/roe-v-wade/summaries/

![image](https://user-images.githubusercontent.com/236970/227963995-c4e0fae5-fa59-413e-8a47-bb056496cfa0.png)

So yeah, it makes sense not to include those dozens or hundreds of redundant results in the search engine and to instead just use the group. 

## Sorting?

For sorting, I think this is easy to change in the future if we just do the following:

 - If sorted by relevancy, we group by described opinion, and show the top five results (as ranked by ElasticSearch) as a nested group under the decision. Let's just use word matching relevancy at first, and if it's better, let's switch to ordering the group members that match a query by their group score. 

 - If sorted by date, order the grouped search results by date, and then order the group search result members by relevancy (again, we can order by group score later, if it seems better).


## Filtering?

Your description of this sounds good to me, but, I was wrong about:

> the new one, precedential_status

I just realized this isn't necessary, actually. Sorry. Normally it would be needed when searching opinions, but precedential status refers to whether an opinion should be cited or whether it's not worth citing at all. 

Since parentheticals are all examples of something that IS cited, we can just assume it's all precedential and not bother with this.

## Fin?

I think that's it, but let me know if you still have questions!

**Comment by albertisfu** [comment]
@mlissner  Thanks for the explanation, yeah based on the nature of parentheticals it makes sense to show results based on `ParentheticalGroup` instead of `Parenthetical`, I'll change this behavior.

Just a couple of more questions about:

> If sorted by relevancy, **we group by described opinion**, and show the top five results (as ranked by ElasticSearch) as a nested group under the decision. Let's just use word matching relevancy at first, and if it's better, let's switch to ordering the group members that match a query by their group score.

_we group by described opinion_:  Are you referring to the `ParentheticalGroups` that are already made, in your example the described opinion is [Roe v. Wade](https://www.courtlistener.com/admin/search/opinion/108713/change/) right? 

For example considering the following query and results:
Query: `terminate a pregnancy`
Search results:

- Recognizing that the constitutional right of privacy includes a woman's right to terminate a pregnancy absent an overriding state interest
  - Holding that right of privacy in matters concerning procreation and family "is broad enough to encompass a woman's decision whether or not to terminate her pregnancy”
  - Recognizing a woman's qualified right to terminate her pregnancy included in a substantive due process right to privacy
  - Identifying specific right to terminate a pregnancy from broader right to privacy
  - Woman's right to decide whether to have abortion
  - Right of privacy protects a woman's decision regarding termination of pregnancy

- Denying the contention “that the woman’s right is absolute and that she is entitled to terminate her pregnancy at whatever time, in whatever way, and for whatever reason she alone chooses”
  - Denying the contention “that the woman’s right is absolute and that she is entitled to terminate her pregnancy at whatever time, in whatever way, and for whatever reason she alone chooses”

- Stating that at the founding and throughout the 19th century, "a woman enjoyed a substantially broader right to terminate a pregnancy”

The first level bullets are the `ParentheticalGroup` objects where their `representative` opinion text matches the query so that if shorted by Relevance these groups are shorted by ElasticSearch according to the query, right?

Then you mentioned:
_and show the top five results (as ranked by ElasticSearch) as a nested group under the decision._

These are the second-level bullets, right? I have a couple of questions here:
- Does that means we should add to the `ParentheticalGroup` index all the `Parenthetical` texts that belong to a group, so we can show the top 5 `Parenthetical` of the group shorted by ElasticSearch relevancy? 

- Or create an index of `ParentheticalGroup` and an additional index of `Parenthetical` so that when a search is made it looks for the `ParentheticalGroup` and internally an additional query over each `ParentheticalGroup` so it can retrieve the best `Parenthetical` objects (top five) that belong the group?

**Comment by mlissner** [comment]
So, we have:

 - Decisions, which are described by:
     - ParetheticalGroups, which contain:
         - Representative Parenthetical
         - Opinion

The idea of the search results is to search the most important parentheticals. This means that:

 - We don't need to search the text of the decisions
 - We only need the text of the representative parenthetical from each group.

So when somebody searches, they'll do a full text search of the text of the representative parentheticals, and they'll get results like:

> 1. Roe v. Wade (court, date, etc)
>       - ParentheticalGroup1 that matched on `ParentheticalGroup.representative.text`
>       - ParentheticalGroup2 that matched on `ParentheticalGroup.representative.text`
>       - ParentheticalGroup3 that matched on `ParentheticalGroup.representative.text`
>       - ParentheticalGroup4 that matched on `ParentheticalGroup.representative.text`
>       - ParentheticalGroup5 that matched on `ParentheticalGroup.representative.text`
> 
> 1. Mike v. Walmart (court, date, etc)
>       - ParentheticalGroup1 that matched on `ParentheticalGroup.representative.text`
>       - ParentheticalGroup2 that matched on `ParentheticalGroup.representative.text`
>       - ParentheticalGroup3 that matched on `ParentheticalGroup.representative.text`
>       - ParentheticalGroup4 that matched on `ParentheticalGroup.representative.text`
>       - ParentheticalGroup5 that matched on `ParentheticalGroup.representative.text`

That shows the results grouped by described opinion, and the nested items are one-per group.

If I remember how Solr works (and if Elastic works the same way), you can set the top-level results to be ordered by one thing and then set the nested results to ordered by another.

I hope that clarifies.

Your questions:

> Does that means we should add to the ParentheticalGroup index all the Parenthetical texts that belong to a group, so we can show the top 5 Parenthetical of the group shorted by ElasticSearch relevancy?

No. We don't need all the parentheticals, because if you look at them, they're usually very similar. These three are a good example of why showing more than one isn't very useful (this is why they're collapsed in the webpage I linked in my last comment):

![image](https://user-images.githubusercontent.com/236970/228082289-62bc8f4b-e9e6-4bfd-9f6a-51ce7d6d9bc4.png)

> Or create an index of ParentheticalGroup and an additional index of Parenthetical so that when a search is made it looks for the ParentheticalGroup and internally an additional query over each ParentheticalGroup so it can retrieve the best Parenthetical objects (top five) that belong the group?

I think my explanation above should moot this question, but if this isn't clicking for you, let's just talk. :)

**Comment by albertisfu** [comment]
Thank you, the examples were very helpful, so yes we'll index `ParentheticalGroup` and then group the results by their described opinion.

- Just to confirm, thinking of the following case, if a user searches for a query that matches multiple groups by their representative text within a Decision, we'll show up to 5 nested results:

e.g:
Query: `very common words`
- Roe v. Wade (court, date, etc)
  - ParentheticalGroup1 that matched on ParentheticalGroup.representative.text
  - ParentheticalGroup2 that matched on ParentheticalGroup.representative.text
  - ParentheticalGroup3 that matched on ParentheticalGroup.representative.text
  - ParentheticalGroup4 that matched on ParentheticalGroup.representative.text
  - ParentheticalGroup5 that matched on ParentheticalGroup.representative.text

... 
(might exists more decisions and their ParentheticalGroup)

Because many ParentheticalGroup.representative.text matches the keywords.


- But in case someone searches different keywords that only match one ParentheticalGroup, the decision will only contain one ParentheticalGroup that matches the query:

e.g:
Query: `very uncommon words`

- Roe v. Wade (court, date, etc)
  - ParentheticalGroup1 that matched on ParentheticalGroup.representative.text
 
... 
(might exists more decisions and their ParentheticalGroup)


Is that correct?

**Comment by mlissner** [comment]
Yep, that's exactly it.

**Comment by albertisfu** [comment]
@mlissner Continue working on this I found an additional question:

In Elasticsearch, for normal grouping, you need to set the size when doing an aggregation. This size is the maximum number of groups that can be returned. Years ago, it was possible to set `size:0` to retrieve all possible groups, but they [removed this setting](https://github.com/elastic/elasticsearch/issues/18838) to make the user aware that retrieving a big number of groups can be an expensive operation.

So we have two options: set this size to a high value, for example, `1,000,000`. If a query generates more than `1,000,000 `groups, returned results will be limited by this number, but we’ll be able to show the total number of groups and the total number of parenthetical groups. Also, we can display the total number of pages (even though users are only allowed to browse up to 100 pages). However, returning a big number of groups can be expensive.

Concept of results using this approach:
![Screenshot 2023-03-30 at 10 03 48](https://user-images.githubusercontent.com/486004/228898946-4af7f34c-bbb1-42af-9ea2-fe383bad4b72.png)


The other option is to use a different type of aggregation called composite aggregation. We can create groups in pieces, giving a parameter that is used to indicate where the next grouping should start. We can create groups as needed. The problem with this approach is that we can’t get the total number of possible groups since it only returns a set of groups at a time. But we can display the total number of parenthetical groups related to the query.

The other problem with this approach is that it is not possible to show the total number of pages, since the total number of groups is unknown. So pagination will only include something like "Previous" and "Next" page, showing only the current page.

Concept of results using this approach:
![Screenshot 2023-03-30 at 10 02 44](https://user-images.githubusercontent.com/486004/228898988-0a54c311-e8da-4668-8c80-f1c3c8c5e042.png)


Which approach do you think is better considering these upsides and downsides?

**Comment by albertisfu** [comment]
> One more question I had though, Alberto: Does the second option allow you to do really deep pagination without performance problems? If so, we might want to go that way anyway. It'd be nice to remove the 100 page limitation, because we pretty frequently get people that want to export search results. We've never built that feature though because we know it would never perform well enough with the way Solr works. If Elastic fixes that by allowing deep pagination, that might be a good reason to go with option two.

Yeah, at least for grouped results, the most efficient way to do pagination is to use [composite aggregation pagination](https://www.elastic.co/guide/en/elasticsearch/reference/8.7/search-aggregations-bucket-composite-aggregation.html#_pagination). This way, each group of results is returned in a small request instead of a big one.

The problem, as described above, is that the total number of results and pages is unknown.

**Comment by mlissner** [comment]
Interesting. Well, let's see how it goes doing the simple way for now, but I have a feeling we'll be moving to the hard way soon (or maybe just for RECAP).

**Comment by mlissner** [comment]
This is now deploying. Thank you everybody for so much hard work on this one! We don't have the ES server(s) set up yet, so it won't work, and it's behind a waffle. Once the server is set up, the content is indexed, and it's working nicely, we'll loosen the waffle.
