### ISSUE TITLE
Urgent: New PACER email handler is purchasing documents

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1974]
Let's get this fixed as soon as possible. With every passing moment we get emails for our beta users and that's costing us money.

It's not bad, but it's not great!

**Comment by albertisfu** [comment]
Temporarily disabled send_to_court_listener function here: https://github.com/freelawproject/awscloud/pull/5 

Working in a full solution using `magic_number`

**Comment by albertisfu** [comment]
When retrieving PACER documents from RECAP Email we have to take into consideration:

- We should retrieve without logging in.
- We should make sure that if there's a non-zero price tag on the receipt page, we don't make the purchase.

The reasons we might get non-free downloads are:
- The magic number has been used already (by us, most likely)
- Not all NEFs get magic numbers (some, like those for reporters, are not free)

Some additional notes:
- NEFS are for district courts. NDAs are for appellate courts.
- The magic numbers differ per email address, so using a @recap.email magic number shouldn't impact the magic numbers of our users.

**Comment by albertisfu** [comment]
Some more questions about this issue @mlissner :

- For documents coming from RECAP Email, we are not going to Log in to download the document, from my understanding in case we try to download a non-free document (because the magic number has been used or the document is not free even if it has a magic number), since we aren't going to be logged in, we'll land in a PACER login page and we'll abort that download, Is it still possible to view a receipt page in this flow without being logged in?

- Or the confirmation to check if there's a non-zero price tag on the receipt page, is for other use cases (no RECAP email), I saw CL also retrieve `FreeOpinionReports` from courts where it's necessary to log in, here is where we need to look for the non-zero price tag? 

- Is there an exception in CL where we are allowed to retrieve paid documents?

**Comment by albertisfu** [comment]
Ok great, so I'm going to ensure that we only try to download documents from emails with a magic number without being logged in, if we land on a login page just ignore that download.

Thanks!
