### ISSUE TITLE
Analyze nginx configuration before moving to AWS

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1982]
In another issue, I wrote about how we need to analyze the nginx configuration. Details below...

-----

There's a separate nginx image that we maintain that is an optimized nginx installation. It has a config file [here](https://github.com/freelawproject/courtlistener/blob/c7a1eb544cabbc86ec50779a9c6a4e8e0de08737/docker/nginx/nginx.conf). The particularly important settings I see in there are:

We need this because we get big uploads from users:

```
    # This is the max upload size, default is 1M.
    client_max_body_size 256M;
```

Our SSL is highly optimized for security (we get [an A+ rating](https://www.ssllabs.com/ssltest/analyze.html?d=www.courtlistener.com&hideResults=on):
```
    # Diffie-Hellman parameter for DHE ciphersuites. Downloaded from Mozilla
    # configurator (according to their instructions).
    ssl_dhparam          /etc/nginx/includes/dhparam2048.pem;

    # Mozilla Intermediate configuration
    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_ciphers          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

    # OCSP Stapling
    ssl_stapling         on;
    ssl_stapling_verify  on;
    resolver             1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220 valid=60s;
    resolver_timeout     2s
```

And:

```
# security headers
add_header Referrer-Policy         "same-origin" always;
add_header X-XSS-Protection        "1; mode=block" always;
add_header X-Content-Type-Options  "nosniff" always;

# HSTS
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
```

----

There's also a "sites-enabled" [configuration file](https://github.com/freelawproject/courtlistener/blob/e8afee31435016eecbe9e94c57023465f81d2b43/docker/nginx/sites-available/courtlistener.com.conf) for CourtListener.com. It's worth going through it and making sure we still support what's in there, if necessary. I made an annotated version of it here, with some notes on which features are important:

https://gist.github.com/mlissner/cbd98a2baf87532c5d713e124fbfaee9

_Originally posted by @mlissner in https://github.com/freelawproject/courtlistener/issues/1979#issuecomment-1077967980_

**Comment by kalki-e-datamatics** [comment]
Regarding Big Uploads from users,
* AWS Application Load Balancer (ALB) does not have any restriction on the size of request body, i.e., no max upload size restriction. So the following nginx configuration can be safely omitted.
```
    # This is the max upload size, default is 1M.
    client_max_body_size 256M;
```

Regarding Additional headers
* AWS ALB does not have an option to add the additional headers to the HTTP response. So if we are going with ALB, the only option is add these headers directly in the Django application (may be with [Django middlewares](https://docs.djangoproject.com/en/4.0/topics/http/middleware/))
* If the above wouldn't work, then we have to stick with Nginx and use Network Load Balancer (NLB) from AWS. The NLB can have a TCP listener on port 80 & 443 and they would be forwarding the TCP packets to port 80 & 443 of Nginx respectively. Nginx can set the additional headers as it is doing already.

Regarding SSL security
* AWS ALB has a [list of security policies](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies) from which one can be chosen.
* `ELBSecurityPolicy-2016-08` is the default one which gets B rating on SSL labs test due to its support for TLS v1.0. It is kept as default so that they are compatible with very old browsers.
* So we could get better SSL rating by choosing the right Security Policy from the list. But if you want exact control of what versions and ciphers to support, ALB could be limiting there.
* Also, the OCSP Stapling is not supported by ALB and we might have to stick with Nginx if that's mandatory.*
* Another option is we can have a cloud front distribution (which supports OCSP) in front of the ALB.

Few features of Nginx like
* Compression is not supported by ALB but [Cloud Front supports it](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html).
* Equivalent of Rewrite and Location directives are not there in ALB but with Cloud Front, it can be done.

**Comment by mlissner** [comment]
OK, headers and the favicon stuff are done.

**Comment by mlissner** [comment]
All static files are yanked from our codebase and served via S3 now.
