### ISSUE TITLE
Improve Suffix Handling (specifically with disclosures)

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2068]
Link backs from disclosure page to the Judge/Person page does not title Suffix's properly. 

See [william-lynn-campbell-jr](https://www.courtlistener.com/person/8560/disclosure/30211/william-lynn-campbell-jr)

Also - @mlissner I don't know your feeling on when III is changed to 3 for a judge, but it irks me.

**Comment by flooie** [comment]
An example of the `III` -> `3` 

[See Joel McElroy Carson 3](https://www.courtlistener.com/person/8561/disclosure/30596/joel-mcelroy-carson-iii/)

**Comment by mlissner** [comment]
I guess it's be around the fifth when I'd expect 5th instead of V? But I
have no idea.

**Comment by flooie** [comment]
I think in modern times you never switch away from Roman numerals.  But thats just my understanding.

**Comment by quinnr** [comment]
This is an interesting conversation, I presumed that you'd use Roman Numerals all the way down. I searched for examples in state and federal court style guides and they all seem to stop at "III" for their examples and just remain silent on anything past that. I don't think I've actually come across anything past "III" in my work either. 

I'm reminded of [Falsehoods Programmers Believe About Names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) by Patrick McKenzie. I suppose a birth certificate could list it either way, right?

**Comment by mlissner** [comment]
I'm roundly and passionately informed I'm wrong about this. Roman numerals all the way, apparently.

**Comment by flooie** [comment]
Five years!!  @quinnr cool article.

**Comment by flooie** [comment]
Note: 
This is going to take an update to all suffixes currently in the system.  
A non-migration to update the choices.
And I think we should expand suffixes from I to X

**Comment by mlissner** [comment]
So, the suffix list is:

```
SUFFIXES = (
    ("jr", "Jr."),
    ("sr", "Sr."),
    ("1", "I"),
    ("2", "II"),
    ("3", "III"),
    ("4", "IV"),
)
```

So I think it's actually working more or less fine? If you look at your example, their name is displayed properly on their profile page:

https://www.courtlistener.com/person/8561/joel-mcelroy-carson-iii/

The problem is that the disclosure page uses the `name_suffix` field instead of the calling `get_name_suffix_display`, which would return `III` instead of `3`, for example. 

So I think if we tweak the line here:

https://github.com/freelawproject/courtlistener/blob/8efb71159533671633a4e068307718b3bb25e601/cl/people_db/templates/financial_disclosures_viewer.html#L30

So it says:

```
{{ person.get_name_suffix_display }}
```

That should fix it? 

Or, wait, we can do even better. The whole line above can be changed to:

```
{{ person.name_full }}
```


Which runs:

```
    @property
    def name_full(self):
        return " ".join(
            [
                v
                for v in [
                    self.name_first,
                    self.name_middle,
                    self.name_last,
                    self.get_name_suffix_display(),
                ]
                if v
            ]
        ).strip()
```

**Comment by flooie** [comment]
Okay, yes you made that much cleaner and nicer but ... I do have one last nit to pick.

but ill put it in my PR.
