### ISSUE TITLE
Write webhooks documentation

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2176]
We need to create a new page for webhooks documentation, my proposal about what it should contain:

- Introduction: explaining what webhooks are, how it works, and how can it help.
- Webhooks interface: explaining how to create a webhook, delete or edit it. How to consult logs.
- WebhookEvent object: describing WebhookEvent properties and their payload structure for each type of event.
- Setting up a webhook: General recommendations for users about how to set up a webhook listener on their applications.
- Testing?: This is a proposal, I saw that many services offer a way to test that users can listen properly to a webhook on their application, it could be something simple as allowing users to trigger an example webhook request for each event type.

More ideas are welcomed.

**Comment by mlissner** [comment]
A few more:
 - The idempotency key
 - The retry policy (this can probably be vague, without getting into details, #2207 has some notional language)

**Comment by mlissner** [comment]
- When is a webhook disabled?

**Comment by anseljh** [comment]
## Main questions

There's some overlap in these, but here are questions I had while playing with this so far:

- [ ] What are the criteria for triggering each Event Type?
- [ ] What is the difference between the "Recap Fetch" and "Docket Alert" Event Types?
- [ ] If a document is downloaded on a docket entry that's already in RECAP, is anything triggered? The answer seemed to be no when I tried this with one of my cases. Is that expected behavior? This might be important for the updated Big Cases Bot since many people look at those cases.

## Testing

I love the `curl` code in the test dialog!

- [ ] The formatting is a little off, specifically the indent of the first line:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/2075772/202118078-c044458a-9ef7-48d0-9a13-0de55ecc3021.png">
 
- [ ] I'd love an [HTTPie](https://httpie.io/docs/cli) version, but that's purely extra credit.

## Sample app

- [ ] It would be great to provide a simple sample app. Perhaps a bare-minimum webhook receiver in [Flask](https://flask.palletsprojects.com/en/2.2.x/). Here's what I have so far:

```python
from flask import Flask, request, Response

app = Flask(__name__)


@app.route("/webhook", methods=["POST"])
def respond():
    print(request.json)
    return Response(status=200)
```

**Comment by mlissner** [comment]
I just looked over these and compared them to the draft documentation we've got. I think it checks pretty much all the boxes here. 

https://docs.google.com/document/d/1vXPmiTORtvZzOrq1z4mq03cQw_WWALrjub0egQcfXWI/edit#

**Comment by mlissner** [comment]
@alberto, sorry, one other thing, can you please: 

 - [ ] Move the current API documentation from /api/rest-info/ to /help/api/rest/
 - [ ] Move obsolete API documentation from /api/rest-info/vX to /help/api/rest/vX/
 - [ ] Set up redirects from the old locations to the new
 - [ ] Update /help/ to have links to webhooks (/help/api/webhooks/), webhooks getting started (/help/api/webhooks/getting-started/), and API docs. Probably this can go in a new section, but I trust your judgement to get this right.

**Comment by albertisfu** [comment]
Of course, I'll add these changes.

**Comment by mlissner** [comment]
Last piece here is the search webhook documentation. Re-opening for that.
