### ISSUE TITLE
Docket attachments missing from court listener listing

### ISSUE THREAD

**Issue by hughbe** [freelawproject/courtlistener#2226]
Hi,

I'm following the case Aearo Technologies LLC and Aearo LLC (22-02890): https://www.courtlistener.com/docket/64431919/aearo-technologies-llc-and-aearo-llc/
<img width="932" alt="image" src="https://user-images.githubusercontent.com/1275900/182183933-db65673e-9d55-4333-b2bb-79b37581f3b1.png">

The docket entry 11 "Declaration" refers to "Exhibits", but no attachments/exhibits are displayed in courtlistener.

However, the PACER listing does show attachments: https://ecf.insb.uscourts.gov/doc1/072044680862?caseid=741797
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/1275900/182184051-17056160-c85e-4945-b723-ad4e2dda4cf1.png">

I'm surprised that there are no listings for the attachments on court listener

**Comment by mlissner** [comment]
We looked at this in a separate issue. I can dig it up for you if you want, but we only get the attachment pages if:

 - We download them explicitly; or 
 - Somebody sends them to us.

When neither of those things happen, we don't have the attachments. Downloading them explicitly requires a LOT of looking at PACER (imagine we get a docket with 100 entries, now we have to make 100 requests to PACER for attachment pages). So that's why we don't do it. But doing it for prioritized cases (whatever that means) seems to make sense to me...just hasn't happened yet.

**Comment by mlissner** [comment]
OK, yeah, here's the dup: https://github.com/freelawproject/courtlistener/issues/852. Feel free to chime in there, but I'm closing this one out. Still, thanks for filing it!
