### ISSUE TITLE
Add some spinners to webhooks UI

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2239]
Seems that htmx webhooks UI is laggy on production. 
So it would be good to add spinners when triggering actions and wait for a response.

**Comment by mlissner** [comment]
Alberto, I am going to use this bug as a test for somebody that we interviewing. So that they're not lost with it, I'm going to add a few more notes here so they understand what needs to happen. If you know of other bits of info that I should have mentioned, please feel free to chime in.

## Background

We are currently in the process of building webhooks into our back end so that users of our API can get events sent to a URL on their website whenever a particular item is updated in our database. This is much better than asking them to poll our API every minute for updates.

At present, we have a basic version of this working, which can be viewed by logged-in users here:

https://www.courtlistener.com/profile/webhooks/

Users can add, update, and delete webhooks. It's built using [HTMX](https://htmx.org/).

## The Problem

Alberto built out this page, and it's pretty good, particularly when you're on your local machine. Unfortunately, in production it's a bit too slow, making it feel laggy and hard to understand sometimes. It needs some kind of progress spinner so that users know when they've submitted their request properly.

## The solution

There are three buttons in the interface that I can think of:

 - Create Webhook
 - Edit
 - Delete

Each button should be modified to get grayed out and have a small spinner when the user clicks on it, until the request is successful. 

We usually use font-awesome for spinners.

Bonus: Sometimes requests time out. Can we handle that properly? This might not be worth the effort, but it's probably worth thinking about.

**Comment by albertisfu** [comment]
Yeah, the problem description is correct! 

I would just add that there is an additional request that might need the spinner. This is the webhooks-list request that it's not triggered by a button but by the load page event.

**Comment by mlissner** [comment]
I'm closing this one manually, but in the future, @ERosendo, if you can [auto-close your issues][gh], that's usually preferred. 

It usually just means putting something like this in your commit message on the second or third line:

> Fixes: #2239

If you put that, when the commit is merged, it closes the PR. (Sorry if you know all this already.)

[gh]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
