### ISSUE TITLE
@recap.email needs to get the attached items too

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2263]
This was an oversight that we noticed last week, but that we somehow didn't catch until then. From what I understand, the magic number lets you download the PDF and the attached items, so we need to figure out:

1. Are there attached items (can we get this info from the alert email?)
2. If so, how do we get them? 

And then:

3. Get them

And finally:

4. Send our email to the user listing all of the attachments that are part of the notification.

**Comment by albertisfu** [comment]
@mlissner  I've checked which the problem here is.

Right now when getting the free look document the attachment page is bypassed by `make_doc1_url` replacing the fourth digit with a 1 that download only the main document and we don't see the attachment page that can be seen without being logged into PACER.

Here is an example:

![Screen Shot 2022-08-16 at 17 28 57](https://user-images.githubusercontent.com/486004/184918878-eeb5ad79-dff8-47f5-be52-a5a0fd450312.png)


So, to solve it. We should check if there is multiple documents associated with the notice:
<img width="665" alt="Screen Shot 2022-08-16 at 17 15 44" src="https://user-images.githubusercontent.com/486004/184916156-343cd7ce-ef49-4f9f-a4e3-80f3e126f3bc.png">

If there is more than one, we should open the magic link (avoiding bypassing the attachment page), parse the attachments and get the `pacer_doc_id` for each attached document, return them to add to the docket entry.

Then, download the main document and every attachment if they exist replacing the `pacer_doc_id` into the magic link.

I'll first add this support for NEFs. Once we get back with NDAs support I think we also download attachments too (I haven't checked how it works for NDAs).

Does it makes sense to you? If so I'll be working on this.

**Comment by mlissner** [comment]
Sounds perfect. Please proceed!
