### ISSUE TITLE
@recap.email should handle NEFs that mention multiple dockets (relates to doppelganger issue)

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2270]
Working with attachments within PACER email notifications we found some emails that contain more than one docket entry (right now we only parse one docket entry for each notification) for different cases, e.g:

![Screen Shot 2022-08-16 at 23 24 45](https://user-images.githubusercontent.com/486004/185155352-98fdaac3-fd4d-4c49-80b6-9d323ae6ada3.png)

However the documents seems to be the same for both cases due to `pacer_doc_id` are the same.

We should get all the docket entries for recap.email and include them in the docket alert and webhook.

**Comment by johnhawkinson** [comment]
So, this is another situation where our data model does not properly reflect CMECF's.

This is not, strictly speaking, "more than one docket entry."  It is a single docket entry that has been "spread" to multiple cases. This typically occurs when there are related cases or consolidated cases or MDL cases or similar mechanisms where it makes sense for a single document to be filed in multiple cases. It gets a single document ID and can be retrieved from either case.'

(This results in cases where we have that document in CL but we only associate with one of the cases, and that means if someone looks at one of the other cases, it looks like we don't have the document, even though we do. A special case of this is doppelganger cases, where it is perhaps most frustrating, but it occurs elsewhere as well.)

As far as I am aware, only Court clerks can spread documents into mutliple cases, regular CMECF users cannot do so. (Although the example above suggests otherwise, so I'm not entirely sure what to make of that.)

**Comment by mlissner** [comment]
I agree with all that, thanks John. I think the one nice thing is that we can handle this a bit better in this case because we know all the cases it's a part of at a given time. The ideal thing would be to fix our data model, but short of that we can at least put a copy of the doc into multiple cases so they all have it.

**Comment by johnhawkinson** [comment]
> but short of that we can at least put a copy of the doc into multiple cases so they all have it.

I continue to think the better answer is to relax our search query (when building docket pages, etc.) to search by document id and NOT case number, rather than both of them, assuming that's what we do now.

**Comment by mlissner** [comment]
This can be closed, right Alberto?

**Comment by albertisfu** [comment]
@mlissner  I don't think so because this is a different issue from attachments #2263 which was recently released. Here the issue is that there are some NEFs that have more than one docket entry for different dockets (the documents seem the same but they have different document and docket numbers). So I need to work also on this.

**Comment by mlissner** [comment]
Got it, thanks Alberto.
