### ISSUE TITLE
Delete old webhook events periodically.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2381]
Reviewing #854 I noticed that we didn't have an issue for this requirement.

**We need to trim old webhook events via a cronjob.**

**Comment by mlissner** [comment]
Thanks for filing. This kept occurring to me too, and then I'd forget to write it down. I'll get it prioritized for you.

**Comment by mlissner** [comment]
It'd be nice if this could fit into the deamon we launched for retries too. Maybe do it as a last step of the daemon loop if `current_minute_of_day % 500 == 0` or something?

**Comment by albertisfu** [comment]
Yes of course I think it's possible to add this into the deamon, a couple of questions:

> current_minute_of_day % 500 == 0

Does this mean that we expect to check for old webhook events to delete 3 times a day (minute of the day: 0, 500, 1000)?

How old do events have to be in order to be deleted? 
We are going to mark events as failed when older than 2 days, but maybe we want them to exist a bit more to be available in logs?

**Comment by mlissner** [comment]
I guess once per day is fine. My point was more that it doesn't really matter, so long as it works. I assume it's performant. 

> How old do events have to be in order to be deleted?

I don't know, um, three months? Six months? I'm not sure it matters since it's just clean up work.

(We do need to document whatever it is somehow though, either in the documentation or with a note on the logs page itself, which could just say, "Logs are deleted after x months" or something. No strong opinions here from me.)
