### ISSUE TITLE
Lots of failing iquery pages

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2419]
Usually Sentry catches this and maybe it did, but I haven't seen an issue. On Friday we released a new version of RECAP that uploads the iquery page. As of this moment, we've gotten about 2k of them (kind of a surprising number!), and of those, about 700 didn't work: 

https://www.courtlistener.com/api/rest/v3/recap/?upload_type=12&status!=2

(Status of 2 is "success", so these are ones that have `status!=2`, a clever trick our API supports.)

Not sure what's up with these, but we should investigate. @albertisfu, I'm going to put this on your queue, but if it winds up being the extension, let's kick it over to @ERosendo.

**Comment by albertisfu** [comment]
I've checked this, I got some random files from these unsuccessful `CASE_QUERY_PAGE` uploads.

Seems that the problem is partially related to [#598](https://github.com/freelawproject/juriscraper/issues/598)

From my sample, some of the uploads belong to `CASE_QUERY_RESULT_PAGE`. So once we start getting these uploads using the new `upload_type`, this might be solved.

Some more are from a different page **"Select a Person"** (maybe this page also uses the iquery url), so I think the solution that @ERosendo proposed for the extension about not relying on the URL to identify Case Query pages and instead use the HTML might solve the problem.

Here are some screenshots from my sample:

![Screen Shot 2022-12-19 at 19 36 25](https://user-images.githubusercontent.com/486004/208562389-2511ca34-d80b-4faf-9477-d9936545314f.png)
![Screen Shot 2022-12-19 at 19 41 24](https://user-images.githubusercontent.com/486004/208562440-5b0d5e14-5044-4150-8611-01849dfb00fc.png)


![Screen Shot 2022-12-19 at 19 38 21](https://user-images.githubusercontent.com/486004/208562519-7dc10c08-fd23-4e55-96a2-b1a59142cd14.png)
![Screen Shot 2022-12-19 at 19 37 28](https://user-images.githubusercontent.com/486004/208562556-3ac100b7-9bcd-4eb9-8683-9357c117e6ae.png)

I attach the Select a Person HTML if is useful for Eduardo to identify this page:
[person_html.zip](https://github.com/freelawproject/courtlistener/files/10264056/person_html.zip)

**Comment by ERosendo** [comment]
@albertisfu I've just created a PR to address this issue related to the `CASE_QUERY_PAGE` uploads.

**Comment by ERosendo** [comment]
@albertisfu Yes, you're right. The extension will ignore pages similar to the **"Select a Person"**.

**Comment by albertisfu** [comment]
Perfect, thanks you!
