### ISSUE TITLE
Deleting your account should nuke your account history too

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2490]
In #2489, we're adding history tracking to the user tables and a handful of tables that store user-created things (alerts, notes, etc). 

When somebody deletes their account, we should also delete or wipe these tables too, so we truly don't have any more stuff about the user. I'm guessing that's pretty straightforward, but if not, please let me know and we can evaluate how much effort to put into this.

**Comment by quevon24** [comment]
this is an excellent question, i think there is no way to revert a deleted object with pghistory because the original object is deleted, so there is no way to call revert() method, so we probably need to remove everything related from pghistory tables

to delete the history for all registered models, we probably need to override the model's delete method to get the history before deleting the actual object.
