### ISSUE TITLE
Clicking docket numbers or citations once or twice should automatically select it

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2518]
Sentry has this great feature. They know that people constantly copy/pasting the issue number, so when you click it once or twice, it magically selects the whole thing. 

We should do that for citations and docket numbers. I know I'd appreciate it.

**Comment by DasWordNerd** [comment]
Changing [this class](https://github.com/freelawproject/courtlistener/blob/main/cl/assets/static-global/css/override.css#L574) to add a user-select property would do what you want.
```
.meta-data-value {
  margin-right: 2em;
  user-select: all;
}
``` 
At least it did in my browser when I edited the CSS via dev tools. I have not tested cross-browser or in a sim env; I don't have a build to use for that.

However, you may want a custom class ( maybe `meta-data-value-selectall` ) for just these two meta-data-value fields if you think this feature wouldn't be helpful on the other fields that share the same class (e.g., precedential status). I can't quite tell which template file controls this part of the opinion page because there's an include that seems to duplicate some of the logic, but it looks to me like [this is the right area](https://github.com/freelawproject/courtlistener/blob/main/cl/opinion_page/templates/opinion.html#L278) if you decide to make that minor change.

**Comment by mlissner** [comment]
Cool! I had no idea you could control the select with CSS. That seems....out of spec? When did selection become part of the style? Weird. Maybe the spec authors did this just to make this easy? 

Your analysis looks good. We could apply it to `meta-data-value`, but I think that'd be too broad (like, if you have multiple citations, it'd make it hard to select just one).

Do you want to take a stab at fixing this? I think we'd just want to:
 - add a new class for `.select-all`
 - add that class to docket numbers wherever they appear in templates
 - wrap each citation with a `<span>` containing the class

And for bonus points:
 - We could investigate applying this to the citations that are in the text of opinions, but that might be hard (either the citations have to be re-found, or we have to add this to an existing class on the citations). If we have to re-find the citations, that's OK. We'll probably do that in the next six months or so anyway.

Want to take this on?

**Comment by DasWordNerd** [comment]
I definitely agree that it's a convenient way of achieving the desired effect. Sometimes the W3C blesses us with a super useful prop and it's best not to ask too many questions lest they decide to deprecate it out of spite :) 

I'm happy to work on this! I don't have a dev environment for CL and it looks like that would take some time to set up especially given my lack of familiarity with django. If you're comfortable forking a PR from me to run tests locally using your own sandbox, I could probably get this in tonight or tomorrow night. Otherwise it might be this weekend or next weekend when I have more time to focus on the env aspect. I can do the CLA either way.

On the in-opinion citations front, I would want to think about that some more. Those are usually hrefs to other CL opinion pages and a select-all style on them might create a bit of difficulty for users who want to visit those other opinions rather than merely select the text for copying. Maybe the bonus-points idea would fit better in the 'this case cites to' list of cites? Anyway, I'll take on the low-hanger for now and we can use that to think a bit more about the in-opinion context.

**Comment by mlissner** [comment]
Wonderful! We don't have a quick way to give you a dev environment aside from what's in DEVELOPING.md, sorry. I wish.

Django's pretty simple most of the time, and it's very well documented. Chime in if you get stuck and need a pointer. 

Agree re not making links selectable. That would be confusing. So let's take the bonus points off the table. If we keep it simple, I'm guessing this will be a pretty fun and easy bug.
