### ISSUE TITLE
Make pghistory work on first changes to models

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2531]
I did an experiment with @flooie today. We grabbed a docket that had never been changed, and we changed it to see if we could revert it. It turns out that because django-pghistory tracks the NEW data, not the OLD, and writes events on INSERT, not DELETE, we can't revert the change. Here's the demo:

```txt
# Start by checking the event table for rows (there are none)
courtlistener=> select * from search_docketevent where id = 4761309;
(0 rows)

# Then, we update the row via CL's admin interface and we have an event with the NEW values
courtlistener=> select * from search_docketevent where id = 4761309;
 pgh_id  |        pgh_created_at         | pgh_label |   id    |         date_created         |         date_modified         | source | appeal_from_str |  assigned_to_str  | referred_to_str | panel_str |    date_last_index     | date_cert_granted | date_cert_denied | date_argued | date_reargued | date_reargument_denied | date_filed | date_terminated | date_last_filing | case_name_short |                         case_name                         |                          case_name_full                          |                           slug                           | docket_number | docket_number_core | pacer_case_id |         cause         |     nature_of_suit      | jury_demand | jurisdiction_type | appellate_fee_status | appellate_case_type_information | mdl_status | filepath_local | filepath_ia |                                      filepath_ia_json                                      | ia_upload_failure_count | ia_needs_upload |  ia_date_first_change  | date_blocked | blocked | appeal_from_id | assigned_to_id | court_id | idb_data_id | originating_court_information_id |            pgh_context_id            | pgh_obj_id | referred_to_id ---------+-------------------------------+-----------+---------+------------------------------+-------------------------------+--------+-----------------+-------------------+-----------------+-----------+------------------------+-------------------+------------------+-------------+---------------+------------------------+------------+-----------------+------------------+----------------+-----------------------------------------------------------+------------------------------------------------------------------+----------------------------------------------------------+---------------+--------------------+---------------+-----------------------+-------------------------+-------------+-------------------+----------------------+---------------------------------+------------+----------------+-------------+--------------------------------------------------------------------------------------------+-------------------------+-----------------+------------------------+--------------+---------+----------------+----------------+----------+-------------+----------------------------------+--------------------------------------+------------+----------------
 1889848 | 2023-02-07 17:03:29.307772+00 | snapshot  | 4761309 | 2017-04-19 07:56:57.91245+00 | 2023-02-07 17:03:29.342388+00 |      9 |                 | Patrick J. Duggan | Mona K. Majzoub |           | 2021-01-23 23:39:31+00 |                   |                  |             |               |                        | 2005-07-05 | 2005-09-06      | 2005-09-06       | Head            | Head v. Farm Bureau General Insurance Company of Michigan | Eugene Head v. Farm Bureau General Insurance Company of Michigan | head-v-farm-bureau-general-insurance-company-of-michigan | 2:05-cv-72650 | 0572650            | 203175        | No cause code entered | Bankruptcy Appeal (801) |             | Federal question  |                      |                                |            |                |             | https://archive.org/download/gov.uscourts.mied.203175/gov.uscourts.mied.203175.docket.json |                         | t               | 2018-09-30 07:00:00+00 |              | f       |                |            934 | mied     |    21090748 |                                  | 4b933b6c-8263-489a-9d34-535dec5e95d8 |    4761309 |           9310
(1 row)
```

Fine, but the old values are gone (the case_name was previously just `HEAD`). So there's no way to revert. 

I filed this upstream here: https://github.com/Opus10/django-pghistory/issues/78. Hopefully we'll get some discussion.

**Comment by quevon24** [comment]
The problem of saving new data instead of old is because of the default snapshot tracker (this automatically generates the insert/update triggers without the needing to do anything complex), the problem is that you don't have much control over it and the behaviour of each trigger.

Probably the easiest way to fix it is to duplicate the snapshot tracker, and change the code.

The other way is to write a longer decorador in each model that will forcefully require a small sql statement

I also found something that could be a problem, depending on the point of view of who sees it, since it would be more related to the user level. When you have a model with an auto_now field like date_modified field, every time you save something it will fire the trigger in the db, even if you didn't make any changes (e.g., user adds a note, then decides to make a change, in the end the user didn't make any change but is paranoid and clicks the save button (i'm telling you from experience), this will cause date_modified to be updated causing to fire the trigger, and this will create a backup without changed data, if we don't care about date_modified field we can exclude it from tracking)

**Comment by mlissner** [comment]
Re the date_modified fields, storage is cheap and it's worth knowing when something changed, so I think that's fine.  We'll wind up trimming the history logs anyway, once they get big enough that they become a problem. 

Can you show me the code you want to duplicate and change? Would it make sense to fork the package or vendor it, or...what are you thinking?

**Comment by quevon24** [comment]
> Re the date_modified fields, storage is cheap and it's worth knowing when something changed, so I think that's fine. We'll wind up trimming the history logs anyway, once they get big enough that they become a problem.
> 
> Can you show me the code you want to duplicate and change? Would it make sense to fork the package or vendor it, or...what are you thinking?

@mlissner I already found a way to fix the problem with auto_now fields, we will save the value of auto_now fields as date_modified, but ignore them comparing old and new data before firing any trigger.

You can take a look to the code here: https://github.com/freelawproject/courtlistener/blob/2531-make-pghistory-work-on-first-changes-to-models/cl/lib/pghistory.py

The changes are in L37, L43 and L61

One setback i found  using NEW for insert (OLD is null in insert operations) and OLD for update is that when you make an insert and the first update, the first row will we duplicated until the next update, this is normal because now we are storing OLD value instead of NEW (e.g., you add a new note with "x" name, this will create a history object for the insert, then you change the note name to "y", this will fire update trigger and will copy old value "x", then you change again the name to "z", now "y" will be stored and if your revert the object, you will have "y" again, etc.), 

This behavior will only happen on first update and insert, after that all  history will have old values stored instead of new. And of course we have to keep in mind that if we revert an object, that will fire the update trigger and create a row with OLD data before reverting the object.

**Comment by quevon24** [comment]
> I'm sorry, I totally don't follow what you're saying here:
> 
> > One setback i found using NEW for insert (OLD is null in insert operations) and OLD for update is that when you make an insert and the first update, the first row will we duplicated until the next update, this is normal because now we are storing OLD value instead of NEW (e.g., you add a new note with "x" name, this will create a history object for the insert, then you change the note name to "y", this will fire update trigger and will copy old value "x", then you change again the name to "z", now "y" will be stored and if your revert the object, you will have "y" again, etc.),
> 
> Could you do a chronological little table like this (or similar):
> 
> Step	Action	Real table contents	History table contents	Status/Notes
> 1	First insert	The new values	null	OK
> 2	First update	The new values	The values from step 1	OK
> Etc? I'm not quite following the issue you're saying, sorry.

@mlissner No problem, in fact it's a good idea to use a table, i didn't know you could do that in the comments.

| Step | Action | Real table contents | History table contents | Status/Notes |
| --- | --- | --- | --- | --- |
|1|First insert|The new values, e.g., "x" |The new values, e.g., "x" |Ok, backup original|
|2|First update|The new values, e.g., "y" |Values first insert, e.g., "x" |Values are the same from step 1, update store old value from backup|
|3|Second update|The new values, e.g. "z" |Values first update, e.g., "y" |Values changed, store old|
|4|Revert object|Last value stored in history table, e.g., "y" | Value from previous update, e.g., "z" |We store previous value because revert triggers an update|

As you can see, we will have the first insert values duplicated, and after that we will continue to store old values, and as you can see, if we revert directly using pghistory's revert() function, it will perform an update which will cause to store the newest value.

**Comment by mlissner** [comment]
After rolling this out, I figured I better clean up the old records. These are the event tables with the most rows:

```
courtlistener=>     SELECT c.oid,nspname AS table_schema, relname AS table_name
              , c.reltuples AS row_estimate
              , pg_total_relation_size(c.oid) AS total_bytes
              , pg_indexes_size(c.oid) AS index_bytes
              , pg_total_relation_size(reltoastrelid) AS toast_bytes
          FROM pg_class c
          LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE relkind = 'r' AND relname like '%event%' AND reltuples > 1000 order by row_estimate desc;
   oid    | table_schema |               table_name                | row_estimate  | total_bytes | index_bytes | toast_bytes 
----------+--------------+-----------------------------------------+---------------+-------------+-------------+-------------
 23271507 | public       | search_recapdocumentevent               | 9.5392944e+07 | 47915614208 |  7216021504 | 24308858880
 23271408 | public       | search_docketentryevent                 | 9.2887696e+07 | 22193766400 |  5857091584 |    63496192
 23271353 | public       | search_bankruptcyinformationevent       | 5.5500112e+07 |  9768304640 |  2901983232 |        8192
 23271426 | public       | search_docketevent                      | 3.6848392e+07 | 14787297280 |  4329242624 |       65536
 23271692 | public       | alerts_docketalertevent                 |        386638 |    84582400 |    25214976 |        8192
 23271453 | public       | search_opinionclusterevent              |        148959 |    64741376 |    11599872 |     3293184
 23271380 | public       | search_claimhistoryevent                |         68246 |    19652608 |     4816896 |        8192
 23271480 | public       | search_opinionevent                     |         58282 |   583942144 |     4628480 |   550305792
 23271371 | public       | search_claimevent                       |         54315 |    16416768 |     3432448 |        8192
 23272187 | public       | users_userproxyevent                    |         30918 |    10518528 |     2547712 |        8192
 23272178 | public       | users_userprofileevent                  |         26172 |     7331840 |     2646016 |        8192
 23271683 | public       | alerts_alertevent                       |         16018 |     6832128 |      892928 |       98304
 23271498 | public       | search_originatingcourtinformationevent |         13200 |     2924544 |     1015808 |        8192
 23271362 | public       | search_citationevent                    |          4220 |      868352 |      401408 |        8192
 23271444 | public       | search_dockettagsevent                  |          4061 |      712704 |      360448 |        8192
 23271516 | public       | search_recapdocumenttagsevent           |          4058 |      704512 |      352256 |        8192
 23271417 | public       | search_docketentrytagsevent             |          4058 |      704512 |      352256 |        8192
 23271910 | public       | audio_audioevent                        |          3890 |     2170880 |      352256 |        8192
```

I deleted each of these by hand with something like:

```SQL
delete from audio_audioevent;
```

It took a while for some of the larger ones, but it should reclaim a lot of space.
