### ISSUE TITLE
Do milestone tracking for webhook events sent

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2533]
We currently track how many times somebody used the API and then send a daily email when folks hit milestones. 

We should do this for webhooks too so that we can easily know who our big users are (and contact them for commercial contracts if it makes sense to do so).

A few things to note:
 - We send a daily email for the API usage. This can just go in there too.
 - We don't care about smaller milestones with the API (using it five times isn't interesting), but we do for webhooks.
 - We should probably ignore debug and failing events when tracking this, but if that's hard, that's fine too.

**Comment by albertisfu** [comment]
@mlissner  A couple of questions about this one:

- I saw that for tracking API usage an "Event" object is created every time a milestone is reached, then there is the "send_events_email" command that sends the events created in the last 24 hours. So that for Webhooks we should follow the same process, right?
- Regarding the milestones for API usage, we have:
```
 (
        ("XXS", [1e0, 5e0]),  # 1 - 5
        ("XS", [1e1, 2.5e1, 5e1, 1e2, 2.5e2, 5e2]),  # 10 - 500
        ("SM", [1e3, 2.5e3, 5e3, 1e4, 2.5e4, 5e4]),  # 1_000 - 50_000
        ("MD", [1e5, 2.5e5, 5e5]),  # 100_000 - 500_000
        ("LG", [1e6, 2.5e6, 5e6]),  # 1M - 5M
        ("XL", [1e7, 2.5e7, 5e7]),  # 10M - 50M
        ("XXL", [1e8, 2.5e8, 5e8]),  # 100M - 500M
        ("XXXL", [1e9, 2.5e9, 5e9]),  # 1B - 5B
    )
```

You mentioned that we should track milestones starting from small numbers. Should we consider tracking milestones from `XXS` to `XXXL`, or do you think we'll need more granular milestones for webhooks?

**Comment by mlissner** [comment]
Looks like you got it figured out. Let's track all the milestones from XXS to XXXL, and yeah, the same process would be great. It can be included in the same email too.
