### ISSUE TITLE
Feature request: When looking at docket pages it would be nice to have a next/prev button at the top

### ISSUE THREAD

**Issue by troglodite2** [freelawproject/courtlistener#2670]
Currently, the filter header looks like this:
![image](https://user-images.githubusercontent.com/82225842/234108123-19bd0e9c-4ffb-4d5b-8ff6-cf60ea6bc83d.png)

Adding a next/previous in the header should be doable.

**Comment by mlissner** [comment]
Want to try a mockup/prototype with the smallest of buttons you can cram into the far left and right?

**Comment by troglodite2** [comment]
![image](https://user-images.githubusercontent.com/82225842/234383914-6a3ed719-1e09-42c0-8bba-0c6d1a6c5ef3.png)

This is the full size mock up.  If this is what you are looking for, then I'll go a head and code the responsive versions as well.

**Comment by mlissner** [comment]
That's not bad. I was actually thinking of something simpler. Could you mock up just the arrows themselves on the far left and far right, maybe with a mouseover that says Previous/next? That's what's in my mind's eye, and I think it'd be pretty elegant.

**Comment by troglodite2** [comment]
I heard that you are looking for something different.  I want to present a couple of different options:
Option 1:
![image](https://user-images.githubusercontent.com/82225842/234657673-faf331d4-9872-4270-9aaf-3b843e1874cd.png)
Prev. at the front, next at the end of the line.  The ascend/descend buttons changed so that only the clickable version shows.

Option 2: 
The same layout but now only the next/previous arrows showing.  I've also changed the order to show the button changing
![image](https://user-images.githubusercontent.com/82225842/234658346-d8bf9733-7875-4268-b6b7-806d5a90ea3c.png)

Option 3:
Previous/next arrows at the end of the bar, still with the ascend/descend showing only one button.
![image](https://user-images.githubusercontent.com/82225842/234659404-f7a073fa-446b-4d5b-8512-928878194368.png)
We can tweak the placement of the arrows in there as well.

Option 4:
Previous/Next plus arrows at the end of the filters.
![image](https://user-images.githubusercontent.com/82225842/234659695-e74ce35e-6007-42ac-85d7-a131f0260457.png)

Option 5-8: 
The same as above, but going back to showing the redundant sort order button.

If there is something else you would like to suggest, let me know.

**Comment by mlissner** [comment]
The last one has some good things going for it, but I don't think the single button will work for asc/desc, like it does at the top of tables — it's just not a pattern you see anywhere else that I can think of. It suffers from the play/pause button problem, where it's trying to show what it's doing, and also that it has an affordance for switching what it's doing. 

I fear a long, distracting digression, but historically, digital music players copied from physical ones, and had two buttons you could click on, like this:

```
⏵ ⏸
```

And you could click one and it'd interact with the other. Then, in Windows XP or so, we switched to a single button that swapped between `⏵` and `⏸`, doubling as both an affordance ("You can click this to change the state") and information ("This shows `⏸` because the music is playing"). I remember at the time being confused because if your headphones aren't in and you see a `⏸` button, that means your music is...paused? Playing? We're all used to this now, but it wasn't so obvious back then. 

Anyhow, the ordering icons at the top of tables and in the screenshots above are the same problem, but with weaker iconography. They show both something you can do, and the state of the ordering. When they show `↓`, I *think* that means the newest stuff is at the...bottom? But I kind of don't care, because I know that clicking it will flip things, and I can skim to see if it's in the order I want. As a button, like in your screenshot, I'm not sure what it does. Does it mean that the stuff is ascending? Or does it mean that clicking it *makes* the stuff ascending? I don't know! 

So, anyhow, that's my long digression, but could we try something slightly different? Could we try doing the fourth approach above, wrt to pagination, but switch in the mobile button for the ordering one? 

![image](https://user-images.githubusercontent.com/236970/234669003-bda8c61e-98ce-4be5-b1dd-39ed24b31e1f.png)

I hope you enjoyed by historical digression. I guess I'm something of an old timer.

**Comment by troglodite2** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/82225842/234678046-4cc8ea8d-0ee8-4c86-9cc1-e7c58d7b8fb1.png)

**Comment by mlissner** [comment]
I dig it, yep. Could we try adding `Asc.` and `Desc.`? 

How's it look on mobile?

**Comment by troglodite2** [comment]
![image](https://user-images.githubusercontent.com/82225842/234679718-dadd3d9c-67d1-4ed3-98e1-6d5554d104c9.png)

I haven't started working on mobile yet.  Once we have a rough conscience, I'll verify at all the responsive levels.

**Comment by mlissner** [comment]
That looks great to me. :shipit:

**Comment by troglodite2** [comment]
bootstrap-lg, bootstrap-desktop:
![image](https://user-images.githubusercontent.com/82225842/234704678-8802fd39-fffa-4070-8bbc-cb6aa7b2da45.png)

bootstrap-md:
![image](https://user-images.githubusercontent.com/82225842/234704553-f614d900-67bc-4b2a-8253-7640b1400225.png)

bootstrap-sm:
![image](https://user-images.githubusercontent.com/82225842/234705360-86f67968-e813-40ec-abbd-4fcfd07cc2ac.png)

**Comment by mlissner** [comment]
Yeah, that small is bad. Maybe just hide the new pagination buttons and have it work like it did before?

**Comment by troglodite2** [comment]
Bootstrap-sm:
![image](https://user-images.githubusercontent.com/82225842/234716877-29ba9971-4828-43b7-b3cd-504cfc1d0af9.png)

**Comment by troglodite2** [comment]
Option 2:
![image](https://user-images.githubusercontent.com/82225842/234717028-6a4eef7e-2837-4ee9-82fc-b4275a916f36.png)

**Comment by mlissner** [comment]
Option 2 looks great, thanks!

**Comment by troglodite2** [comment]
bootstrap-xs:  This doesn't look like what is currently there for xs:
![image](https://user-images.githubusercontent.com/82225842/234736326-1a38c3b7-4456-4174-abad-8313750d8f10.png)

bootstrap-xs-mini 360px:  I'm not done with this one, I'm thinking on it.
![image](https://user-images.githubusercontent.com/82225842/234736684-898122bd-e80e-4e6b-a312-0ecd2a7926b0.png)

**Comment by mlissner** [comment]
Your xs looks better than what's there. If it just put the up/down boxes to the right, I think we'd be in good shape. 

For the xs-mini-360, yeah, that's pretty bad. Maybe just drop the filed from/to boxes too?

**Comment by troglodite2** [comment]
How about:
Option 1:
![image](https://user-images.githubusercontent.com/82225842/234882886-610aed4e-2a3d-4abc-b075-1ca38e788d80.png)

**Comment by troglodite2** [comment]
Sorry for two entries:
Option 2:
![image](https://user-images.githubusercontent.com/82225842/234883455-4f87766a-5477-482d-b0c4-fe4f46d3b533.png)

**Comment by mlissner** [comment]
Those are both great, if they're not too much of a headache to get right, with a slight preference for the second one. Thanks!
