### ISSUE TITLE
Fix old search-related issue while migrating oral argument search to Elastic Search

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2675]
In [this tag](https://github.com/freelawproject/courtlistener/labels/search), we've piled up 34 valid and mostly reasonable requests that folks have made. 

These are the ones we should fix or at least look at going into the oral argument system:
 - https://github.com/freelawproject/courtlistener/issues/1486
 - https://github.com/freelawproject/courtlistener/issues/739
 - https://github.com/freelawproject/courtlistener/issues/1635
 - https://github.com/freelawproject/courtlistener/issues/231
 - https://github.com/freelawproject/courtlistener/issues/249
 - https://github.com/freelawproject/courtlistener/issues/365
 - https://github.com/freelawproject/courtlistener/issues/2629
 - https://github.com/freelawproject/courtlistener/issues/1886
 - https://github.com/freelawproject/courtlistener/issues/1645
 - https://github.com/freelawproject/courtlistener/issues/1486
 - https://github.com/freelawproject/courtlistener/issues/864
 - https://github.com/freelawproject/courtlistener/issues/824
 - https://github.com/freelawproject/courtlistener/issues/778 (this will affect OA, P, and R)
 - https://github.com/freelawproject/courtlistener/issues/764
 - https://github.com/freelawproject/courtlistener/issues/739
 - https://github.com/freelawproject/courtlistener/issues/231

Whew, that's a lot. As we go, we'll want tests for each of these, I'm afraid, even if it's just one quick query.

**Comment by albertisfu** [comment]
@DictCheney, these are the next tasks we have scheduled to continue working on the Elastic project. They involve requests and issues related to the search that we want to address or incorporate for the Oral Arguments search using Elasticsearch.

Would you like to help us with any of them?

Some of these tasks may have already been resolved now that we're using Elasticsearch. For example, I just checked [Unicode not rendering properly in search snippets #1486](https://github.com/freelawproject/courtlistener/issues/1486), and it appears that this is not a problem in Elasticsearch. I'll simply add a test to confirm that it works correctly in ES.

Currently, I'll be working on [Phrase + conjunction search in fielded search injects too many conjunctions #739](https://github.com/freelawproject/courtlistener/issues/739).

If you'd like to work on any of these tasks, you could just post here which one you'll be working on so we avoid working into the same issue. You can use https://github.com/freelawproject/courtlistener/pull/2748 as a base PR/branch to work from since it contains the most recent Elastic-related changes.

If you have any questions, feel free to ask.
Thank you!

**Comment by albertisfu** [comment]
- [ ] https://github.com/freelawproject/courtlistener/issues/1486
- [ ] https://github.com/freelawproject/courtlistener/issues/739
- [ ] https://github.com/freelawproject/courtlistener/issues/1635 (In progress...)

**Comment by mlissner** [comment]
We're done here, folks.
