### ISSUE TITLE
Feature: Alerts when Federal District Court transcripts are available for purchase

### ISSUE THREAD

**Issue by troglodite2** [freelawproject/courtlistener#2698]
The rules on getting transcripts of district court cases requires the court to hold them for 60(?) days before they can be purchased through PACER.  

For Docket entries such as:

TRANSCRIPT OF PROCEEDINGS held on 01/27/2023 before the Honorable Virginia M. Kendall. Motion Hearing. Order Number: 45107. Court Reporter Contact Information: Gayle A. McGuigan, CSR, RMR, CRR, Gayle_McGuigan@ilnd.uscourts.gov. IMPORTANT: The transcript may be viewed at the court's public terminal or purchased through the Court Reporter/Transcriber before the deadline for Release of Transcript Restriction. After that date it may be obtained through the Court Reporter/Transcriber or PACER. For further information on the redaction process, see the Court's web site at www.ilnd.uscourts.gov under Quick Links select Policy Regarding the Availability of Transcripts of Court Proceedings. Redaction Request due 3/1/2023. Redacted Transcript Deadline set for 3/13/2023. Release of Transcript Restriction set for 5/9/2023. 

It would be nice to get an alert on 5/9/2023 saying that the document is available for purchase from PACER.

**Comment by johnhawkinson** [comment]
> The rules on getting transcripts of district court cases requires the court to hold them for 60(?) days

Ninety days, not sixty. https://www.uscourts.gov/services-forms/federal-court-reporting-program

>  The Judicial Conference approved a policy regarding the availability of transcripts of court proceedings filed with the clerk of court in electronic format. A transcript provided to a court by a court reporter or transcriber will be available at the office of the clerk of court for inspection only, for a period of 90 days (unless extended by the court) after it is delivered to the clerk.

Anyhow, @troglodite2:
> It would be nice to get an alert on 5/9/2023 saying that the document is available for purchase from PACER.

**Why?**

Approximately nobody buys transcripts on PACER in the near term.
Let's say the average transcript is 50 pages (many are 100 or much longer).

That transcript costs $3.65/page if you're first ($182), or $0.90/page if you're second ($45).
If you wait until the 90 day mark, remembering that transcripts on PACER are not subject to the 30-page cap,  it is $0.10/page ($5).

If you're really cash-starved but deeply interested, you can go read it at the Courthouse for free.
(Of course, the transcript is unlikely to be prepared and docketed in CMECF before somebody pays the initial $182, so that option may be unavailable in many circumstances.)

It's not very many people that so interested in a transcript of a hearing that they are willing to wait 90 and pay $5 but are not sufficiently interested to pay $45. Perhaps there are a few, but I can't really imagine who they are. Not parties, who need the transcript much faster. Not reporters. (Also, in many situations you can shake a transcript lose from someone else who has paid.)

Or to expedite it (up to $7.25/pg => $362).

Anyhow, those $5/90-day people, and already quite small set, are not likely to be interested in transcripts for terribly many cases. For the handful (probably just 1 or 2), they can just put a reminder in their calendar if they need it.


There is another set of people for whom the $.10/page rate is important, and that's academics/researchers (&c.) who might be researching a case or group of cases long after the case events. (e.g. years later, not 90 days later). An alert wouldn't be helpful to them either.


So…what's the use case? Convince me! :)
