### ISSUE TITLE
Synonym file needs more entries

### ISSUE THREAD

**Issue by morninj** [freelawproject/courtlistener#273]
When I query `Clapper v. Amnesty Intern. USA`, it should return [this](https://www.courtlistener.com/scotus/5d9s/clapper-v-amnesty-international-usa/?q=&order_by=score+desc&case_name=Clapper+v.+Amnesty&stat_Precedential=on), but instead I get no results.

**Comment by mlissner** [comment]
I just did this today, so this is finally getting fixed once I pull it and things get reindexed. The source for this data is mostly from the [Indigo Book][1], which has many tables of abbreviations, such as:

 - U.S. States and Other Jurisdictions
 - Services & Publishers
 - Legislative Documents
 - Treaties
 - Arbitral Reporters
 - Intergovernmental Organizations
 - Court names
 - Titles of judges and other people
 - Case name abbreviations
 - Geographical terms
 - Document subdivistions (pargaph, section, etc)
 - Explanatory phrases
 - Institutions
 - Publishing terms
 - Month names
 - Common words in periodical names

On top of that, I added a few things:

 - Numbers from 1-20
 - Units
 - And any extra things I saw missing (like trans didn't have a mapping to transgender)

From there I did the following:

 - Remove duplicates (of which there were many)
 - Removed phrases (Solr is [bad at this][2])
 - Removed anything with a period or apostrophe in the middle, like, `U.S.`, because those things get split by Solr anyway.
 - Cleaned up a bunch of items that had brackets, like `trans[lator, lation], trans`. In the case that the expanded word lists were semantically different, I made them into mappings. Else, I made them into synonyms. For example, here's what trans maps to:

        trans => translation,translator,transgender

    Whereas something else might just be:

        assemb,assembly,assemblyman,assemblywoman,assemblymember

    Because they're all essentially the same.
 - Eliminated one-letter abbreviations (they're not likely to be useful)
 - Removed real words that'd cause trouble. For example, we wouldn't want every search for `cat` to turn up results for `category`.

All in all, I think she's a fine list. Definitely a conservative one, which lawyers like, but also one that should make lots of searches (especially those involving abbreviations) work better.

[1]: https://law.resource.org/pub/us/code/blue/IndigoBook.html
[2]: http://opensourceconnections.com/blog/2013/10/27/why-is-multi-term-synonyms-so-hard-in-solr/

**Comment by mlissner** [comment]
This is now deployed, and @morninj, your query is definitely improved: https://www.courtlistener.com/?q=Clapper+v.+Amnesty+Intern.+USA&type=o&order_by=score+desc&stat_Precedential=on

I'm loving it, actually. It's a subtle but big improvement.
