### ISSUE TITLE
[EPIC] Create Elastic Search Server

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2867]
This shouldn't be too hard, given that we do it for Solr already. We'll use this ticket to keep track of our notes. A few things we'll need to do at a minimum:

0. Create a server in Ec2

1. Install ES
    - Provide synonyms and related files to the server
    - Set envs (see docker compose file)
    - Don't put the data into the docker container (mount it instead)

2. Get AWS's stats logger working (see notes from Solr)
    - Set up any alerts to make sure ES stays OK (copy from Solr)

3. Provide access to the server via the Security Groups

Before we create the server, we need to figure out how many nodes, shards, and replicas to create.

**Comment by mlissner** [comment]
OK, Alberto and I just had a quick meeting to discuss how to make the ES cluster. Lots more questions than answers, but we'll use this issue as a tracking issue for all the others. 

AWS Elastic Load Balancer:
 - Do we need this?
 - Does this just do road robin? 
 - What if we don't do this, how does ES route queries?

EC2 Nodes:
 - How many nodes? 
     - Five? Four? Something like that. We'll see.
 - How big of nodes?
     -  Discussed in https://github.com/freelawproject/courtlistener/issues/2874
 - Autoscaling?
 - Snapshotting?
     - Do these use AMI's?
         - If we use AMI's, do we need docker?
     - Do snapshots go into S3?
 - Node discovery via [AWS plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/discovery-ec2.html)?

Elastic Block Devices:
 - One device per node?
 - How big?
     - These can be made bigger later, but it's a bit of a hassle. 
     - At least twice the size of the index

Do we do a dedicated Kibana node?
 - Probably.

Elastic Configuration:
 - How many shards for each object type?
     - Shards need to be 10-50GB as said above.
     - Difficult to make more shards later, or to remove existing ones.
     - Probably have to do some indexing to see how this goes.
 - How many replicas? 
 - How are replicas located?

Alerts and logging?
 - What alerts do we need? 
 - How do we get logging going?

What config/hardware mistakes cause downtime?
 - Needing more shards than initially planned?

How do we make certificates for each node to encrypt traffic?

**Comment by albertisfu** [comment]
Some updates about this issue.

I've been working on setting up a basic Elasticsearch stack with security and SSL enabled on AWS, consisting of one Elasticsearch node and a Kibana instance.

I have created a Dockerfile (an other required setup files) for Elasticsearch and another one for Kibana, allowing me to test the setup locally. You can find the repository here: https://github.com/albertisfu/cl-elastic

The main challenge in setting up secure Elasticsearch and Kibana instances is managing certificates.

Elasticsearch provides a built-in tool called `elasticsearch-certutil` that can generate certificates. This tool allows us to generate a `certificate_authority` that can be used to issue certificates for each Elasticsearch node and Kibana instance.

We can generate these certificates locally. However, the problem of securely and easily distributing the certificates across nodes remains.

To address this, I tested AWS Secrets Manager as a solution to store the certificate_authority and certificates for each Elasticsearch node and Kibana instance. This way, the certificates can be automatically retrieved when running the container.

The self-signed certificates can be used to establish secure connections between nodes and Kibana. However, to access the Kibana web interface, we would need to set up a domain (or sub-domain) and use a certificate issued by a CA trusted by browsers.
Perhaps we could utilize `AWS Certificate Manager` for this purpose?

So the steps to setup a `elasticsearch` node in EC2 are:

1.- Create a EC2 instances for Elasticsearch and Kibana. (I'll describe permissions required in https://github.com/freelawproject/courtlistener/issues/2875)
 - I used a Ubuntu ARM instance
 - Set network settings. For production, are we going to use an existing VPC or create a new one?
 - Subnet. For production, are we going to distribute the cluster nodes across different availability zones?
 - Firewall. We need to create a new security group for Elasticsearch nodes and set a rule that allows inbound traffic on port 9200. For Kibana, we need a security group that allows inbound traffic on port 5601.
 - Chose the storage volume size.

2.- Issue certificates for the node. Once we know the instance IP and Public DNS address, we can issue the certificates for the node.
 - In a local elasticsearch instance, issue a certificate authority: 
`bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip`
 - Create a `instances.yml` file with the data to issue certificates, it's possible to issue multiple certificates at once:

e.g:
```
 instances:
  - name: "ec2-3-000-126-93.us-west-1.compute.amazonaws.com"
    dns: [ "ec2-3-000-126-93.us-west-1.compute.amazonaws.com", "localhost" ]
    ip: ["3.101.000.93", "172.00.28.11", "127.0.0.1"]
```

Then run the utility using the certificate authority previously issued:
`bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key`

Then we can store the certificates in `AWS secrets manager`, using a different key for each one, eg:

```
dev/certs/cl-es-key
dev/certs/cl-es-crt
dev/certs/ca-cert
```

3.- To setup elasticsearch node in the EC2 instance, connect to the instance and install docker:

```
sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install docker-ce
sudo systemctl status docker
```

4.- Download dockerfiles from Github and move to directory `elastic`
- Build docker image: `sudo docker build -t elasticsearch-node .`
- Run docker image passing the required env vars, including the certificate secrets IDS, the AWS credentials to get them, the volume to mount in order to make data persistent and heap memory size.

e.g:

`sudo docker run -e ES_NODE_KEY_SECRET_ID=dev/certs/cl-es-key -e ES_NODE_CERT_SECRET_ID=dev/certs/cl-es-crt -e CA_CERT_SECRET_ID=dev/certs/ca-cert  -e AWS_ACCESS_KEY_ID=YOUR_KEY -e AWS_SECRET_ACCESS_KEY=YOUR_SECRET -e AWS_DEFAULT_REGION=default_region -p 9200:9200 -p 9300:9300 -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -v local/path/data:/usr/share/elasticsearch/data --name cl-es-node elasticsearch-node`

5.- Then after container is running,  it is necessary to set up passwords:
```
sudo docker exec -it cl-es-node sh
bin/elasticsearch-setup-passwords auto -u 'https://localhost:9200/'
```
We need to save these passwords, we'll need them to connect Kibana and connect to elasticsearch node.

**To setup Kibana in a EC2 instance, follow steps 1,2 and 3.**

4.1.- Download dockerfiles from Github and move to directory `kibana`
- Build docker image: `sudo docker build -t kibana-cl-image .`
- Run docker image passing the required env vars, that includes the certificate secrets IDS, the AWS credentials to get them, the volume to mount in order to make data persistent.

`sudo docker run e KIBANA_KEY_SECRET_ID=dev/certs/cl-kibana-key -e KIBANA_CERT_SECRET_ID=dev/certs/cl-kibana-crt -e CA_CERT_SECRET_ID=dev/certs/ca-cert e AWS_ACCESS_KEY_ID=YOUR_KEY -e AWS_SECRET_ACCESS_KEY=YOUR_SECRET -e AWS_DEFAULT_REGION=default_region -e ELASTICSEARCH_PASSWORD=password -v path/local/kibana_data:/usr/share/kibana/config -p 5601:5601 kibana-cl-image`

At this point the Kibana should be running, currently you can enter to the testing Kibana instance using the public EC2 instance subdomain:
https://ec2-54-153-39-149.us-west-1.compute.amazonaws.com:5601/
You'll need to omit the secure message shown by the browser.

I think we're close to deploying our basic Elasticsearch cluster, but we still need to answer some questions:

- Are we going to make the Kibana web interface available to the internet (password-protected and using an SSL connection)? If so, we will require a domain or sub-domain from which we can issue a certificate trusted by browsers.

- Alternatively, should we make it only available within the VPC and use AWS Client VPN to connect to it?

- How are we going to manage containers if we decide to use Docker? One advantage of using Docker is that we can test settings before rolling them out to production, similar to how it currently works with the Solr image. While we won't be able to test distributed features locally, we can at least reproduce single-node settings.

- If we choose to use Docker, will we need to use an orchestration tool such as Kubernetes, Docker Swarm, or Amazon's ECS?

- The alternative to using Docker is to directly replicate the setup described in the Dockerfiles on the EC2 instances and enable the Elasticsearch service on boot.

Let me know your thoughts on these points. I will continue to check the remaining questions we have for this issue.

**Comment by albertisfu** [comment]
More updates regarding this issue:

I've now set up a multi-node cluster in AWS, the settings for which differ slightly from those of a single-node cluster.

Steps 1, 2, 3, and 4 from the previous comment remain the same.

`.yml `template files for elastic and kibana can be found in this  [branch](https://github.com/albertisfu/cl-elastic/tree/multi-setup-cluster).

Changes on .yml files are the following:

```
node.name: cl-es-node
network.host: [_local_,_site_] 

# These settings are required if elasticsearch is running within a docker container, otherwise node discovery will fail.
# Since by default ES use the container IP instead of the machine private IP.
network.publish_host: node_private_ipv4
http.publish_host: node_private_ipv4
transport.publish_host: node_private_ipv4

# Assign these roles for a master eligible node.
node.roles: [ master, data ]

# Only assign the data role for a no master eligible node.
# node.roles: [ data ]

discovery.seed_hosts: ["master_eligible_nodes_private_ipv4"]
# This setting is only required on the master-eligible node during cluster formation.
# It should be removed after the cluster has been formed.
cluster.initial_master_nodes: ["cl-es-node"]
```

 1.- Adjust the `elasticsearch.yml` file according to each node that needs to be set up.
Master eligible nodes should contain:
`node.roles: [ master, data ]`
`discovery.seed_hosts: ["master_eligible_nodes_private_ipv4"]`
`cluster.initial_master_nodes: ["cl-es-node", "other_master_eligible_nodes"]`

Data only nodes:
`node.roles: [ data ]`
`discovery.seed_hosts: ["master_eligible_nodes_private_ipv4"]`

Before starting the cluster formation for the first time, confirm that:

The local data directory to be mounted is empty (to avoid data from a previous failed formation).
The local data directory to be mounted has the correct permissions to be accessible from Docker:
`sudo chmod a+w /local/path/data`

Set [virtual memory](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html) to at least: 262144
`sudo sysctl -w vm.max_map_count=262144`

Start the cluster formation by running master nodes, and run containers on every master-eligible node.

- Adjust "ES_JAVA_OPTS=-Xms512m -Xmx512m" (memory heap) according to the machine resources.

`sudo docker run  --ulimit memlock=-1:-1 -e ES_NODE_KEY_SECRET_ID=dev/certs/cl-es-key -e ES_NODE_CERT_SECRET_ID=dev/certs/cl-es-crt -e CA_CERT_SECRET_ID=dev/certs/ca-cert -e AWS_ACCESS_KEY_ID=YOUR_KEY -e AWS_SECRET_ACCESS_KEY=YOUR_SECRET -e AWS_DEFAULT_REGION=default_region -p 9200:9200 -p 9300:9300 -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -v /home/cl-es/data:/usr/share/elasticsearch/data -v /home/cl-es/cl-elastic/elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml --name cl-es-node elasticsearch-node`

2.- After starting the master-eligible nodes, initiate the data nodes following the same process.

- Set cluster passwords:
`sudo docker exec -it cl-es-node sh`
`bin/elasticsearch-setup-passwords auto -u 'https://localhost:9200/'`

3.- Setup kibana for multi-node cluster.

The local data directory to be mounted has the correct permissions to be accessible from Docker:
`sudo chmod a+w /local/path/kibana_data`

Tweak `kibana.yml` accordingly:

```
server.name: cl-kibana
server.host: "0.0.0.0"
elasticsearch.hosts: ["https://node-host:9200", "https://node-host-2:9200", "https://node-host-3:9200"]
elasticsearch.username: "kibana_system"
server.ssl.enabled: true
server.ssl.certificate: config/certs/cl-kibana.crt
server.ssl.key: config/certs/cl-kibana.key
elasticsearch.ssl.certificateAuthorities: config/certs/ca.crt
monitoring.ui.ccs.enabled: false
```

The main required changes include:
- Setting the list of all ES node hosts.
`elasticsearch.hosts: ["https://node-host:9200", "https://node-host-2:9200", "https://node-host-3:9200"]`

- Set `monitoring.ui.ccs.enabled: false` in order to solve the `Access Denied error` in multi-cluster setup.

- Run the container:
`sudo docker run e KIBANA_KEY_SECRET_ID=dev/certs/cl-kibana-key -e KIBANA_CERT_SECRET_ID=dev/certs/cl-kibana-crt -e CA_CERT_SECRET_ID=dev/certs/ca-cert e AWS_ACCESS_KEY_ID=YOUR_KEY -e AWS_SECRET_ACCESS_KEY=YOUR_SECRET -e AWS_DEFAULT_REGION=default_region -e ELASTICSEARCH_PASSWORD=password -v path/local/kibana_data:/usr/share/kibana/data -v /home/cl-es/cl-elastic/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml -p 5601:5601 kibana-cl-image`

New data nodes can be added at any time following the same process.

**Regarding the number of nodes and roles in a cluster:**
If we're considering around ~5 machines for our cluster, this could be seen as a small cluster, according to the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.8/high-availability-cluster-small-clusters.html).

The recommended number of master-eligible nodes in a small cluster is three to ensure resilience. This way, if the master node fails, the remaining two master-eligible nodes can perform an election to choose a new master, allowing the cluster to continue functioning properly.

Additionally, we can add two more data nodes. Here are some configuration role scenarios with their respective upsides and downsides, according to my understanding:

**3 Master-eligible/Data-nodes + 3 Data-nodes:**
In this setup, three nodes are configured as both master-eligible and data nodes, and the remaining two are only data nodes.

Advantages:
Best resource utilization: The three nodes that are both master-eligible and data nodes can handle requests and store data, so resources are not under-utilized.
Resilience: Since there are three master-eligible node if one fails, another can take its place.
Scalability: The cluster can handle more data since every node can store data.

Disadvantages:
Posible performance degradation: If master nodes are overloaded by coordinating tasks, they may have less capacity to handle data or if data tasks makes the master busy it might struggle to perform coordinating tasks.

**3 Dedicated master-nodes + 3 Data-nodes:**
This configuration is formed of 3 nodes dedicated only to being master-eligible and two nodes to be only data nodes.

Advantages:
Separation of tasks: Master nodes are isolated from data nodes, reducing the chance of resource exhaustion by data tasks that will result performance degradation.
Resilience: Since there are three master-eligible node if one fails, another can take its place.

Disadvantages:
Resources underutilization: The master nodes may be underutilized as they aren't storing data or handling search queries, this could be minimized assigning less resources to these machines.
Limited data capacity: With only two data nodes, the cluster has less data storage capacity.

**About the number of shards per index.**
The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html#shard-size-recommendation) recommends keeping the size of shards between 10 and 50GB, as larger shards take longer to recover after a failure and also make maintenance tasks more complex.

To leverage Elasticsearch's distribution and resilience capabilities, the number of shards per index should also take into account the number of data nodes. For example, if we're going to have 5 data nodes or master/data nodes, we should choose a minimum of 5 shards, so each shard can be distributed to one data node. Generally, the number of shards per index should be divisible by the number of data nodes (5, 15, 20, etc).

**Regarding shard replicas**
 If we want to enhance the performance and reliability of an index search, we should set up at least one replica per shard. Each replica will be stored on a different node from the primary shard, so that if the primary shard goes down, the replica will  completely sustite the shards until it gets back.

**Load Balancer might no be required.**

I tought a load balancer might be required as documentation [suggested](https://www.elastic.co/guide/en/elasticsearch/reference/8.8/high-availability-cluster-small-clusters.html) it:

> You should also avoid sending client requests to just one of the other two nodes. If you do, and this node fails, then any requests will not receive responses, even if the remaining nodes form a healthy cluster. Ideally, you should balance your client requests across both of the non-tiebreaker nodes. You can do this by specifying the address of both nodes when configuring your client to connect to your cluster. Alternatively, you can use a resilient load balancer to balance client requests across the appropriate nodes in your cluster. The [Elastic Cloud](https://www.elastic.co/cloud/elasticsearch-service/signup?baymax=docs-body&elektra=docs) service provides such a load balancer.

However, a load balancer might only be useful if the Elasticsearch client is unable to send requests to all the nodes in the cluster. If the client is tied to a node and this node fails, the cluster will stop receiving requests.

If the client can send requests to multiple nodes and handle retries and timeouts, an external load balancer might not be necessary, at least from the Elasticsearch perspective. The Python Elasticsearch library supports this:
https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/config.html#node-pool

By default, it chooses a node from the pool using a `round_robin` approach, and it can also handle retries and timeouts.

Therefore, if a node fails, the request can be retried and sent to a different node.

Internally, the Elasticsearch node that receives the request acts as a load balancer (each node is a coordinator), routing requests to the best nodes that can retrieve results.

**Comment by albertisfu** [comment]
**About Snapshotting.**

Elasticsearch has a [snapshot](https://www.elastic.co/guide/en/elasticsearch/reference/8.8/snapshot-restore.html) built-in feature to schedule, manage and restore snapshot. Full cluster backups snapshots can be generated with no downtime. 

Snapshots can be stored in a S3 bucket, here is the process to setup a snapshot repository:

**Using Kibana:**

- Go to Stack Management/Snapshot and Restore/Repositories and click on "Register Repository"
- Chose a repository name and select AWS S3
- In repository settings set: 
  - Client, unless you need to configure a custom client use `default`.
  - Bucket, the S3 bucket name.
  - Base path, the bucket path to store snapshots, let it blank to use the bucket root.
  - Snapshot compression, recommended to enable it.
  - Other settings can be left as blank to use [default values](https://www.elastic.co/guide/en/elasticsearch/reference/8.8/repository-s3.html#repository-s3-repository).
  - Click on Register.

In order to grant access to the S3 bucket there are two options.

- Create a AWS User and assign the policy recommended [here](https://github.com/freelawproject/courtlistener/issues/2875#issuecomment-1638812784)
  - Set the AWS credentials on every node using the ES keystore.
  - `bin/elasticsearch-keystore add s3.client.default.access_key`
  - `bin/elasticsearch-keystore add s3.client.default.secret_key`

- (Recommended) Create a new Role in IAM and assign the policy recommended [here](https://github.com/freelawproject/courtlistener/issues/2875#issuecomment-1638812784)
  - Assign this Role to every ES node EC2 instance, select the instance, go to Actions/Security/Modify IAM Role.
  - This way ES will use this role to access to the S3 bucket.
  
Verify the repository connection:
![Screenshot 2023-07-17 at 13 13 34](https://github.com/freelawproject/courtlistener/assets/486004/bf570c99-e7ba-41e8-adba-ec2869ff7446)

 It should show a connected status for each node in the cluster.

The repository can also be created using the ES API:

Make a PUT request to: `_snapshot/my_s3_repository`
```
{
  "type": "s3",
  "settings": {
    "bucket": "my-bucket",
    "another_setting": "setting-value"
  }
}
```

Once the repository is created and connected, a snapshot policy should be created:

- Go to Stack Management/Snapshot and Restore/Policies and click on "Create policy":
  -  Assign a policy name
  - The snapshot name (it accepts date [math expressions](https://www.elastic.co/guide/en/elasticsearch/reference/8.8/api-conventions.html#api-date-math-index-names))
  - Select the repository created in the previous step.
  - Frequency, it can be hourly, daily, weekly, monthly or yearly.
  - Time, select the hour and minute to take the snapshot.
- Snapshot settings:
  - Customize the indices and data to include in the snapshot (default, everything.)
- Snapshot retention, set the snapshot expiration, they will be deleted after this time. Snapshots to retain, se the minimum and maximum number of snapshots to retain.
- Create the policy.

Now snapshots should be automatically generated according to the policy and available in the repository.

![Screenshot 2023-07-17 at 14 38 04](https://github.com/freelawproject/courtlistener/assets/486004/e4672237-f5c6-45ab-8fde-b04d3bb3d82e)

**Comment by mlissner** [comment]
I just went through this whole thread, and here's a summary:

 - There are a few open issues remaining, as seen just above this comment. 
 - The only other things are:
     - Autoscaling - This should be fine for now. We can easily scale by hand by upping the number of nodegroups, if needed.
     - Replication - It'd be nice to be able to test settings and things like that in a smaller cluster or locally, but we didn't achieve this, unfortunately.
 
So we're doing pretty great. Now it's really up to these last few tweaks and getting the application code ready.

**Comment by mlissner** [comment]
I'm ready to wrap this up. The cluster is working quite nicely and all remaining issues are optimizations we can do later.
