### ISSUE TITLE
Make party search work from the case name when needed

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3046]
A user [complained](https://x.com/adamdavidlong/status/1694570259150487609) on twitter that:

> Often I try to search based on party name [...] and it just doesn’t work. Like it says “no results”.

This is because our parties field in RECAP only gets populated when we actually have the parties information from the docket itself. If we only have the metadata for the case, a party search fails, even though we know the name of the case. 

We can do better than this. 

All we have to do is:

1. If there are normalized parties in the DB, fantastic, use 'em like we do now.
2. If not, split the case name on `v.`, and put the left and right into the parties field.

Easy! Better!

**Comment by mlissner** [comment]
Just had another unhappy user ask about this. Seems we should put a little more priority on this.

**Comment by albertisfu** [comment]
@mlissner  I want to confirm that I understand what needs to be done here.

The problem is that we don't index parties when normalized parties are not available.

As a result, if a user searches by Party Name or Attorney Name, they might not get any results because those fields are empty, even though we know the two parties involved in the case name.

For instance this query:
```
case_name:Cooper v. Microsoft
party_name:Cooper
```

doesn't return results because Cooper is not indexed under the parties field.
https://www.courtlistener.com/?q=&type=r&order_by=score%20desc&case_name=Cooper%20v.%20Microsoft&party_name=Cooper

The solution would be to split the `case_name` field on "v." during indexing time and store each part as a party in the party field within the `DocketDocument` in ES. This behavior should only be applied if the docket does not have normalized parties to prevent overwriting the whole party data.

Is that correct?

This solution would require re-indexing the DocketDocuments.

**Comment by mlissner** [comment]
Yes, this is all exactly correct. I, too, am thrilled about doing another reindex. :-1:
