### ISSUE TITLE
GHA Runners running out of disk space

### ISSUE THREAD

**Issue by ss108** [freelawproject/courtlistener#3105]
GHA tests workflow is failing in multiple branches when pulling remote images via `docker-compose` with error `no space left on device`

**Comment by mlissner** [comment]
Thanks for filing an issue on this. Lots of discussion on this in the #development channel on Slack today. From what we can tell right now, this seems like an issue related to the [Github Actions cache](https://github.com/freelawproject/courtlistener/actions/caches?query=sort%3Asize-desc).

I cleared it out, and that seems to be helping, but it's back to dozens of GB now.

@cweider  also had [a PR](https://github.com/freelawproject/courtlistener/pull/3106) that makes buildx use Github Actions cache directly instead of a hack we had, so I merged that, and we'll see how that goes.

**Comment by cweider** [comment]
Confirmed #3106 works as a fix!
