### ISSUE TITLE
Error importing opinions.csv into Postgres: unterminated CSV quoted field

### ISSUE THREAD

**Issue by taylorkangbeck** [freelawproject/courtlistener#3152]
I'm trying to import the ~200GB of opinions data downloaded from the S3 bucket into my local Postgres database using a COPY statement in psql:

```
\copy public.search_opinion (id, date_created, date_modified, author_str, per_curiam, joined_by_str,
               type, sha1, page_count, download_url, local_path, plain_text, html,
               html_lawbox, html_columbia, html_anon_2020, xml_harvard,
               html_with_citations, extracted_by_ocr, author_id, cluster_id) FROM 'opinions-2023-08-31.csv' WITH (FORMAT csv, ENCODING utf8, header);
```
and it fails on a particular row with the following error:
```
ERROR:  unterminated CSV quoted field                                                                                                                                                   
CONTEXT:  COPY search_opinion, line 507903410: ""4544092","2020-06-25 17:13:53.973335+00","2022-03-09 10:53:56.197499+00","","f","","010combined","7..."
```
I encountered the same error (on the same item with id `4544092`) trying to import the `opinions-2023-07-31.csv` as well. It looks like there's an extra quote in the id field. 

This may be a problem with the data that needs to be fixed. If I'm just doing something wrong or there's an additional option I should pass to COPY FROM, please let me know!

**Comment by mlissner** [comment]
Hey Taylor, sorry about that. We use the COPY TO command to make the CSV, so it *should* be able to do a round trip like you're attempting. One of our developers recently was working with this data, and I believe he got it working. We should document this better. 

@quevon24 do you think you can help? Do you know the commands you used with your `COPY TO`?

**Comment by taylorkangbeck** [comment]
Quick update on this, it seems this problem was specific to `\copy`, which for some reason fails to handle escape characters within field text bodies. Using a regular `COPY FROM` worked. Using hexedit I found that the html of a particular opinion contained `\.` which was causing the error.

**Comment by taylorkangbeck** [comment]
Closing this issue since this is not a problem with courtlistener

**Comment by mlissner** [comment]
That's very interesting, thank you. Did you consider filing it with postgres?

**Comment by quevon24** [comment]
> Quick update on this, it seems this problem was specific to `\copy`, which for some reason fails to handle escape characters within field text bodies. Using a regular `COPY FROM` worked. Using hexedit I found that the html of a particular opinion contained `\.` which was causing the error.

You are right, the problem with psql's \copy command is that it doesn't know anything about handling csv files (you can't specify the format in the options), and will take `\.` as an EOF although it shouldn't because it's supposed to work only for stdin. This is mentioned in psql documentation: https://www.postgresql.org/docs/current/app-psql.html#APP-PSQL-META-COMMANDS-COPY

Also for large amounts of data such as dockets, clusters and opinions it is recommended to use SQL COPY instead of psql's \copy.

The tests I originally ran were directly with COPY using dbeaver so I didn't run into that problem, plus I only tested a small portion of the opinions file because the file is huge 😵‍💫, but thanks to this we can add it to the documentation.
