### ISSUE TITLE
Staging Env Discussion 

### ISSUE THREAD

**Issue by ss108** [freelawproject/courtlistener#3183]
@mlissner I wanted to raise the issue of a staging or beta environment for Courtlistener

Courtlistener is sufficiently complicated, and has a sufficient number of different things being worked on by different developers, that it should have a staging environment. 

This originally came up in the context of https://github.com/freelawproject/courtlistener/issues/3134 where I mentioned it to @cweider and he agreed, but said there wasn't a lot of appetite for it when he raised it previously. There should be appetite for it! 

For that Docker ticket, I have a good chunk of the work done, but there is no mechanism to test whether the entire flow, including the relevant GitHub actions, would work. Ideally, there would be a staging environment that mirrors the production workflow, including the Kubernetes part. The only difference would be pointing to a central test db and some other things that should mostly be a matter of changing config variables: https://12factor.net/dev-prod-parity 

The lack of a staging environment makes it difficult to do non-infra tickets as well; for example, https://github.com/freelawproject/courtlistener/issues/607 

I have the code done, but am stymied by env issues when it comes to verifying it all works, including the need to add stuff to `make_dev_data`, and the Solr issue. If there was a centralized staging env, it would be possible to just maintain a prepopulated DB and solve things such as Solr issue at that choke-point, instead of having individual devs slowed down by that kind of stuff. 

Plus, it would facilitate proper testing of UI changes by deploying them.

The proposal here is that, prior to completing #3134, I do another ticket to set up a proper staging environment.

**Comment by mlissner** [comment]
I'm not an expert here, so please tell me where I'm wrong, but I've always been dubious of the value of a staging environment at our scale, and I've always thought that a blue/green system would be better. The three things that get me down about staging env's are:

1. Cost. I assume we'd want a mirror of our DB, k8s set up, etc. That's pretty expensive.
2. Work. If you tell me every deployment is going to take more work, I'm sad. :(
3. I'm not sure it makes a huge difference most of the time.

Even for this example that you've giving, @ss108, #3134, I don't see it as being super necessary. For example, let's say you created a really bad docker image in your PR that failed in prod. What would happen is that the automatic deployment would fail and we'd have to revert, but the site would stay up. That's not so bad, and we don't do *that* much infrastructure work, so it feels like an OK compromise. 

The other example is UI changes. I agree that they can be hard to test in prod, BUT this is why we feature flags. Instead of just releasing a new page or feature, we can put all that functionality behind a flag, try it out in prod, and only enable it once we're happy. Once again, that's not too bad! 

---

As for blue/green deployments, what I like about them vs staging is that you're guaranteed to have the systems in parity, because they're always swapping places. It also makes reverting instant, at the DNS level, which is really fun. So in theory, I like it. But in practice, I'm not sure how to actually set it up, so we don't have it yet, I'm afraid. 

Tell me where I'm wrong, and please push me to be right. I think it's a balance thing, but I've never lived in a world with staging, so what do I know???

**Comment by mlissner** [comment]
Thoughtworks is an organization that analyzes technologies and provides guidance on best practices. I tend to agree with most of their analysis and I happened to be on their website today. Here's [their analysis](https://www.thoughtworks.com/radar/techniques/enterprise-wide-integration-test-environments) of what they call "Enterprise-wide integration test environments":

> ### Hold (Proceed with caution)
> When the enterprise-wide quarterly or monthly releases were considered best practice, it was necessary to maintain a complete environment for performing testing cycles prior to deployment to production. These enterprise-wide integration test environments (often referred to as SIT or Staging) are a common bottleneck for continuous delivery today. The environments themselves are fragile and expensive to maintain, often with components that need manual configuration by a separate environment management team. Testing in the staging environment provides unreliable and slow feedback, and testing effort is duplicated with what can be performed on components in isolation. We recommend that organizations incrementally create an independent path to production for key components. Important techniques include [contract testing](https://www.thoughtworks.com/radar/techniques/consumer-driven-contract-testing), [decoupling deployment from release](https://www.thoughtworks.com/radar/techniques/decoupling-deployment-from-release), [focus on mean time to recovery](https://www.thoughtworks.com/radar/techniques/focus-on-mean-time-to-recovery) and [testing in production](https://www.thoughtworks.com/radar/techniques/qa-in-production).

**Comment by ss108** [comment]
@mlissner Sorry for the late reply.

Chad and I talked further about this the other day, and the upshot of his perspective is that, while staging is good, many of the pain-points we are experiencing with development can be addressed separately and/or by means other than creation of a staging environment. 

For the immediate issues:

For my RECAP doc ticket specifically, I will probably put logic in the opinion endpoint to bypass Solr locally. I can do that in a separate branch, if you think that's better (it probably is)

For the Docker entrypoint thing, we can go with just deploying it to prod based on the fact that it works when we run `docker compose`. 

Since I have only ever used staging environments everywhere I have worked, I am actually not well-equipped to advocate for them over other workflows :thinking: 

That being said, from my understanding, I don't think staging is really all that different or any more work than a Blue/Green deployment setup. In fact, having a staging environment can be thought of as doing Blue/Green Deployment where your traffic split is always 100-0, if that makes sense. 

To be clear, right now, 100% of traffic gets every new prod deployment, right?

But to address a couple of your points for the sake of completeness

I think concern #2 that you expressed is def not the case--it should be at most the same amount of work. In the end, all you have to do to deploy is merge branches, etc. Staging would allow you to test stuff live and in conjunction with one another, but you don't *have* to, if you think something is good to go, too minimal, w/e

Regarding #1, that's an unknown, but it shouldn't be as costly to run as prod. You don't need same size/specs for anything, and it could even use the "prod" versions of the external services as much as reasonable.

**Comment by mlissner** [comment]
Thanks for these thoughts. It's helpful to think about, and yeah, I think Blue/Green is pretty similar. We could do that just for the Python parts or the microservices parts, I guess. 

I have no idea how, but if we connect both Blue and Green application code to the prod DB and Elastic instances, that makes life a lot cheaper and easier. There's definitely improvements we could make here. I think if there were a concrete plan of attack, we could start refining it and mulling it until it was something we liked.

But in any case, for the moment, I agree, your solutions sound good. For the opinions bypass, I started a new issue and, yes, let's do it in a separate PR: https://github.com/freelawproject/courtlistener/issues/3192

**Comment by ss108** [comment]
Sounds good!

**Comment by mlissner** [comment]
I think we made progress here and the conversation seems to have stopped, so closing just for tidiness, but if we need more improvements, I'm always happy to discuss such things. 

Thanks you Samier!
