### ISSUE TITLE
Make it easy to make automatic monthly donations

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#325]
There should be an option here: https://www.courtlistener.com/donate/ something like this:
|_| Make the same contribution each month.

So that people could sign up to donate $10/mo $20/mo whatever. 

It'd be preferable if those clicking this option could get a choice, like "Process my donations on the __ of each month" and then let people pick whatever date they get paid, but then we've got to have this day in their user profile in the database and we've (probably?) got to somehow store their payment method enough to be able to repeat it each month.

Might be a little simpler to just tell people that click that option that their payment method will be processed on the 4th of the month. (Reasoning: Most people are paid at end or beginning of month and even when the first of the month falls on weekend, there's bound to be a weekday by the 4th, even considering that New Years Day and the occasional Labor Day will/may be on the 1st and hence a bank holiday.) But this may still require some storage of payment methods.

Note, if resolution of this issue requires storage of payment info, such as credit card info, then that's another ball of wax entirely and even implicates some legal requirements. If so, then this should probably be closed wontfix for now.

**Comment by mlissner** [comment]
Stripe has a way of doing this, as does PayPal and I think even Dwolla. The problem is that each has *its own* way of doing this. 

Dwolla increasingly seems like a failed project, so I think we can safely ditch it. If we did that then we'd only have to figure out PayPal and Stripe (both of these make it possible to do monthly payments without storing payment info).

The annoying thing is that payments is fraught with difficulty, and monthly payments are especially tricky because you need a way for people to cancel the payments, update their credit cards, etc. Lots more tricky edge cases.

**Comment by mlissner** [comment]
Yeah, so doing this sucks, as might be expected. So far I've only really looked at Stripe, and I think it's the only service I'm going to do this for. We also accept PayPal, but setting it up just for regular billing is painful, so I expect doing monthly will only be worse. 

So, for Stripe, they've got decent docs: https://stripe.com/docs/billing/quickstart

The big picture is that you:
1. Create a product ("Monthly donation"). We do this once, and could probably even do it via an Ansible script if we're feeling brave. 

1. Create a plan for that product. This is how you schedule it monthly. The plan should have a cost of 1¢, and then you set the quantity to whatever the person wants to donate every month.

1. Create a customer. This is how stripe represents somebody.

1. Associate the customer with the plan at a given quantity (5,000 of the 1¢ plan: $50/month).

That doesn't require *too* much work. But the other two pieces I haven't yet figured out are:

1. There are undoubtedly webhooks we need to listen to. We already listen to a few. Do we need more?
1. What sorts of forms and tweaks do we need on the site to make this possible? How little can we get away with? The simplest thing I can imagine would be to just append every email with a "Cancel this subscription" link, and then do similar in the "donations" tab of people's profile. Better would be an *edit this subscription* page, but that sound harder. Bleh.

I'd love to bang this one out because it's a blocker for #845, which in turn is a blocker for announcing the docket alerts properly.

**Comment by mlissner** [comment]
OK, I think, more than three years after this issue was filed, this is now resolved:

https://www.courtlistener.com/donate/

I could use some testers because this area of the code is very tricky. Can you break it?

I ended up doing this in the easiest way possible, which means that:

1. We don't use stripe's concept of subscriptions and instead handle it ourselves. As is explained on our new help page about donations:

    https://www.courtlistener.com/help/donations/

    We will bill you on the day that you donate. This isn't configurable as Brian had asked in the initial post, but I didn't see other non-profits doing that either. The one tricky bit here is that if you donate on the 29th, 30th, or 31st of the month, we're just going to bill you on the 28th from then on.

2. We don't accept paypal for this. Paypal is hard and annoying. Stripe was hard enough.

What we do do is:

 - Collect your payment info client-side, and send it to Stripe. Stripe gives us back a token for it, and we use that to create a "customer" in stripe. This way no card data ever hits our servers and we just save the Stripe customer ID.

 - Every day, we run a cron job that looks for monthly donors on that day. Those donors get charged via stripe and we send them an email to say they were charged. We send ourselves an email saying how many people were charged that day and what the grand total was.

 - Recurring donations can be paused or resumed in a user's profile! This is a nice trick that I'm pretty happy with.

And there's some other trickiness about pre-filling forms for logged in users and things like that! If you have a moment, I'd greatly appreciate your giving it a shot.
