### ISSUE TITLE
Various front end issues in the new RECAP search

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3257]
Just saw a result like this: 

![image](https://github.com/freelawproject/courtlistener/assets/236970/b2e6083d-2739-4fcd-82da-76de9f44a10f)

We should use a `...` kind of thing to only show the first couple of lines of any long description. I think we do this in the current search page for some of the fields, but I forget which.

**Comment by mlissner** [comment]
That one isn't even the worst. Here's the query I'm using: 

https://www.courtlistener.com/?q=&type=r&order_by=score%20desc&available_only=on&description=Kathleen

It seems like some of the full text snippets are extreeeeeeemely long too. Not sure why. They go on for page after page.

**Comment by mlissner** [comment]
Another issue, highlighting in the court field is wonky: 

![image](https://github.com/freelawproject/courtlistener/assets/236970/e4a6652a-e434-4a66-8eaf-745ca4172845)

![image](https://github.com/freelawproject/courtlistener/assets/236970/197d7b79-92b4-4619-90c4-5d4c6b0c41b3)

**Comment by mlissner** [comment]
Items without PDFs (or docket entries) seem to think they have PDFs. Note the box is checked in this query, but we get back dockets that don't have any docket entries at all: 

![image](https://github.com/freelawproject/courtlistener/assets/236970/f7b09776-0441-46f5-9161-5fb7c6054bc2)

https://www.courtlistener.com/?q=&type=r&order_by=score%20desc&available_only=on&court=ksd

**Comment by mlissner** [comment]
The HTML bold tag in the text of [this document](https://www.courtlistener.com/docket/4246168/10/united-states-v-limoz/) makes the remainder of the page bold:

![image](https://github.com/freelawproject/courtlistener/assets/236970/6b95f2f2-7318-41e4-93ff-e5a94cba2c69)

Link: https://www.courtlistener.com/?type=r&q=id%3A4337497

**Comment by mlissner** [comment]
Another fun one. I'm sitting here with my son and we decided to search his name. Turns out there is 1 case and 1 docket entry, but it doesn't show any. It's weird: 

![image](https://github.com/freelawproject/courtlistener/assets/236970/d55a7e4d-bf7a-486c-b4f9-0cf05971a040)

https://www.courtlistener.com/?q=kelvin%20lissner&type=r&order_by=score%20desc

**Comment by mlissner** [comment]
Curious white space between parties and attorneys:

![image](https://github.com/freelawproject/courtlistener/assets/236970/bcc9a3e9-4399-4310-b0c1-4ed1c77138e8)

https://www.courtlistener.com/?q=copyright%20%22memory%22&type=r&order_by=score%20desc&case_name=-%22memory%22

**Comment by mlissner** [comment]
When filter just to a single docket, it works nicely, but when you get to the bottom of all the filings, there's no indicator that there might be more. I think we concluded it wasn't useful to show any more, but maybe we should have a button there that says, "XYZ total filings. See full docket for details" or something like that (maybe it's hard to get the count in the button?).

Right now it looks like this, which is kind of wrong: 

![image](https://github.com/freelawproject/courtlistener/assets/236970/baff5f18-e896-4b13-bf5b-d8f7c86a8259)


https://www.courtlistener.com/?q=docket_id%3A7180514&type=r&order_by=score%20desc

**Comment by ERosendo** [comment]
@mlissner I've been checking the issue where the docket/docket entry wasn't appearing in the search.

I found that the docket entry matching the search terms is [Document #21-The Bon-Ton Stores, Inc.](https://www.courtlistener.com/docket/6292528/21/the-bon-ton-stores-inc/) and the issue is related to the highlighter type we're using.

The current implementation of the RECAP search uses the Plain highlighter, this highlighter works by re-analyzing the text from each field to identify terms to highlight and where those terms are located in the text. The process creates an in-memory index for every document and field at query time. Plain highlighting for large texts may require a substantial amount of time and memory. To protect against this, the maximum number of text characters that will be analyzed has been limited to `1_000_000` characters, and when the number of characters exceeds this limit an error is returned. 

[Document #21](https://www.courtlistener.com/docket/6292528/21/the-bon-ton-stores-inc/) has 1799 pages and more than `1_000_000` characters, so the highlighter is failing to show the results properly. We have a few options to avoid this error:

### 1. Use the `max_analyzed_offset` parameter in the Highlighting query

if this setting is set to a non-negative value, the highlighting stops at this defined maximum limit, and the rest of the text is not processed, thus not highlighted and no error is returned. The [max_analyzed_offset](https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html#max-analyzed-offset) query setting does not override the [index.highlight.max_analyzed_offset](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-max-analyzed-offset) which prevails when it’s set to lower value than the query setting. 

### 2. Use a different highlighter implementation
    
The Plain Highlighter can be slow for large fields, for such use cases, two other implementations come in handy: `Postings Highlighter` and `Fast Vector Highlighter`. Both are faster than the Plain Highlighter on large fields, but both require additional data to be stored in the index—data on which their speed is based. 

**2.1 Postings Highlighter**

In order to use the Highlighter, we need to set `index_options` to `offsets` for the highlighted fields, which will store each term’s location (position and offset) in the index.  Offsets indicate the exact position of a certain term in the text, and with this information, the Postings Highlighter can identify which terms to highlight without having to re-analyze the text.

Internally, the Postings Highlighter breaks the field into sentences (which then become fragments) and treats those sentences as separate documents. The fragments will always be sentences unless you set `number_of_fragments` to 0, in which case the whole field is treated as one fragment, and this approach will ignore the `fragment_size` option if we set it(this setting becomes irrelevant because ES is breaking the text down into sentences while indexing).

**2.2 Fast Vector Highlighter**
  
In order to use the Highlighter, we need to set `term_vector` to `with_positions_offsets ` for the highlighted fields. 

Compared to the Postings Highlighter, the Fast Vector Highlighter takes up more space and requires more computation during indexing, because both need positions and offsets, but only the Fast Vector Highlighter has to compute the term vectors themselves, which are disabled by default. This approach also offers better phrase highlighting.

If the Fast Vector Highlighter matches many phrases, it could consume a lot of memory. By default, only the 256 first matches in a document are used. We can change this amount using the `phrase_limit` parameter.

---

### Final thoughts 

- By setting the `max_analyzed_offset` parameter, we can fix the issue with the matching docket entry by stopping the highlighting process at this defined maximum limit and this option doesn't require re-indexing. However, it won't generate highlights for long documents.
- Both implementations from option 2 are faster than the plain highlighter, but they require re-indexing and use disk space. Here's an article that compares the speed and index size of different ES highlighting methods: https://www.agilytic.be/blog/tech-talk-elasticsearch-highlighting-kibana
 
Let me know what you think.

**Comment by mlissner** [comment]
On the highlighting, we discussed it and it feels like a small-medium-large thing. We are currently using the 'small' size, meaning the plain highlighter. The medium size, "Postings highlighter" is better, and fixes the problem while making the index somewhat larger, but requires indexing and will only make things a bit faster. The large size, "Fast Vector Highlighter" makes things faster but makes the index larger still. 

For now we are going to do the simple thing and implement the `max_analyzed_offset` parameter at its highest possible value, 999,999. When we do opinions, we'll test the different highlighters against about a million items and see how that goes. We'll do that in: https://github.com/freelawproject/courtlistener/issues/3300

**Comment by mlissner** [comment]
Hm, it seems like documents aren't being shown properly now. I'm guessing this is because I have the "Only show PDFs" option selected: 

![image](https://github.com/freelawproject/courtlistener/assets/236970/779ff9c0-c5f5-4714-810f-ad773c501066)

https://www.courtlistener.com/?type=r&order_by=score+desc&available_only=on&description=Kathleen

**Comment by mlissner** [comment]
I think this is all resolved. For now. :)

For future readers, not that the hidden comments are each issues we've resolved.
