### ISSUE TITLE
Random case doesn't show entries but should be indexed

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3325]
This is a case I often use for testing things, and I'm concerned it doesn't show any entries. My guess is that it failed to index properly for the usual timeout/connection/conflict error kinds of reasons. If so, that's a bummer: 

![image](https://github.com/freelawproject/courtlistener/assets/236970/1bbf4b3a-6e2c-4cf2-a8d8-f082ae4cbf78)

I wonder if the solution is going to be to re-index everything. Boy, I hope not, but it's beginning to feel like we should if I'm hitting things like this.

**Comment by mlissner** [comment]
This shows up now. Great. Closing.

**Comment by mlissner** [comment]
Actually, I take that back. It only shows one docket entry now: 

https://www.courtlistener.com/?type=r&q=docket_id%3A4214664

![image](https://github.com/freelawproject/courtlistener/assets/236970/c8728337-3e42-470d-8110-63b40fd04b0e)

**Comment by albertisfu** [comment]
I checked this case to confirm that there was nothing unusual preventing the indexing of child documents in this docket.

Using data from the dev database, I was able to index RECAP Documents in this docket by triggering a document update.
Indexing the entire docket using the `cl_index_parent_and_child_docs` command also indexed all the documents in the case.

![Screenshot 2023-12-26 at 18 13 39](https://github.com/freelawproject/courtlistener/assets/486004/f5d942ef-9575-4778-9a88-2c4d96a7877b)

Going forward, only new RECAP Documents and those that have changed in one of their tracked fields will indexed by signals.

Therefore, I think this issue is related to #3407 and #3406, where we will need to go through the indexing errors or slowly index the missing content.

**Comment by mlissner** [comment]
Works for me. Do you have the command for me to try?

**Comment by albertisfu** [comment]
Yeah, I had to temporarily tweak the command `cl.search.management.commands.cl_index_parent_and_child_docs.py` to be like this, so it only index the provided docket ID:

![Screenshot 2023-12-26 at 18 43 41](https://github.com/freelawproject/courtlistener/assets/486004/84667c81-b7f9-45cd-872d-e92369ca968b)

```
queryset = (
                    Docket.objects.filter(pk__in=[4214664])
                    .order_by("pk")
                    .values_list("pk", flat=True)
                )
```
And then run the command as:

`docker exec -it cl-django python /opt/courtlistener/manage.py cl_index_parent_and_child_docs --search-type r --chunk-size 1`

Let me know if I should update the command so we can include a `--parent_id` argument to the indexing command so we can do this process more easily.

**Comment by mlissner** [comment]
Eh, it's OK. We'll get this one soon, and we can close this. Thanks for investigating.
