### ISSUE TITLE
Use distinct Sentry DSN for Juriscraper scripts

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3399]
I think it should be possible to use a different Sentry DSN for scraping tasks. We should do that, because that way, we can have certain people get and monitor those alerts, while others can ignore them.

**Comment by flooie** [comment]
This is a great idea.  I looked briefly at a way to do this.

**Comment by flooie** [comment]
Is the goal to reduce clutter on the Main sentry SDK or enable finer grained review of errors? 

Either way we can implement a `before_send` hook in the sentry sdk.

I tested this 

```
env = environ.FileAwareEnv()
SENTRY_DSN = env("SENTRY_DSN", default="")
SENTRY_REPORT_URI = env("SENTRY_REPORT_URI", default="")
JURISCRAPER_DSN = env("JURISCRAPER_DSN", default="")

# IA's library logs a lot of errors, which get sent to sentry unnecessarily
ignore_logger("internetarchive.session")
ignore_logger("internetarchive.item")

def before_send(event, hint):
    exception = event.get("exception", {}).get("values", [{}])[0]
    if "cl/scrapers/" in exception['stacktrace']['frames'][0]['filename']:
        event["dsn"] = JURISCRAPER_DSN
        event.setdefault("tags", {})["juriscraper"] = exception['stacktrace']['frames'][0]['vars']['options']['court_id']
    return event

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            CeleryIntegration(),
            DjangoIntegration(),
            RedisIntegration(),
        ],
        ignore_errors=[KeyboardInterrupt],
        before_send=before_send,
    )
```

Because I can't setup a new project I ran a local test to the courtlistener-dev sentry project - and tagged errors with the court_id.  I think this would be an effective way to monitor which court is actually throwing the error - especially when multiple courts are throwing 404s.  

Either way, adding a new project and DSN would let us filter these jurscraper scraping issues nicely

**Comment by mlissner** [comment]
Where did you find the beforeSend approach? It feels a little clunky and they describe it as a last chance to tweak things. 

I thought because of monorepos there would be a better way to do this, but I haven't been able to find anything. I guess another approach is to just use [ownership rules](https://docs.sentry.io/product/issues/ownership-rules/).

We could also try asking their customer service. They've been helpful in the past.

**Comment by flooie** [comment]
I think this was a good idea - but I think we came decided it wasn't possible.  Closing this for now - or until we move juriscraper to its own microservice.

**Comment by mlissner** [comment]
Agreed, but let's start using ownership rules as issues arise in Sentry, so that things get assigned to you or @grossir.

**Comment by grossir** [comment]
I was checking this issue because we got some events from the recently merged NY Misc. scrapers directed to an archived [Sentry issue](https://freelawproject.sentry.io/issues/2927971596/events/?project=5257254&referrer=issue-stream&statsPeriod=24h&stream_index=0), that mixes all the ["Could not parse citation"]((https://github.com/freelawproject/courtlistener/blob/main/cl/scrapers/management/commands/cl_scrape_opinions.py#L56)) errors from all scrapers

This grouping is not desirable, since the problem should be analyzed by each scraper.

I was able to separate the errors by each `court.id` by overriding Sentry's [fingerprinting rules](https://docs.sentry.io/platforms/python/usage/sdk-fingerprinting/?original_referrer=https%3A%2F%2Fwww.google.com%2F) using the beforeSend hook.

The new groups can be seen on [courtlistener-dev Sentry issues](https://freelawproject.sentry.io/issues/?project=5620212&referrer=sidebar&statsPeriod=14d). On the bottom of each issue page, Sentry reports the `Event grouping information` which has changed to `Custom fingerprint` from `Grouped by message`

This would be extensible for any `logger.error` call by passing a `fingerprint` variable to the `extra` argument, which is essentially an group ID. In order to separate each error by each scrapers, it should simply be something like: `f"{logged_error}_{court_id}"`

Some working code changes can be seen here:

https://github.com/freelawproject/courtlistener/compare/main...grossir:courtlistener:make_citation_errors_court_specific?expand=1

**Comment by mlissner** [comment]
Cool. Works for me. Let's make sure we teach everybody how to do this once it's in place, so others can improve their Sentry stuff too. Maybe even put it on our dev wiki?

**Comment by grossir** [comment]
I will refine this issue further, but limiting the analysis and examples to code called by cl_scrape_opinions.py .
This is important so as to know where to put the court_id metadata necessary to fingerprint events

I have found 2 kinds of "errors" in the code that end up on Sentry. 
 
1. logger.error()
2. Uncaught exceptions

## logger.error
These could be data quality issues, that do not abort the scraper or rollback the saving of the scraped opinion 
Their purpose is to warn the developers that there is something missing
We should analyze if we really want to continue saving a record even if one of these fields are missing:

- [No citations were found](https://github.com/freelawproject/courtlistener/blob/main/cl/scrapers/management/commands/cl_scrape_opinions.py#L55)
- 3 loggers when [child court cannot be found from string](https://github.com/freelawproject/courtlistener/blob/main/cl/scrapers/utils.py#L51) for different reasons 
- When doctor extraction is not supported for a [certain extension](https://github.com/freelawproject/courtlistener/blob/main/cl/scrapers/tasks.py#L171)
- [When the opinion could not be saved to the DB](https://github.com/freelawproject/courtlistener/blob/main/cl/scrapers/tasks.py#L191). This warning is in a `print` statement, and it shouldn't be

## Uncaught exceptions
All of the uncaugh exceptions inside `parse_and_scrape_site` are reported to Sentry using  [`capture_exception`](https://github.com/freelawproject/courtlistener/blob/main/cl/scrapers/management/commands/cl_scrape_opinions.py#L380)

---

The grouping may be random in both of these kinds of errors, although less so on logger.error calls when the message includes detailed data. These groupings can be forced by fingerprinting as described on a previous comment

After testing the fingerprinting, I found the following:

- Doing `f"{logged_error} - {court_id}"` instead of `f"{court_id} - {logged_error}"` breaks the fingerprinting
- Passing [extra_data](https://docs.sentry.io/product/sentry-basics/integrate-backend/capturing-errors/#enriching-your-event-data) as keyword argument to `sentry_sdk.capture_exception` makes the event to not be captured
- Passing this fingerprint list `[mod, '{{ default }}']` splits groups of errors by scraper. Doing `['{{ default }}', mod]` groups errors from different scrapers

I tested the groupins using the following code from a Django Shell `python manage.py shell`
```
from sentry_sdk import capture_exception
from cl.search.models import Citation
from requests.exceptions import ConnectionError
import logging
logger = logging.getLogger(__name__)
import time

class TestSentry():
    court_modules = [
        "juriscraper.opinions.united_states.federal_appellate.cadc_pi",
        "juriscraper.opinions.united_states.federal_appellate.cadc",        
        "juriscraper.opinions.united_states.state.nycivct",
        "juriscraper.opinions.united_states.state.nysupct",
    ]
    court_urls = [
        "https://www.cadc.uscourts.gov/internet/orders.nsf",
        "https://www.cadc.uscourts.gov/internet/opinions.nsf/uscadcopinions.xml",
        "https://nycourts.gov/reporter/slipidx/miscolo.shtml",
        "https://nycourts.gov/reporter/slipidx/miscolo.shtml",
    ]
    
    def test_raised_exceptions(self):
        for index, mod in enumerate(self.court_modules):
            fingerprint = [mod, '{{ default }}']

            # Raises Django IntegrityError, which specific
            try:
                Citation(volume=str(index+1), reporter="Misc 3d", page="1215(A)").save()
            except Exception as e:
                capture_exception(e, fingerprint=fingerprint)
            
            try:
                url = self.court_urls[index]
                raise ConnectionError(f"HTTPConnectionPool(host='{url}', port=80): Max retries exceeded with url:")
            except Exception as e:
                capture_exception(e, fingerprint=fingerprint)

            # Type Error
            try:
                mod + 1
            except Exception as e:
                capture_exception(e, fingerprint=fingerprint)

            time.sleep(10)

    def test_error_loggers(self):
        for index, mod in enumerate(self.court_modules):
            court_id = mod.split(".")[-1].split("_")[0]
            logger.error("Could not parse citation", extra={"fingerprint": f"{court_id}-citation-not-found"})
            time.sleep(2)
            logger.error("Could not get child court id from name %s", court_id, extra={"fingerprint": f"{court_id}-child-court-not-found"})
            time.sleep(2)
            logger.error("Court object does not exist for id '%s'",court_id, extra={"fingerprint": f"{court_id}-found-child-court-has-no-parent"})
            time.sleep(2)
            logger.error("Child court found from name '%s' with id '%s' has parent court id different from expected. Expected: '%s' Found: '%s'", court_id, court_id, court_id, court_id, extra={"fingerprint": f"{court_id}-found-child-court-parent-different-than-expected"})
            
            time.sleep(10)
```

**Comment by grossir** [comment]
Here is the wiki 
https://github.com/freelawproject/courtlistener/wiki/Customizing-Sentry-issues-via-fingerprinting
