### ISSUE TITLE
Add short case names to improve citator

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#340]
Cases like "Larry, Curly, & Moe v. Acme Inc." have a "short name" that they are referred to after they are cited the first time. Subsequent references would probably just be "Larry, at 112".

 The way to construct a short name follows some definable rules that we can know in advance and so we could generate these and add them to the database.

Then, we could modify the citator to identify these short names in documents and then it would do its lookup against these short names.

There will still be some hard cases where we have to punt, but it's one technique that could bring us much closer to success.

This would be supplemented by our reverse lookup technique. When two or more cases have the short name "Larry" we retrieve each full name and then search the full text of the document that was the source of the citation for a match. Hopefully there's only one. Additionally, an initial search of the source document should give us some idea of what the short cite is a cite of, so that should also yield many unique matches.

**Comment by mlissner** [comment]
The most basic form of this is DONE and in the dev version. It actually became part of juriscraper, since it's the thing that's going to be generating and serving short case names most of the time. Today, I added it to the new DB schema, and as we do the conversion short names will be added automatically.
