### ISSUE TITLE
Develop sweep indexer to clean up missed items

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3406]
I'm entirely unsure what the best architecture of this will be, but I think we need a daemon that continually pulls data from the database and adds it to Elastic. The idea is that there will always be content that doesn't make it into Elastic properly, and a well-designed daemon could come around cleaning up messes.

I think the best approach will be for this to slowly sweep across all of our data sets, with a rate that allows it to start over every few months. I think if the daemon is only concerned about content being **in** Elastic, not about whether content is **fully up to date**, it could be a lot faster. It could just query each item, and then add content that's missing.

This will need to be work for every index. Probably having them go in parallel is fine, though I could see a design that works serially as well. 

This will need to be resumable too, so that if/when it crashes, it can easily pick up wherever it left off.

**Comment by mlissner** [comment]
Moving @albertisfu's comment from #3541 over here: 

> Considering that we cannot avoid some errors during indexing due to network issues, race conditions, etc., even after retries. I'm considering the idea of keeping track of the documents being indexed, updated, or removed. This way, if the indexing task fails, the sweep indexer could prioritize those documents, ensuring the changes are reflected in the index more quickly. I was thinking of a queue in Redis. When a document is triggered for indexing, updating, or removal, we add it to the queue. Once the action is completed successfully, we remove it from the queue. Items in the queue older than a certain threshold would be considered failed. We could then process these items every day or every few hours to ensure the data changes are up to date in the index. In this way, even if we still encounter a few ConflictErrors or other types of errors, we can be confident that the data will be updated soon. What do you think?

**Comment by mlissner** [comment]
So the idea is that whenever we start indexing something in Elastic, we begin by adding its ID to a queue, and then when we finish indexing successfully, we remove it? And any item that's in the queue for more than a few hours is considered failed, and we retry it? 

On the surface, that seems like a good idea to me, but it feels a lot like re-inventing Celery retries, doesn't it? Maybe I'm misunderstanding your design?

**Comment by albertisfu** [comment]
> On the surface, that seems like a good idea to me, but it feels a lot like re-inventing Celery retries, doesn't it?

Yeah it makes sense.

I think there are some problems with retries:

- Sometimes the retries we have are not sufficient for tasks to succeed, especially in the case of network or cluster issues.
- Tasks only retry on exceptions that we have identified and set the task to retry on. If a task fails due to an error we haven't seen before, but the root failure is a transient problem like the one we recently saw in #3818, the task won't be retried.
I think eventually we won't see more of those rare cases after we handled all of them. Also they seem pretty rare.

So as an alternative, we could:

- Set a higher number of retries and/or establish a better retry policy (to all our ES tasks) that spreads them out over time to ensure tasks always succeed. This policy should include an exponential backoff that continues retrying tasks a few hours after the first attempt to ensure that if the problem is related to network issues or a cluster overload/failure, these tasks have a good chance to succeed.
- For exceptions that we don't know and can be retried, since they are rare, we could just check them when they happen, analyze them, and incorporate them into the retry policy if required.
- If we don't apply the better retry policy to `ConflictError` in order to continue monitoring data integrity issues, there could be some rare cases where we might miss data.

**Comment by mlissner** [comment]
Great. I think just using the celery retry mechanism should be simpler than trying to develop our own (though we'll have to catch 'em all when it comes to exceptions). Want to see what tweaks we need for that?

**Comment by albertisfu** [comment]
Sure! So you want me to check how we can retry tasks for all possible exceptions, including those not related to transient issues? I think those kind of errors could be rare but can still occur, such as sending incorrect data or something similar.

**Comment by albertisfu** [comment]
I'll start working on this one. Here are some notes about what we talked about today:

- We're going to increase retries only on indexing tasks and give them a better retry policy so they can succeed after a transient issue related to the network or the cluster.
- In case we encounter a new exception that is not included in retries, we'll get a new event on Sentry, evaluate it, and add it to retries if required. If there are many failed events related to an exception, we could re-process them by taking advantage of Sentry's API. We can retrieve the related instance IDs and then use the indexing command to update the failed documents after the issue is resolved.
- To improve the performance of the sweep indexer, we should index each document type serially, e.g: first index all the `Dockets`, then all the `RECAPDocuments`. This way, we could use bulk indexing, instead of the approach followed in the first indexing where for each docket in the database, we retrieve their filings to index first the docket and then their filings. We already have the task that handles this process: **`index_parent_or_child_docs`**, which we used when indexing new dockets and filings added during the last re-index.

> I think if the daemon is only concerned about content being in Elastic, not about whether content is fully up to date, it could be a lot faster. It could just query each item, and then add content that's missing.

Yeah, this makes sense. However, for the re-index we need to perform for RECAP, where we need to re-index everything to fix the phrase search (to avoid removing duplicates), we need to re-index every docket and RECAPDocument.

We could add this as an option like "action": "all" or "missing". **`all`** will re-index everything again, pulling the most recent data from the database. If the **`missing`** option is enabled, the indexer will check if the document already exists in ES, omitting those that already exist.

> This will need to be work for every index. Probably having them go in parallel is fine, though I could see a design that works serially as well.

There are some differences regarding this one. In the serial approach we just need to save the state of the index using a key for the document model being indexed and the current document PK. That way, we can do every document from every index every few months, for instance, starting from Dockets, RECAPDocuments, OpinionCluster, Opinion, Audio, etc. However, considering that the other indices than RECAP are relatively small, they'll need to wait a few months to get the sweep indexer going through them again.

The parallel approach, on the other hand, if we set one daemon for every index, we'll need to set a kind of rate for each index. Otherwise, we'll be running the indexer again and again many times unnecessarily for small indices, for instance, Oral Arguments, which only takes a few hours. So, it'll be better to run it every few days.

Let me know what do you think.

**Comment by mlissner** [comment]
> We could add this as an option like "action": "all" or "missing".

Makes sense to me.

It seems best to me to just do the reindexes in serial. I'm not sure what you mean about keeping the the "current document PK" in a key though. Can you explain that to me a bit more so I'm sure we're on the same page?

**Comment by albertisfu** [comment]
> It seems best to me to just do the reindexes in serial.

Perfect, I agree.

> I'm not sure what you mean about keeping the the "current document PK" in a key though. Can you explain that to me a bit more so I'm sure we're on the same page?

Sure, I'm referring to a mechanism to save the state of the indexer so that in case it crashes, it can restart its work from where it left was. Considering the indexer will go through documents serially, we need to know two things: the document type being indexed and the last document PK indexed, and store them in Redis. For instance, if the document type being indexed is `RECAPDocument` and the last PK indexed is 450000, if it crashes, when restarting the indexer, it will continue from that RECAPDocument.

**Comment by mlissner** [comment]
Got it. Yeah, let's definitely do that, maybe cache it every 1000 items or something?

**Comment by albertisfu** [comment]
Sure, every 1000 items seems fine that's the number we're currently using on `cl_index_parent_and_child_docs`. 
I'll start working on this then.

**Comment by mlissner** [comment]
This is running. I think we can call it done. Thank you!
