### ISSUE TITLE
Set up end of year fundraisers

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3416]
This one will take some teamwork. 

A couple things we do every year:

 - [x] @mlissner: Write the annual letter saying what we've done and what we've got coming up.

 - [x] @mlissner: Tweak the annual letter to work as a popup for RECAP users.

 - [x] @ERosendo: Pop up a banner on the top of CourtListener asking for donations.

    We have some really easy code for this, but it's worth looking around at Wikipedia, EFF, ACLU, Archive.org, Cornell's LVI, etc to see how others are doing this. I think the rest of the world is WAY more aggressive than we are, and we should try to be more aggressive without spending too much time making it really polished.

 - [x] @ERosendo: Open a new tab in all RECAP browsers pointing to the page created above.

 - [x] @jeniferw: Send out newsletters, tweets, etc.

**Comment by mlissner** [comment]
I'm removing this from Eduardo and my boards. It's all you now, Jenifer!

**Comment by jimtje** [comment]
Hey, I emailed but never got a response, but should I move my yearly donation out of Github and onto your site directly? Since my background is "lawyer who happens to write code" instead of "software engineer who has a law degree" and also, contributors here are a tiny proportion and I don't know if that makes your accounting more complicated than it needs to be - since I don't know how Github handles these things on the backend. But if it makes no difference whatsoever the current setup works for me since I generally like to plan my financial contributions by the year and way ahead of the time and being able to designate a month to a particular cause/project I care about and take care of it for the next year as far as I'm concerned is something that Github allows me to do. I just don't want to be the asshole that thinks that I'm entitled to create extra work for you guys, I already feel bad enough not actually contributing to your codebase. Let me know which way you prefer. I have you guys set up for December 3rd, btw. Thanks!

**Comment by mlissner** [comment]
It's all good either way, @jimtje, but thanks for asking. Non-profits have the curse of getting money from lots of places no matter what, so Github is just one of many sources we have and we're very used to it. Github is nice though because I think they don't charge CC fees like the others do (I think this is Microsoft just footing the bill — nice!).
