### ISSUE TITLE
Mechanism to Reprocess some failed recap.email needed

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#3503]
## Issue Description:
The current email processing system occasionally encounters failures, resulting in some emails not being processed into RECAP. Unprocessed emails may contain critical information for a court docket. Regular failures while not common could decrease the reliability of recap.  

## Suggested Solution:
We should create a standalone method either in lambda? or in courtlistener to reprocess a file.  @albertisfu suggested a method to just post the data again - but I'm not sure how we would implement that outside of building something in Lambda.

**Comment by mlissner** [comment]
I guess at the point we get a failure, we have:

 - Received the email
 - Put it in S3
 - Run the lambda
 - Which did a POST
 - Which was stored in our API endpoint
 - Which we tried to parse, but which failed

Do we have a failed API request with the needed details at the time of failure? If so, that seems like the thing to hook into for the retry. If we have an admin panel for those objects, maybe we could add an admin action to do it?

**Comment by albertisfu** [comment]
Yes, the plan makes sense.

We do have the **`EmailProcessingQueue`** model, where all the recap.email requests are stored. So, we could add this model to the admin and implement a custom action to reprocess the failed instances. This can be done by simply calling:

**`do_recap_document_fetch(epq, user)`**

In this case, the user could be the default recap.email user.

**Comment by mlissner** [comment]
Simple enough. Let's put this on @ERosendo's backlog, and prioritize it according to whenever @grossir gets our parsers fixed and deployed. Should be a fairly easy solution.

**Comment by mlissner** [comment]
Shoot, thanks to Epstein, we had 13 failed emails today in issue [RECAPEMAIL-LAMBDA-9](https://freelawproject.sentry.io/issues/4803787511/). @albertisfu do you think you can whip up an admin command for this so we can reprocess those tomorrow (Thursday)? It might be best if we just reprocess them ASAP, and then follow up with the admin command?

**Comment by albertisfu** [comment]
Great, I've reprocessed the emails reported in [RECAPEMAIL-LAMBDA-9](https://freelawproject.sentry.io/issues/4803787511/) using the action that @ERosendo added to admin.

From the Sentry event context, I retrieved the email `message_id`, which looks like **`389652978.588.1704329032286@ca9db-rep.ca9.gtwy.dcn`**.

Then, using this **`message_id`**, I identified the related S3 keys, since this `message_id` is within the email body. From the email file, I also obtained the `court` and the recap.email recipient address.

Next, using this data, I created the EPQs objects using the admin and reprocessed them.

There were nine in total, as some of the events were duplicated in Sentry.

https://www.courtlistener.com/admin/recap/emailprocessingqueue/47039/change/
https://www.courtlistener.com/admin/recap/emailprocessingqueue/47041/change/
https://www.courtlistener.com/docket/67534649/rachel-damiano-v-grants-pass-school-district-no-7/
2 Minute entries on Jan 3

https://www.courtlistener.com/admin/recap/emailprocessingqueue/47042/change/
https://www.courtlistener.com/docket/4226871/cin-q-automobiles-inc-v-buccaneers-limited-partnership/
Entry 516

https://www.courtlistener.com/admin/recap/emailprocessingqueue/47045/change/
https://www.courtlistener.com/docket/67631223/zermatt-holdings-llc-v-cooper/
Entry 32

https://www.courtlistener.com/admin/recap/emailprocessingqueue/47047/change/
https://www.courtlistener.com/docket/67856158/in-re-uber-technologies-inc-passenger-sexual-assault-litigation/
Entry 179

https://www.courtlistener.com/admin/recap/emailprocessingqueue/47048/change/
https://www.courtlistener.com/admin/recap/emailprocessingqueue/47050/change/
https://www.courtlistener.com/admin/recap/emailprocessingqueue/47052/change/
https://www.courtlistener.com/docket/68127442/headwater-research-llc-v-samsung-electronics-co-ltd/
Entries 15, 16, 18

https://www.courtlistener.com/admin/recap/emailprocessingqueue/47051/change/
https://www.courtlistener.com/docket/67721832/michael-e-parks-jr-and-michelle-parks/
Entry 40


Additionally I review errors on the `ReadTimeout` [RECAPEMAIL-LAMBDA-8](https://freelawproject.sentry.io/issues/4558807354/) issue, most of events there were also related to the same emails in RECAPEMAIL-LAMBDA-9 

Just 3 were different:
```
jke53vi5e78e1g4cgujln3g307g503ef1nl7iho1
6u2kvofcuuo3e5ugnvf9ddbocm238qd2kd5thpg1
hojrtpbnqekia87ie239mqqldq7juobb4chb33o1
```

But also checked if it existed a EPQ for these IDs and yeah I found they have some and their processing was succesful.
For instance:
https://www.courtlistener.com/admin/recap/emailprocessingqueue/?message_id=jke53vi5e78e1g4cgujln3g307g503ef1nl7iho1
https://www.courtlistener.com/admin/recap/emailprocessingqueue/?message_id=6u2kvofcuuo3e5ugnvf9ddbocm238qd2kd5thpg1

Only `hojrtpbnqekia87ie239mqqldq7juobb4chb33o1` didn't have a previous EPQ, so I created one for this and processed it.
https://www.courtlistener.com/admin/recap/emailprocessingqueue/47081/change/
https://www.courtlistener.com/docket/68127442/headwater-research-llc-v-samsung-electronics-co-ltd/
Entry 17

The reason some of these have an EPQ even though they triggered an error, I believe, is that between retries, CL was able to process the request and create the EPQ, even if there was no response to the lambda request.

So, for the next time we need to re-process some emails, it is recommended to first check if the `message_id` has an existing EPQ.

**Comment by mlissner** [comment]
Thanks. Do you have some code you used that's worth posting here for next time?

**Comment by albertisfu** [comment]
Sure, I just used the my script to retrieve data from sentry events with some tweaks for this issue to get the emails IDS from all the events in a date range:
[get_email_ids_from_sentry.txt](https://github.com/freelawproject/courtlistener/files/13843786/get_email_ids_from_sentry.txt)

The returned IDs looks like: `<3173902145@court.uscourts.gov>`

With the IDs in the previous step I ran the following `grep` over a folder with the email files from the datetime around the issue:
```
grep -lr \
-e '<3173902145@court.uscourts.gov>' \
-e '<other@ids>' path_with_files
```
And the output is a list of S3 Keys like:
`jke53vi5e78e1g4cgujln3g307g503ef1nl7iho1`

The rest of the process was manual, create the EPQs in the admin and process them.

We could automate also this process, for instance we could create a command that receives a CSV with the EPQs to create, check if there are existing EPQs and create the required ones and process them.

**Comment by mlissner** [comment]
Great. Let's just keep this here for the moment and remember we have this note. If we end up using it again, let's add it to the wiki, and if we find that it would take longer to do the action than to do the programming, let's do the programming.

**Comment by ERosendo** [comment]
done! Here's the queue:

https://www.courtlistener.com/admin/recap/emailprocessingqueue/111448/change/

**Comment by mlissner** [comment]
Great, but it looks like it failed? Is that expected?

**Comment by ERosendo** [comment]
@mlissner I didn't expect that, but when I looked at the content of the email, I noticed there was no document associated with the transaction. 

Here's the link to the object: [email](https://s3.us-west-2.amazonaws.com/recap.email/ge2ua5ue8vhvf96jdo61unvm4b1mq0dds08o5f01)
