### ISSUE TITLE
Clean up for Opinion Search Alerts.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#3632]
Before launching the ES Opinion Search live, we should clean up the current Opinion Search Alerts queries. 

In the new ES Opinions Index, we have renamed the values of the fields **`status`** and **`type`**, and removed **`caseNameShort`**. 
Therefore, it's necessary to fix any Alerts that utilize these fields.

Additionally, we need to modify the **`cl_send_alerts`** command to query the search alerts using ES. This will serve as a temporary solution before moving Opinion alerts to utilize the Percolator.

**Comment by albertisfu** [comment]
To ensure a smooth transition of Opinions to ES, we should follow these steps:

- I am working on a PR that adjusts **`cl_send_alerts`** and confirm if any changes are required in the templates. It will include a waffle switch, allowing us to control the timing of the transition.
- In order to confirm all the alerts are good in terms of syntax. We need to run the #3890 alert validation queries command. I've confirmed the `stat_` filter having different values at this stage won't affect syntax, internally it just set the default status to the filter, so we can run it by:
**`manage.py clean_up_search_alerts --action validate-queries --validation-wait 1`**
- Based on the results from the previous command, we will determine if additional actions are needed to fix alerts.
- Once we confirm the alerts are in good shape, it's time to clean up the **`stat_`** filter using:
**`manage.py clean_up_search_alerts --action clean-up`**
This should be done ensuring the **`cl_send_alerts`** cron job is not close to be executed. I do not recall the frequency of the alerts cron job. If it runs too frequently, we might consider temporarily stopping it.

- After cleaning the alerts, we are prepared to make opinions public and we should change the opinions waffles for everyone, including those for search and alerts.
- If the cl_send_alerts cron was stopped, we should re-enable it.

**Comment by mlissner** [comment]
OK, per our conversation just now, we need to write some code to convert webhook search alerts v1 and search API v3 to use Elastic. We can't make it perfectly like the current API, but we can get it close and provide some time for folks to adjust. I'll write the full plan in a separate issue, but as far as webhook v1 and API v3 go:

 - Using the collapse filter like in Solr is fine for v3 of the search API.
 - Losing `caseNameShort`, `pagerank`, and `status_exact` is fine. 
 - `court_exact` can be copied from the `court` field.
 - `non_participating_judges` can be removed.
 - `source` can be removed.
 - `status` and `type` can have a little mapping so that they're unchanged when we switch to Elastic-backed v3.

Hopefully with some notice to our customers, this will be fine.

**Comment by blancoramiro** [comment]
Hey @albertisfu. Please let me know if you need anything from my end. Thank you!

**Comment by albertisfu** [comment]
Sure! I'll let you know once we are ready to perform this action. We just need to complete the documentation for version 4 of the Search API before it can be released.

**Comment by albertisfu** [comment]
@mlissner confirmed that it's better to wait for releasing the whole Case Law Search/Alerts suite to the public as you outlined [here](https://github.com/freelawproject/courtlistener/issues/3033#issuecomment-2010849352).

If we perform the Opinions Alert cleanup now and make ES run Opinion Alerts, we'll also need to move the Search frontend to ES. This ensures that new alerts saved via the frontend use the new fields in queries and are compatible with ES `cl_send_alerts`.

However, there are two additional issues if we only move the frontend to work over ES:

1. If a V3 Search API user copies a search query generated by the frontend to use it on the V3 Search API running over Solr, it might not be compatible if it uses one of the fields that changed on ES.
2. When moving Alerts to ES, the Search Alerts Webhooks will use the `V3OpinionESResultSerializer`, which uses the new field values compatible with ES described in the [migration guide](http://localhost:8000/help/api/rest/v4/migration-guide/#opinions-breaking-changes). I'm just noticing that we are not explicitly specifying that these changes will also apply to the Opinion Search Alerts webhook payload alongside the V3 Opinion Search API. Would it be a good idea to mention it, or is it implicitly understandable?

We have a command to validate current Opinions Alerts, just to check if there are more alerts (besides field replacements) that would require manual intervention due to their syntax being incompatible with ES, such as having unbalanced parentheses or special characters that break the query.

Do you think it's worth running it now just to confirm there aren't too many changes to do manually that would require some kind of automation? Or should we wait until we're closer to the release?

`manage.py clean_up_search_alerts --action validate-queries --validation-wait 1`

**Comment by mlissner** [comment]
Thanks. I think we're good here. The documentation doesn't mention webhooks because we're going to reach out to people about them directly. @s-taube, we should get on that, eh? :)

For the rest, yes, looks like we'll have to wait until the deadline in the migration guide to flip the switch here, but we do need to get the current webhook folks migrated before then. Soon!

**Comment by mlissner** [comment]
I think we can close this. The notes are here: https://github.com/freelawproject/courtlistener/issues/4713
