### ISSUE TITLE
Add judicial clerkships table

### ISSUE THREAD

**Issue by ellliottt** [freelawproject/courtlistener#370]
Include a table in the judges DB that includes clerkships. The fields are 

`[clerk,judge,startdate,enddate]`

This looks like a good place to start: https://en.wikipedia.org/wiki/List_of_law_clerks_of_the_Supreme_Court_of_the_United_States

**Comment by ellliottt** [comment]
This adds to the need for a "person" table rather than a "judge" table. We will get info on many of these clerks, and many of them won't be judges (yet). We could put attorneys and expert witnesses in the person table as well, for example.

**Comment by brianwc** [comment]
Some might find it interesting that we would distinguish between judges and persons. Not an objection, just sayin'.

On September 22, 2015 1:38:32 PM PDT, ellliottt <notifications@github.com> wrote:
>This adds to the need for a "person" table rather than a "judge" table.
>We will get info on many of these clerks, and many of them won't be
>judges (yet). We could put attorneys and expert witnesses in the person
>table as well, for example.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/freelawproject/courtlistener/issues/370#issuecomment-142412821

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by mlissner** [comment]
I mean, if we want to do this right way, we should consider judges to be a special case of users. Instead of adding a separate table of them, we should add a flag to the users table that says what type of person the user is. As you might guess, this is a dangerous path to tread, though we already have two types of users, those that actually have accounts, and so-called stub-users, whom made a donation independent of having an account.

A step down from that insanity would be to have a people table, like @ellliottt is suggesting, separate from the users table, though that means that we'd one day miss out on the incredible ability to say "You wrote this opinion, with Sotomayor, Roberts and 1 Other"

**Comment by ellliottt** [comment]
That would be very cool. Once CourtListener catches on, some judges will use it instead of Lexis or WestLaw. 

I think my idea was to have a People table, and then have a Judgeships table rather than a Judges table. If the end-date on a judgeship is empty, they are considered an active judge on that court.
