### ISSUE TITLE
Create a cite-checker for uploaded documents

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#374]
Our existing citation-finding code can be adapted to other contexts, as illustrated by @fgbjr's freelawferret. 

We should allow users to upload documents they want citations found in. An obvious use case is cite-checking a brief.

It's also been suggested that the visualization features we're working on would be an asset here, as visualizing the citation relationships existing in various briefs would likely show interesting features of each litigant's strategy, etc.

**Comment by Colinstarger** [comment]
Would it be easier to make this an API feature to begin with. API user makes a call with a giant text variable of some kind (i.e., the document) and gets back an array of the cites in the text variable? This would avoid the need to design a UI on CourtListener. And I imagine LOTS of folks could find use for this...

**Comment by mlissner** [comment]
I think I considered making this an API feature back when I released the first version of the API, but then opted against it because of how CPU-intensive it is. We could probably do it though with a low throttle -- say, 1/minute and 50/day or something. Even that could be pretty stressful, and who knows how big of documents folks will upload....hm.

**Comment by Colinstarger** [comment]
If it was relatively easy to implement, is this the kind of thing that could be released without any fanfare, tested on the sly, and the assessed? If the feature is too resource-intensive, it could be turned off...

**Comment by brianwc** [comment]
We process every document from juriscraper for cites. This should be similar in intensity for simple versions of this feature. It's so cool we would just raise money for a separate server if really necessary. I think people would pay quite a bit for access to more complex versions of this feature.

On October 5, 2015 10:03:16 AM PDT, Colinstarger <notifications@github.com> wrote:
>If it was relatively easy to implement, is this the kind of thing that
>could be released without any fanfare, tested on the sly, and the
>assessed? If the feature is too resource-intensive, it could be turned
>off...
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/freelawproject/courtlistener/issues/374#issuecomment-145599618

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by mlissner** [comment]
Alas, it's more complicated than that, and indeed we've already tweaked the scraping framework so that the results of a scrape are only parsed over the course of the next half hour. When they were parsed immediately a scrape that downloaded a bunch of new opinions would generate hundreds of (fast) queries, which would bog down Solr's query queue, making front end queries lag terribly.

So, we could throw more hardware at this problem, but even a dedicated server wouldn't solve it. Two ideas that might:

1. Replicate the Solr index across multiple servers, allowing each server to handle half the queries. At times of demand (like when finding citations in a document), this would roughly double the speed of the parsing. At times of low demand, no improvements would result. I don't love this though because it adds complication and because we're frankly not at the level of scale where this should be necessary.

1. Add some kind of delay after each query, allowing front end queries to slip into the gaps. This sucks because:
    1. It makes things harder to debug when you have random delays all over the place. Who knows what's happening where? 
    1. It means the front end or API would have longer wait times for results. In the front end, that's probably OK, but on the API, that could mean timeouts (might be OK though) or the need for us to post results to a different URL once they're ready. Either way: More complication.

    But, it'd avoid the need for more hardware and the complication mentioned above. 

In general, I'd favor the second approach, though testing should quickly determine what solution makes the most sense, so I guess the point of this is to say, I don't think the solution here won't be as easy as more hardware. BUT, I do think it's solvable.

**Comment by brianwc** [comment]
For cite-checking purposes the citations one is citing to are not typically recent, since those recent cases often don't even have true citations. This means the cite-checking server could be a week or month behind live CL without any harm to functionality. So it's a little easier than keeping the solr index perfectly synced across multiple servers. Instead it just needs to be copied over late every Friday night.

So this is a third approach, have a dedicated cite-checking server that is a little behind live CL. Juriscraper can still run its stuff on live, but all new cite-checking queries are handled elsewhere.

On October 5, 2015 10:01:51 PM PDT, Mike Lissner <notifications@github.com> wrote:
>Alas, it's more complicated than that, and indeed we've already tweaked
>the scraping framework so that the results of a scrape are only parsed
>over the course of the next half hour. When they were parsed
>immediately a scrape that downloaded a bunch of new opinions would
>generate hundreds of (fast) queries, which would bog down Solr's query
>queue, making front end queries lag terribly.
>
>So, we could throw more hardware at this problem, but even a dedicated
>server wouldn't solve it. Two ideas that might:
>
>1. Replicate the Solr index across multiple servers, allowing each
>server to handle half the queries. At times of demand (like when
>finding citations in a document), this would roughly double the speed
>of the parsing. At times of low demand, no improvements would result. I
>don't love this though because it adds complication and because we're
>frankly not at the level of scale where this should be necessary.
>
>1. Add some kind of delay after each query, allowing front end queries
>to slip into the gaps. This sucks because:
>1. It makes things harder to debug when you have random delays all over
>the place. Who knows what's happening where? 
>1. It means the front end or API would have longer wait times for
>results. In the front end, that's probably OK, but on the API, that
>could mean timeouts (might be OK though) or the need for us to post
>results to a different URL once they're ready. Either way: More
>complication.
>
>But, it'd avoid the need for more hardware and the complication
>mentioned above. 
>
>In general, I'd favor the second approach, though testing should
>quickly determine what solution makes the most sense, so I guess the
>point of this is to say, I don't think the solution here won't be as
>easy as more hardware. BUT, I do think it's solvable.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/freelawproject/courtlistener/issues/374#issuecomment-145742576

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by mlissner** [comment]
The API part of this bug from 2015 is getting completed here: https://github.com/freelawproject/courtlistener/issues/3337.
