### ISSUE TITLE
Docket display- two dockets combined, not displaying all available PDFs, 

### ISSUE THREAD

**Issue by mikeweinberg** [freelawproject/courtlistener#3833]
I came upon [this docket](https://www.courtlistener.com/docket/4767883/national-indoor-foot-v-rpc-employers-ser/). 

Initially, I thought that it was not sorted correctly. It starts at doc 60, goes up to doc 173 in order, then starts at 1 again and counts up. All the first docs are shown as available in Courtlistener while the others are shown as not available.

But it seems to be two unrelated cases merged together- So it's correctly sorted by date but the numbers are from the two separate cases: an old case that went from 2006-2009 and a newer Trump case that started in 2020.

There's at least one reason why the "available" display may also be wrong:

I clicked on "Buy on PACER" for doc 11, which is not shown as available on Courtlistener.

I [clicked through](https://ecf.pawd.uscourts.gov/doc1/15707458110?caseid=19454) to the PACER document selection screen.

The document selection screen (thanks to RECAP 2.5.0) shows that Courtlistener has both doc 11 and its attachment 1 (Exhibit A) to download.

Browser: Windows Chrome 121.0.6167.185

**Comment by ERosendo** [comment]
@mikeweinberg Thanks for your report. 

You're right. Docket [2:02-cv-00548](https://www.courtlistener.com/docket/4767883/national-indoor-foot-v-rpc-employers-ser/) previously included some entries from [2:20-cv-00966](https://www.courtlistener.com/docket/17309579/donald-j-trump-for-president-inc-v-boockvar/). I checked our database and found that a docket report from 2:20-cv-00966 uploaded in 2020  was incorrectly merged into docket 2:02-cv-00548,  causing this data discrepancy. The incorrect data was uploaded through the Recap extension, and this error might be related to the bug described in #2211 (which has been fixed since 2022).

Docket [2:02-cv-00548](https://www.courtlistener.com/docket/4767883/national-indoor-foot-v-rpc-employers-ser/) now displays filings in the correct order and the entries from the unrelated Trump case have been removed. A full docket report was uploaded on February 27th and fixed the discrepancies in our records.
