### ISSUE TITLE
Bug in Displaying results from opinions in Elasticsearch 

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#3834]
I came across a random bug - where the original query to CL displayed the first page of results with out case names.  See image below.  The second page correctly rendered the information on the page.  

I asked @grossir  and @albertisfu about this - @grossir reported that he did not have any issue with the page while logged in or not, but @albertisfu had the same bug appear.

After a few minutes - the bug appeared to disappear and display results correctly on the first page. 

I have to assume there is some random caching thing going on.  

[This query](https://www.courtlistener.com/?q=Nixon+v.+Warner+Communications%2C+Inc.%2C+435+U.S.+589+1978&page=1)

![screenshot_2024-02-29_at_9 58 37___am_720](https://github.com/freelawproject/courtlistener/assets/6464529/d4e59d01-4fd4-40c3-aa1e-7c089214dca5)

**Comment by flooie** [comment]
There appears to be a bug in this part of the code 

```
  {% if error_message %}
    {% if suggested_query == "proximity_query" %}
      <h4 class="text-danger" >Are you attempting to perform a proximity search?</h4>
      <p>Try using this format: <code>term~</code> or <code>term~2</code>. For more details, visit our <a href="{% url "advanced_search" %}#proximity">advance search documentation</a>.</p>
    {% elif suggested_query == "proximity_filter" %}
      <h4 class="text-danger" >Are you attempting to perform a proximity search within a filter?</h4>
      <p>Proximity queries do not work in filters. Consider using the main search box. For more details, visit our <a href="{% url "advanced_search" %}#proximity">advance search documentation</a>.</p>
    {% elif suggested_query %}
      <div class="flex">
        <h4 class="text-danger" >Did you mean:&nbsp;<a href="{% url 'show_results' %}?q={{suggested_query}}&type={{request.GET.type}}">{{suggested_query}}</a></h4>
      </div>
    {% endif %}
```

My original query contained an `unbalanced_parentheses` and the URL generated on the no_results page failed to find a type.  The missing type value causes the bug in displaying case names in search results

**Comment by albertisfu** [comment]
Yes, the problem seems to be related to unbalanced parentheses in the URL recommendation:

It generates a URL like this:
`https://www.courtlistener.com/?q=Branzburg%20v.%20Hayes%201972&type=`

Providing a blank `type` parameter causes the results not to be properly rendered because the template doesn't recognize what type of search it is.

Not having a `type` parameter at all is okay:
https://www.courtlistener.com/?q=Branzburg%20v.%20Hayes%201972

Because it defaults to opinions.

The issue arises when the recommendation link takes the `type` from the current URL, and if there is no type, it generates the URL with `&type=`.

We have to behaviors:

If you start the search from:
https://www.courtlistener.com/opinion/
The type is `o`

But if you start it from:
https://www.courtlistener.com/
There is no type on the search URL.

And if your query includes unbalanced parentheses, the recommendation URL is generated incorrectly.

We can simply fix the `unbalanced_parentheses` URL so it avoids adding a blank type.

However, I'm also wondering if it's ok to have URLs  for opinions with a type parameter and URLs without one.

**Comment by mlissner** [comment]
> However, I'm also wondering if it's ok to have URLs for opinions with a type parameter and URLs without one.

Yeah, any of these are fine:

 - `type=o` or no type parameter --> opinions
 - `type=r` --> RECAP
 - `type=oa` --> Oral args
 - `type=p` --> Judges

We could make `type=` also work for opinions too, if that's the easier solution...
