### ISSUE TITLE
Launch v4 of the API and split API docs into smaller pages

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3874]
When we launch the new Elastic-powered search API, that will be v4 of our APIs. 

We should take this opportunity to update the documentation. The main documentation page is just too long, so let's move the current v3 API documentation to `/help/api/rest/v3/` (as we always do) and when we launch the v4 version, let's start splitting a few pages off of it:

 - **Financial Disclosures:** This is a largish section of the current documentation. Let's pull it out into a new page at `/help/api/rest/financial-disclosures/`. The current page can just provide a pointer to this page, like how our coverage page links to subpages:

    ![image](https://github.com/freelawproject/courtlistener/assets/236970/045e8936-9e5b-46fc-834f-aeebda8d3d3a)

 - **Search** This page can be created at `/help/api/rest/search/` and can be largely the same as our current one (but with whatever updates it needs) and can provide more detail if needed. This would be a really good opportunity for one of our user researcher volunteers.

 - **Alerts**  `/api/rest/v3/alerts/` and `/api/rest/v3/docket-alerts/` can be spun into their own page at `/help/api/rest/alerts/`. Search alerts will soon be really important, so it'll be good to spin them off.

 - **RECAP APIs.** There are a bunch of APIs related to RECAP. Let's split them off too, including: `/api/rest/v3/recap/`, `/api/rest/v3/recap-query/` and `/api/rest/v3/recap-fetch/`. This page should also provide a pointer to the new alert API help page above. This can be located at `/api/api/rest/recap/`.

 - **Migration Guide** Let's write a migration guide at `/help/rest/api/v4/migration-guide/` that explains that only the search API has changed and that explains the differences between the two APIs.

Note that v4 only changes the search API, but we'll launch it across all our API endpoints. For most people upgrading will mean switching their URL from v3 to v4. For people using the v3 search endpoint, they'll need to do a little upgrade to make v4 work. v3 will continue working fine until we have a reason to get rid of it, or we get everybody migrated off it.

One other thing: We'll need to update [our changelog](https://www.courtlistener.com/help/api/rest/changes/) to include a reference to the migration guide.

**Comment by mlissner** [comment]
See also: https://github.com/freelawproject/courtlistener/issues/3382

**Comment by albertisfu** [comment]
@mlissner  These are the changes I'm planning to do for the V4 API documentation:

- Move the current API documentation to **`/help/api/rest/v3/`**.
- Add V4 API documentation to **`help/api/rest/`**. Should this PR be held until we launch V4, or would it be better to add the change behind a waffle?

**Move some content to their own page:**

- Financial Disclosures to **`/help/api/rest/financial-disclosures/`**
- Search to **`/help/api/rest/search/`**
- Alerts (alerts and docket-alerts) to **`/help/api/rest/alerts/`**
- RECAP APIs to **`/api/api/rest/recap/`**

All other endpoints and content will remain on the same page. Should we split anything else?

**Regarding issue #3382, which describes splitting the filtering documentation, should I add that now as well?**


### Updated content for the V4 Search API:

This is only an outline of the proposed content, I'll add more details if you agree with the content.

**Overview:**
Current content mentioning the endpoint utilizes the same GET parameters as the frontend, though it differs from other endpoints in that it does not support the OPTIONS method and more.

**Cursor Pagination:**
Mention that the V4 Search API employs cursor pagination as a trade-off for enhanced performance and to facilitate deep pagination. As consequence, users cannot directly jump to a specific page. Navigation through the data is exclusively via next and previous links.

Note that if users want to go to page 0 or switch to a different content type, the cursor must be removed from the request.

**Ordering:**
Ordering in V4 is consistent with V3, using the same sorting keys as the frontend, with the exception of random sorting. Mentioning that the order of results might differ from the frontend due to the use of a secondary sorting key. For **`r`** and **`d`** types, **`docket_id`** is used, and for **`rd`** types, **`RD id`** is used. This secondary sorting is always in descending order, regardless of the primary sorting direction.

**Filtering:**
Filtering is similar to V3, describing users can use any query that worked in the frontend for filtering documents.

**Fields:**
Similar to V3 and it would be worthwhile to describe the data types available in the API and their formats, both filled and empty:

- Integers (null when empty)
- Strings (empty string when empty)
- Lists (empty array when empty)
- Dates (null when empty)
- Datetimes (null when empty)
Data types are formatted in ISO 8601 and UTC.

**Search Types:**
The supported search types include:

- **`o`** — Opinions
- **`r`** — Document-oriented results from the RECAP Archive
- **`d`** — Docket-oriented results from the RECAP Archive
- **`rd`** — RECAPDocuments-oriented results
- **`p`** — Judges
- **`oa`** — Oral Arguments

We can provide an example of how the **`r`** type now displays nested RD documents within the **`recap_documents`** field.

Also, describe the behavior of matching up to 5 RD documents and whether the **`more_docs`** field will be true. Additionally, explain how users can use the **`rd`** type to request all the RD documents in a docket that matched in the **`r`** type using a **`docket_id`** query.

Describe the new **`rd`** type, noting that it only shows RECAPDocuments but works with the same queries as the **`r`** type. RDs can be matched by Docket fields, except for the party and attorney fields.

**Would it be a good idea to provide an example of each response from  `rd`, and `d` types too?**

**Highlighting:**
Explain that by default, highlighting is disabled to enhance query performance. To enable highlighting, include **`highlight=on`** is required to pass to the request. 

Describe the HL fields available for each search type.

**Count:**
Explain that matching fewer than 10,000 documents, the count is accurate. For those exceeding this threshold, counts are approximate with a potential error margin of 1-6%.

**Errors:**
Describe the type of error messages users can encounter two primary types of error messages: 

**`ElasticServerError`** or **`ElasticBadRequestError`**.


### Migration guide:
I'll describe here only the differences between V3 and V4, specifically for the Search API endpoints, including:
- Change in field formats, including date and DateTime fields 
- Cursor pagination
- Count over 10,000 hits not exact
- Highlighting 
- New search type (rd)
- Error messages

Pointing that other endpoints didn't change and only required a change in the URL.

### Update the API changelog


### Move non-search endpoints to V4
I'll open a separate PR to move all the non-search endpoints to V4.

We also have references to these issues in the V4 API backlog: #701 and #2029, but I think the changes described there are already completed or covered by the improvements mentioned above, right?

Let me know what you think.

**Comment by mlissner** [comment]
This is basically done!
