### ISSUE TITLE
Disable stemming in case name searches

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3887]
A user is upset that his case name search for `Howell` found results for `Howells`. Fair enough. I don't think people want broad searches when they're searching by name, so when somebody does a case name search we should be sure to do exact searches and that'll enhance relevancy for this one query type.

**Comment by albertisfu** [comment]
A question here.  Are you referring to completely disabling stemming on the `caseName` field so that text queries and the `case_name` filter only match the original terms in the `caseName` field, correct?

I believe this can be achieved by using the `search_analyzer_exact` for `caseName`. This should work for the `case_name` filter, but I need to run some tests to ensure it can also be applied to the `query_string` without affecting other fields.

**Comment by mlissner** [comment]
It's fine if it doesn't apply to the query_string too. :)
