### ISSUE TITLE
Add default website docket entry ordering to the API

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4061]
From `cl.search.models.DocketEntry.Meta`, docket entries are sorted by: 

```
        ordering = ("recap_sequence_number", "entry_number")
```

But that ordering is not available in the API. Oof! Let's fix that for our customers and then document it in our new documentation page. 

I'm not sure how to sort by two fields like this in DRF, but I assume it's not too difficult.

**Comment by elisa-a-v** [comment]
So, what we want here is to be able to list docket entries using both fields to order at the same time, right? but only when a user explicitly sends the query parameters to do so? and I'm assuming the relevant endpoint here is listing from `DocketEntryViewSet`.

DRF [supports ordering using multiple fields](https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter) just like in a model's Meta class, so if I'm getting this right, this issue should simply add the required fields to the `ordering_fields` in `DocketEntryViewSet`, then we'd use `/api/rest/v4/docket-entries/?ordering=recap_sequence_number,entry_number` to get the ordered results.

I did notice something weird: the ViewSet is explicitly setting an `order_by` in the queryset:

```
queryset = (
    DocketEntry.objects.select_related(
        "docket",  # For links back to dockets
    )
    .prefetch_related(
        "recap_documents",  # Sub items
        "recap_documents__tags",  # Sub-sub items
        "tags",  # Tags on docket entries
    )
    .order_by("-id")
)
```

I believe this is overriding all other orderings, so it's not just that the combination in the model isn't available, not even the `ordering_fields` are working for me unless I get rid of both that line _and_ the `ordering="-id"`, but I guess I'm probably missing something tho because that `order_by` has been in that queryset since 2019, so I imagine if it really wasn't working, we would already know? 😅 and the `ordering` attribute [should only work as a default](https://www.django-rest-framework.org/api-guide/filtering/#specifying-a-default-ordering) if no query parameters are passed, so I wonder if it's just me seeing this behavior?

**Comment by mlissner** [comment]
Hm, I added that order_by to a bunch of queries in https://github.com/freelawproject/courtlistener/commit/9e7a57e1313edeee058f14a044b845bf9d2ed419, but it does look like I should have read the documentation rather than just figure it out. 

That said, I'm able to re-order at least one of the APIs see: 

https://www.courtlistener.com/api/rest/v4/audio/?order_by=id

vs. 

https://www.courtlistener.com/api/rest/v4/audio/?order_by=-id

Seems to work for docket entries too? 

https://www.courtlistener.com/api/rest/v4/docket-entries/?order_by=-id 

vs. 

https://www.courtlistener.com/api/rest/v4/docket-entries/?order_by=id

What are you trying that's not working?

**Comment by elisa-a-v** [comment]
yeah it was me, I was using the DRF default query parameter name, which is `ordering` 😅 I see it working now. So just to make sure, am I right in thinking that the ordering using those fields should only be done when the user explicitly adds the query parameters? the "default" in the issue title is throwing me off.

I'm also wondering if this issue includes documenting the DocketEntry API? [These are the docs](https://www.courtlistener.com/help/api/rest/case-law/), right? there's no docket entry section at all.

**Comment by mlissner** [comment]
Ah. We use `order_by`, I think, because it came from a version of the API that pre-dates DRF.

> am I right in thinking that the ordering using those fields should only be done when the user explicitly adds the query parameters?

Yes. It's the default on our website, when you look at a docket, so it should at least be *available* via the API.

> there's no docket entry section at all.

These are the API docs you're looking for: https://www.courtlistener.com/help/api/rest/pacer/. Adding a note in here somewhere about these ordering parameters probably being what people want would be a good idea, yes. Maybe at the end of the Docket Entries section?
