### ISSUE TITLE
Share Link Should Utilize New Citation Shortcuts

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#411]
https://www.courtlistener.com/opinion/158785/aclu-v-johnson/ which is ACLU v. Johnson, 194 F.3d 1149 (10th Cir. 1999),

along with every other case for which we have a citation, now has a shorter, predictable link based on that citation, in this case:

https://www.courtlistener.com/c/F.3d/194/1149

The share links have been completely useless to me for a long time, namely because when you view a case after a search results page you get a 10,000 character link that is totally absurd and that no one wants to share. I've just been chopping these off manually for years, but it occurs to me now that a feature that is this broken should either be fixed or removed. Providing these citation shortcuts is the first step to fixing it.

Step 2 to fixing it would be to handle the documents for which we have no citation, and we should be able to do that by trimming the URL to include only the part up to the name slug after the id# and nothing else after that name slug's closing slash. All the rest of that solr-created crap makes me nuts.

I really think this should be filed as a bug because the current behavior is so bad as to be essentially broken, but I'm going to label it an enhancement anyway.

**Comment by voutilad** [comment]
I agree the Solr state parameters gunk up that url. 

The default share link should probably be the citation-based link. I think having an option to include the opinion title would be good to blend something descriptive into the link (when the user deems appropriate).

YouTube's behavior is something I've liked for a long time. Clicking _Share_ on a video's page and by default the user is given a shortened URL. The user then has a simple checkbox option for adding/removing the optional _start at_ setting, but it typically defaults to off.

Applying something similar to CL for the example you provided: https://www.courtlistener.com/opinion/158785/aclu-v-johnson/
* **Default Share URL**: https://www.courtlistener.com/c/F.3d/194/1149
* **w/ Optional Short Case Name**: https://www.courtlistener.com/c/F.3d/194/1149#aclu-v-johnson

The hash stuff, by all modern browser conventions, doesn't impact the URL navigation, so it could work as a cheap way to offer a human-readable reminder about what the opinion is about.

Thoughts?

**Comment by mlissner** [comment]
@brianwc you should have filed this long ago. Removing the search params is super easy and I agree we should do it. 

I like the idea of using the citation links in the share feature, but I think it's not quite worth it. Two reasons:

1. Generating one of these links is a pain because you have to iterate over all of the citation fields until you find one that has a value. This could be handled with an `@property` on the model, I suppose, but then we've got our URLs defined in our models, and that's not great design.

2. More importantly though, the citation links aren't unique. So, you might share one and the recipient might see a disambiguation page when they click it, asking which `194 F.3d 1149` they're after. As of now, there's no way for these links to indicate which ambiguous citation it refers to. 

So, I think the best (and simplest) thing we can do is just use links like:

https://www.courtlistener.com/opinion/158785/s/

That is, we replace the slug with the letter s, and remove the search params. 

@voutilad In response to the hash tag idea, I think I'm +0. It's not a bad idea, but I'm not sure it's the best use of our time or that people would notice/care very much.  I'd rather just choose to provide the slug or not and let people roll with our executive decisions

Thoughts?

**Comment by brianwc** [comment]
The /s/ would be good for length, but @voutilad makes a good point that people might like that the link gives some idea what the case name is, so maybe defaulting to our normal slug is best.

I don't mind the disambiguation page problem. It would be rare and I'd rather show off our fancy new citation links, but I defer to @mlissner on whether the difficulty of implementation is worth it.

On January 8, 2016 3:05:45 PM PST, Mike Lissner <notifications@github.com> wrote:
>@brianwc you should have filed this long ago. Removing the search
>params is super easy and I agree we should do it. 
>
>I like the idea of using the citation links in the share feature, but I
>think it's not quite worth it. Two reasons:
>
>1. Generating one of these links is a pain because you have to iterate
>over all of the citation fields until you find one that has a value.
>This could be handled with an `@property` on the model, I suppose, but
>then we've got our URLs defined in our models, and that's not great
>design.
>
>2. More importantly though, the citation links aren't unique. So, you
>might share one and the recipient might see a disambiguation page when
>they click it, asking which `194 F.3d 1149` they're after. As of now,
>there's no way for these links to indicate which ambiguous citation it
>refers to. 
>
>So, I think the best (and simplest) thing we can do is just use links
>like:
>
>https://www.courtlistener.com/opinion/158785/s/
>
>That is, we replace the slug with the letter s, and remove the search
>params. 
>
>@voutilad In response to the hash tag idea, I think I'm +0. It's not a
>bad idea, but I'm not sure it's the best use of our time or that people
>would notice/care very much.  I'd rather just choose to provide the
>slug or not and let people roll with our executive decisions
>
>Thoughts?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/freelawproject/courtlistener/issues/411#issuecomment-170152400

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by mlissner** [comment]
OK, I think the easiest solution is to just remove the parameters for now. KISS. Done in dev.
