### ISSUE TITLE
Change email address confirmation emails slow or nonexistent

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#423]
I changed my email address within the CL profile page.
It logged me out and says I cannot log back in without confirming the new address. (Query whether this is wise...)
Email is either taking forever or is not being generated at all.
I'm now locked out of my account.

Seems like we need 1) a fix for the email situation; 2) a better flow that, at a minimum, gives people a chance to request the confirmation email again.

**Comment by brianwc** [comment]
Note: after waiting for a couple hours for the confirmation email, I filled out the request form asking it to be sent again. After waiting a few hours more, I added this note. Two attempts. No emails.

**Comment by mlissner** [comment]
OK, this is almost definitely related to the fact that you used an @courtlistener.com email address. For whatever reason, the mail server thinks it should send those emails to...itself rather than to the rest of the world. We can either fix the server (which I don't particularly care to do) or use a different email address, if you have one (aside: I want to phase out our @courtlistener addresses, using only free.law -- it's weird to have product-based email addresses). 

Since you're frozen out, let me know another address to use and I'll update it for you. 

The reason that you can't log in with an unconfirmed account is an annoying one, but it's a privacy thing. Say I create a donation, but I don't have a CourtListener account. That creates a shadow account for me using my email address so that if I ever create an account, all my donations will be listed in my profile and the benefits of those donations (like Real Time alerts -- will be automatically in place). 

After I create that donation, say you create an account using my email address. If you could log in without confirming it, you'd be able to see my donations in "your" profile. Ditto applies for changes of email address, which log you out and require confirmation to get back in. I'm sure there are better ways to do this, but I had to get donations out the door, and this was an easy way to hack it.
