### ISSUE TITLE
Suggest people drop citations in queries if we don't have them

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4252]
A good UX suggestion today was that if we don't have a citation in our DB, we should provide a suggestion to the user to drop that suggestion. 

So, like, if they query for `Lissner v. Walnut, 22 WL 22323`, we could look up the citation, and if it's missing, say:

> We don't seem to have the citation in your query. Instead try searching for: "Lissner v. Walnut" (259 hits)?

I think this would help whenever we lack citations, and until we get them all.

**Comment by albertisfu** [comment]
A couple of questions about this:

> So, like, if they query for Lissner v. Walnut, 22 WL 22323, we could look up the citation, and if it's missing, say:

Should the UX suggestion be processed only if a single citation is identified within the query? Should we ignore queries with more than one citation?

> We don't seem to have the citation in your query. Instead try searching for: "Lissner v. Walnut" (259 hits)?

To provide this suggestion, we need to identify the citation in the query in order to remove it. My question is, will the query always follow this format:

`case_name, Citation` or `case_name Citation`?

This way, we can remove the optional comma after the case name and the citation.

The logic would be something like this:

- Identify the citation. If there is text to the left, use it to provide the suggestion.

If we encounter a different format, such as:

```
Text, 22 WL 22323, Text
Text 22 WL 22323 Text
```

Should we also drop the citation and provide the suggested query without it? Or should we avoid the suggestion in these cases? (The suggestion would be something like `Text Text`)

- Also, what if the query `Lissner v. Walnut, 22 WL 22323` includes some filters, for instance, `docket_number:23-54343`?
  - In that case, should the query suggestion `Lissner v. Walnut` also include the selected filters?

- To provide the query suggestion with the number of hits `"Lissner v. Walnut" (259 hits)`, we’ll need to perform an additional ES count query. Is that OK?
- Should this feature be available only for Opinion Search?

**Comment by mlissner** [comment]
Many questions, Alberto. :)

> Should the UX suggestion be processed only if a single citation is identified within the query? Should we ignore queries with more than one citation?

If it's not too difficult to do this for multiple citations, we might as well support that too.

If the citation appears anywhere in a query, it can be dropped if we don't have it and the remaining query can be completed.

> To provide the query suggestion with the number of hits "Lissner v. Walnut" (259 hits), we’ll need to perform an additional ES count query. Is that OK?

Actually, the better way to do it is by just doing it and telling the user. There's really no point in returning the user's query if we know it has no hits due to a citation we don't have.

So if we find a query with a citation we don't have, we should just strip it and do the query without it. On the returned page, we should show a message that says:

> Showing results for `<whatever query>` without the citation, `<some-citation>`. It appears we do not have the citation in our system.

> Should this feature be available only for Opinion Search?

Yes.
