### ISSUE TITLE
Add docket entry date filed field to search results when ordering by that field

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4254]
A user was confused yesterday because they didn't understand how the "Newest Documents First" ordering of search results worked. This is a classic problem in search results, where users can't see what's causing ranking to change and are confused why the record they sought isn't on top. 

That's hard to fix generally, but in this case it's pretty easy. We just need to provide the docket entry date filed field on every document. 

I think you could make an argument to only show it when people order by this field, but it's probably fine to do it all the time and keep it simple.

**Comment by albertisfu** [comment]
@mlissner Here are two proposals for adding the `entry_date_filed` to the results in the frontend:

The first one considers adding the date on the same line as the document title if there is available space; otherwise, it will be pushed to the next line.
![Screenshot 2024-08-08 at 1 16 34 p m](https://github.com/user-attachments/assets/047d7f37-2e38-405c-995e-f7aae7888bef)

The second proposal is to always add the date on a new line.
![Screenshot 2024-08-08 at 1 19 16 p m](https://github.com/user-attachments/assets/d4017263-df8d-47bc-88e3-a5ad561c38da)

For mobile, due to the limited space, the date would be on a new line.
![Screenshot 2024-08-08 at 1 19 39 p m](https://github.com/user-attachments/assets/cf46a71f-7615-41ea-a7d6-0b3aefb362c3)


Let me know what do you think,

**Comment by mlissner** [comment]
Thanks. I think I like the second proposal. I was sort of thinking about doing it in a "2d ago" kind of social media way, but I think for now we can do the simple thing, and when we return to making the front end really good, we can start thinking about that.
