### ISSUE TITLE
Person table rather than Judge table

### ISSUE THREAD

**Issue by ellliottt** [freelawproject/courtlistener#428]
This might be too invasive at this point, but it would be better to have a Person table  instead of the Judge table, and we could replace Position with Judgeship. That way "judges" could be politicians, clerks, etc.

**Comment by mlissner** [comment]
This might be a pain, but I think you're right that it's probably worth it. I'm guessing you've run into a clerk that later became a judge? 

If we go this route, can we close issue #427, and issue #370, since clerks will be in the Person table too?

**Comment by ellliottt** [comment]
Yes. The best known example is Taft, who would be both an appointing politician and a supreme court justice: https://en.wikipedia.org/wiki/William_Howard_Taft

The next question would be what do with Position, Politician, and Career.

**Comment by ellliottt** [comment]
Besides a term as a judge, the other important actors that may be judges at some point are appointing politicians, counsel, and clerks.

**Comment by mlissner** [comment]
I guess we have three tables with similar data:

 - Politician table is very similar to the Person nee Judge table, except it has one more field called `office`, which says whether they were governors or presidents.
 - Career table has a few extra fields so we can track the name of an organization where a judge worked. It really only has `organization_name`, `job_type` and `job_title`. 
 - Title table has lots of titles for judges, but otherwise has almost nothing.

Maybe we can merge all of these into the position table? So a Person has Positions. 
 - Positions may be President, Clerk, or some kind of Judge Title from the list we have in the Title table. 
 - If your `Position` is at an organization, then we have a field for your title there and the name of the org.
 - If your `Position` is as a Judge, then we use one of the titles we have in the Title table for that.

So, if that can encapsulate all the logic, we can merge Career and Title into Position, and we can merge Politician into Judge (renaming it Person).

**Comment by ellliottt** [comment]
Can we close this?

**Comment by mlissner** [comment]
With pleasure.
