### ISSUE TITLE
List of v3 API users

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4315]
We'd like a list of v3 API users so that we can contact them when v4 launches.

- csv or xlsx
- first name, last name, email address

**Comment by mlissner** [comment]
Thanks Stephanie. @albertisfu, if you can provide some code for this, that'd be great. I can run it. 

Two thoughts:

1. Is it possible to get the list of search API users vs the list of other API users? 
2. I guess we'll want to look for people that have made API requests in the last year, but it'd be OK if we went back further. 

Thank you!

**Comment by albertisfu** [comment]
Sure! A few months ago, we extracted this data here:
https://github.com/freelawproject/courtlistener/issues/3033#issuecomment-2012788459

Unfortunately, we don’t have a relationship between the endpoint used and the user, so we can't determine who specifically is a Search API user.

I tweaked the code a bit to extract the First and Last Name as well.

```
import csv
from pathlib import Path

from django.conf import settings
from django.contrib.auth.models import User
from cl.lib.redis_utils import get_redis_interface

r = get_redis_interface("STATS")

user_counts_key = 'api:v3.user.counts'
api_users = r.zrange(user_counts_key, 0, -1, withscores=True)

user_requests_dict = {user_id: requests_count for user_id, requests_count in api_users}
user_ids = [int(user[0]) for user in api_users if user[0] not in ["None", "AnonymousUser"]]

media_path = Path(settings.MEDIA_ROOT)
# The directory for storing the CSV
api_directory = media_path / 'api_data'
api_directory.mkdir(parents=True, exist_ok=True)
csv_file_path = api_directory / 'api_users.csv'
# Write the data to a CSV file
api_users_queryset = User.objects.filter(id__in=user_ids).values_list("pk", "email", "first_name", "last_name")
with open(csv_file_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['UserID', 'First Name', 'Last Name', 'User Email', 'Number of Requests'])

    # Save the user details
    for user_id, email, first_name, last_name in api_users_queryset.iterator():
        user_requests = user_requests_dict[str(user_id)]
        writer.writerow([user_id, first_name, last_name, email, user_requests])
```

Let me know if you need anything else here.

**Comment by mlissner** [comment]
Great, thanks Alberto. @s-taube, when you're ready to send your email, I'll get a list together for you, but I'll hold off until then so the list doesn't get outdated.

**Comment by s-taube** [comment]
@mlissner can you create this list when you have a minute on Monday?

**Comment by mlissner** [comment]
@albertisfu, I just exported the file, but it has about 8k entries including some that are for people that have never used the API. I think the website itself uses the API (Tags, perhaps?) and that that is inflating the size of the file. 

Do you have any ideas for how we can identify people that only use the actual APIs instead of the website?

**Comment by albertisfu** [comment]
Yes, I’ve confirmed that the user data stored in `api:v3.user.counts` includes requests from the Tags endpoint used in CL.

Unfortunately, we don't have an easy way to filter out users coming from the Tags endpoint versus other endpoints, as there are no stats in Redis that can help us link endpoints usage to specific users.

I believe the only way to achieve this would be complex. We’d need to retrieve the logs from the past few months, filter out requests from `api/rest/v3/` (except from the tags endpoint), extract the IPs, and then use those IPs to attempt to identify the users in the redis records from the last few months.

**Comment by mlissner** [comment]
Shoot. I think we can get by though. Let's do the following:

1. Send our email to anybody on the list that has more than 25k API requests.

2. Look at our customer list and make sure we contact all of them.

3. Set up something to notify each person the first time they use API v3 (this is useful to prevent new implementations anyway). We used to have an email like this but we disabled it because of just this problem: https://github.com/freelawproject/courtlistener/issues/1396

4. That actually makes me think that we might have stopped logging tags at some point, so maybe anybody that used the API after that change actually used the API and wasn't logged due to Tags? Can you check, Alberto, if that's possible? 

Stephanie, let's get going on number 1 and 2 though. I'll help with the customer list when you're ready?

**Comment by albertisfu** [comment]
> That actually makes me think that we might have stopped logging tags at some point, so maybe anybody that used the API after that change actually used the API and wasn't logged due to Tags? Can you check, Alberto, if that's possible?

You're right. The DocketTagViewSet and UserTagViewSet endpoints, which are used by the Tags feature in CL, have not been logged in Redis since 21/04/22.

We have user counts per day, so we can check the counts for each day after 21/04/22 and sum them up. This will allow us to identify the users who have been using the API directly since that date. 
Let me know if that sounds good, and I can provide the script.

**Comment by mlissner** [comment]
Let's do it, Alberto!

**Comment by albertisfu** [comment]
Sure, here is the script to retrieve API users from 2022/4/21 to today. I think it will take some time to process everything.

```
import csv
from pathlib import Path
from datetime import datetime, timedelta

from django.conf import settings
from django.contrib.auth.models import User
from cl.lib.redis_utils import get_redis_interface

r = get_redis_interface("STATS")

start_date = datetime(2022, 4, 21)
end_date = datetime.now()

user_total_requests = {}
current_date = start_date
while current_date <= end_date:
    date_str = current_date.strftime("%Y-%m-%d")
    daily_key = f"api:v3.user.d:{date_str}.counts"
    daily_users = r.zrange(daily_key, 0, -1, withscores=True)

    # sum up counts for each user
    for user_id, count in daily_users:
        if user_id not in ["None", "AnonymousUser"]:
            user_id = int(user_id)
            user_total_requests[user_id] = user_total_requests.get(user_id, 0) + int(count)

    current_date += timedelta(days=1)

media_path = Path(settings.MEDIA_ROOT)
# The directory for storing the CSV
api_directory = media_path / "api_data"
api_directory.mkdir(parents=True, exist_ok=True)
csv_file_path = api_directory / "filtered_api_users.csv"

user_ids = list(user_total_requests.keys())
api_users_queryset = User.objects.filter(id__in=user_ids).values_list("pk", "email", "first_name", "last_name")

# Write the data to a CSV file
with open(csv_file_path, mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["UserID", "First Name", "Last Name", "User Email", "Number of Requests"])

    # Save the user details
    for user_id, email, first_name, last_name in api_users_queryset.iterator():
        total_requests = user_total_requests.get(user_id, 0)
        writer.writerow([user_id, first_name, last_name, email, total_requests])
```

**Comment by mlissner** [comment]
Looks great, and worked well. Thank you Alberto!
