### ISSUE TITLE
Depth of treatment analysis

### ISSUE THREAD

**Issue by elliottash** [freelawproject/courtlistener#435]
We can add depth of treatment or "multiple-use" cites. So if you are looking at the opinions citing Roe v Wade, you can distinguish the opinions that cited it once in passing, versus the opinions that discussed it in depth, citing it many times. 

This requires adding counters to the parser and then storing those in the DB and in Solr.

**Comment by mlissner** [comment]
Open question: How do we expose this to users. Probably a lot of opportunities to do interesting things with this data once we have it.

**Comment by mlissner** [comment]
Brian reminded me what makes this hard. It would be fairly easy to identify multiple occurrences of the same citation within a body of text. But lawyers like to use Id and Supra a lot, and they like to use short names a lot, so you have to somehow catch all of those.

**Comment by ellliottt** [comment]
Mike and I decided today that this can go into `cl.search.models.OpinionsCited` as an integer field.

**Comment by ellliottt** [comment]
It would also be good to add a Boolean of whether the previous case's text was quoted directly.

**Comment by mlissner** [comment]
Another issue to consider here is parallel citations. For example, we need to make sure this counts once, not twice, if we recognize both citations below:

> Harden v. Playboy Enterprises, Inc., 261 Ill. App. 3d 443, 633 N.E.2d 764 (1993).

We can probably do this by keeping track of the index of the citation and eliminating any that appear too closely, but we'll need some strategy for this, I'm afraid.

**Comment by ellliottt** [comment]
How about multiple citations in a single sentence are only counted once. we could split on periods that arent part of citations.

**Comment by mlissner** [comment]
@idc9, @ellliottt, @brianwc, @Colinstarger: I'd love to think some more about how this could be put to use. In network theoretical talk, I believe this changes our citation graph from a directed acyclic graph to a weighted, directed acyclic graph. So instead of:

    A --cites--> B

We have:

    A --cites--> B (four times)

My first thoughts are that this could be useful as an enhancement to our ranking algorithm or as an enhancement to @Colinstarger's visualizations, but I'm really not sure how in either case. I'd be curious what you guys. If we had this data, how would we put it to use? What new features or improvements would it make possible?

**Comment by ellliottt** [comment]
On the ibid. and supra issues, maybe we could automate coding these based on the set of previous citations, but have some easy interface for crowd-fixing.

**Comment by mlissner** [comment]
> On the ibid. and supra issues, maybe we could automate coding these based on the set of previous citations, but have some easy interface for crowd-fixing.

We've shied away from crowd-sourcing in the past because it's really hard, but it sure would provide a lot of benefit if we could do it right. 

I think getting the supras and ibids right isn't *that* hard. The good news is that every time you run into one, you know that it's referring to one of only 10 cases or something (only the things that have come before). It's a pretty small universe to try to sort out, hopefully.

**Comment by mlissner** [comment]
This is now implemented. I'm going to start kicking the tires now. Timeline:

1. Feb 2016 - Bug filed.
2. Feb 2019 - PR filed.
3. Feb 2020 - PR merged.

Could be better, but I'm happy it's landing.
