### ISSUE TITLE
Enhance case name search relevancy

### ISSUE THREAD

**Issue by legaltextai** [freelawproject/courtlistener#4366]
"Google v Oracle" shows Oracle v Google 
Ideally, should show Google v Oracle, Supreme Court first, then Appeal, then organized by date 
There are other examples with famous cases. 
Should we assign more weight to the case name field? To the phrase? Recognize when a user searches for a case name (if there is a "v" or "v.")?  
<img width="727" alt="Screenshot 2024-08-28 at 7 28 56 AM" src="https://github.com/user-attachments/assets/3b95acd4-5cf2-4d28-9bce-fb5ed7df0b6c">
<img width="765" alt="Screenshot 2024-08-28 at 7 28 31 AM" src="https://github.com/user-attachments/assets/900f0054-518f-4fc9-b739-f09c3ccc4a93">
<img width="755" alt="Screenshot 2024-08-28 at 7 28 19 AM" src="https://github.com/user-attachments/assets/57b4a378-afc9-4d91-9408-6f121d36636d">

**Comment by legaltextai** [comment]
Interesting, even if I filter further by case name, it still does not show Google v Oracle in the first place 
<img width="1295" alt="Screenshot 2024-08-28 at 9 38 57 AM" src="https://github.com/user-attachments/assets/131d0d1f-6726-4a75-9fd9-d47841406e20">

**Comment by mlissner** [comment]
We do recognize when there's a `v.` or an `In re` in the query and boost based on case name. Maybe we need to crank that boost higher. 

I don't know that we can boost based on phrases, but @albertisfu might.

Two other relevancy enhancements we have planned are:

1. #558 
2. https://github.com/freelawproject/courtlistener/issues/4381

**Comment by albertisfu** [comment]
> We do recognize when there's a v. or an In re in the query and boost based on case name. Maybe we need to crank that boost higher.

Yeah, this is correct. Currently, we boost the caseName field to 50 if there is a "v", "v.", "vs.", or "vs" within the query, or if it starts with "in re ", "matter of ", or "ex parte ".

After discussing this issue with @legaltextai, we think we could try to increase the boost on `caseName` and/or increase the `query_string` phrase component as well. This is because currently, matches in fields other than `caseName` are also influencing the scores.

This will require some testing within the production cluster so we can determine the best tuning for the search parameters. Perhaps this should also wait for https://github.com/freelawproject/infrastructure/issues/144 ?

**Comment by mlissner** [comment]
Yes, I'd suggest waiting. It'll be easier to do once y'all have read only access.
