### ISSUE TITLE
Email v3 API users

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4405]
Contact v3 API users to announce v4 and encourage them to migrate.

**Notes:**
Mike shared a previous email that can be used as an example on 8.16

**To Do:**

- [x] Draft
- [x] Get feedback
- [x] Confirm email address of sender ([info@free.law](mailto:info@free.law) ?)
- [x] Publish blog, add blog link to email. (via issue freelawproject/free.law#213)
- [x] Get list of contacts (via issue freelawproject/courtlistener#4315)
- [x] Send email

**Comment by s-taube** [comment]
Draft is [here](https://docs.google.com/document/d/1I5zUf0WtElJx0Pf3ndA7k7Do9gGlJUPPGwsutdV_gec/edit).

**Comment by mlissner** [comment]
I tuned it up, but again, only notionally, and feel free to further tweak. The big change I made was to simplify it so that the main goal of it is to:

 - Start talking
 - Assuage people's frustrations
 - Point people to the migration docs

I think it's wise not to put too many details in these because if you do, people will treat them as their migration guide instead of using the canonical one on the website.

Thank you!
