### ISSUE TITLE
Add attachment_number and document_type to the docket-entries API

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4434]
I'm kind of annoyed because I want to get a document using only a URL like this:

https://storage.courtlistener.com/recap/gov.uscourts.cand.433675/gov.uscourts.cand.433675.1.0.pdf

I can get close, but I can't discern between attachments and main documents:

https://www.courtlistener.com/api/rest/v4/docket-entries/?docket__pacer_case_id=433675&docket__court=cand&entry_number=1

If I could do attachment_number or document_type (or both), I'd be on my way.

**Comment by ERosendo** [comment]
@mlissner Is there a specific reason to use the `docket-entries` API instead of the `recap-documents` endpoint? the latter offers `attachment_number` and `document_type` filters. Here are equivalent requests to the one in the issue, using the recap-documents endpoint:

**Main document**:

https://www.courtlistener.com/api/rest/v4/recap-documents/?docket_entry__docket__pacer_case_id=433675&docket_entry__docket__court=cand&docket_entry__entry_number=1&document_type=1

**Attachments**:

https://www.courtlistener.com/api/rest/v4/recap-documents/?docket_entry__docket__pacer_case_id=433675&docket_entry__docket__court=cand&docket_entry__entry_number=1&document_type=2

**Comment by mlissner** [comment]
Yeah, OK, this is fine, I think. I was annoyed, but I think I was using the API poorly. I can indeed do this:

https://www.courtlistener.com/api/rest/v4/docket-entries/?docket__pacer_case_id=433675&docket__court=cand&entry_number=1&recap_documents__document_type=1

But that *does* return two entries still, but I think that's just how the filters work, and I can live with that.

Thanks for clarifying!

**Comment by ERosendo** [comment]
> I think that's just how the filters work

That's correct.

I still think the current filtering mechanism is behaving unexpectedly 😕 While filters are accurately applied to the primary level of results, the nested elements within those results are not being filtered as intended.

**Comment by mlissner** [comment]
I think that's just how they work, for better or worse....
