### ISSUE TITLE
Pghistory's Event admin page for a single object never loads

### ISSUE THREAD

**Issue by grossir** [freelawproject/courtlistener#4602]
An admin page for a single object, like https://www.courtlistener.com/admin/pghistory/events/?method=tracks&obj=search.Docket:60821777&back=/admin/search/docket/60821777/change/ is returning the Flip error page everytime. Maybe this is a timeout or an internal server error?

The admin page was implemented in this PR: https://github.com/freelawproject/courtlistener/pull/4577

![Image](https://github.com/user-attachments/assets/89c87f3b-c319-4acf-8430-957b746c2b67)

**Comment by quevon24** [comment]
Alberto told me that the same thing happened to him with this url: https://www.courtlistener.com/admin/pghistory/events/?method=tracks&obj=search.RECAPDocument:372557163&back=/admin/search/recapdocument/372557163/change/

I think it might be happening because of the way pgh_diff is calculated. https://django-pghistory.readthedocs.io/en/3.4.4/aggregating_events/?h=dif#how-does-it-work

I don't know if adding an index for the pgh_obj_id field in the events table can help with the queries.

**Comment by mlissner** [comment]
I wasn't able to load a list of events either via admin. Maybe it just can't work?

**Comment by quevon24** [comment]
Yes, I was able to load it, it took a while but I was able to load the list of events. I asked Ramiro for the backup of the recapdocumentevent table for the id 372557163.

The second time i tried to load it took less time but still took a while

![Image](https://github.com/user-attachments/assets/55f2ff6b-5264-4ec0-83ed-aa78b0b22755)

![Image](https://github.com/user-attachments/assets/beb6a1a6-6bf2-4b4c-b5c2-b146228e41ac)

This seems to be the problematic query: [monstrous_query.txt](https://github.com/user-attachments/files/17480910/monstrous_query.txt)

This query seems to be fetching everything from each event table and combine the results,  at the end it is used to count the total number of rows from the combined result, but it is also doing more things: it is comparing the current and previous to calculate the `pgh_diff ` which shouldn't be necessary if you're just going to count the rows in all the event tables and this makes it terribly slow if you have a lot of rows in the event tables, which is the case for some models like OpinionCluster, Docket, Opinion, etc. 

I'm still not sure why we need the count from all the events. In my case, in my local env returned 3413574 because i updated a lot of clusters when i was normalizing the filepath_json_harvard field.

After that query, it performs another query that retrieves what we need for the specified object, the events only for the specified id and event table, and this query is fast:

```
SELECT set_config('pghistory.context_id', '4eea0bbe-b050-4974-95d9-02d5d6870689', true),
       set_config('pghistory.context_metadata', '{"user": 3, "url": "/admin/pghistory/events/"}', true); WITH pghistory_events AS (
        SELECT CONCAT('search.RECAPDocumentEvent', ':', _pgh_obj_event.pgh_id) AS pgh_slug,
               _pgh_obj_event.pgh_id,
               _pgh_obj_event.pgh_created_at,
               _pgh_obj_event.pgh_label,
               _pgh_obj_event.pgh_obj_id,
               'search.RECAPDocumentEvent' AS pgh_model,
               'search.RECAPDocument' AS pgh_obj_model,
               (
                SELECT JSONB_OBJECT_AGG(filtered.key, filtered.value)
                  FROM (
                        SELECT key,
                               value
                          FROM JSONB_EACH(_pgh_obj_event._curr_data::JSONB)
                       ) filtered
                 WHERE filtered.key NOT LIKE 'pgh_%'
               ) AS pgh_data,
               (
                SELECT JSONB_OBJECT_AGG(curr.key, array[prev.value, curr.value])
                  FROM (
                        SELECT key,
                               value
                          FROM JSONB_EACH(_pgh_obj_event._curr_data::JSONB)
                       ) curr
                  LEFT OUTER JOIN (
                        SELECT key,
                               value
                          FROM JSONB_EACH(_pgh_obj_event._prev_data::JSONB)
                       ) prev
                    ON curr.key = prev.key
                 WHERE curr.key NOT LIKE 'pgh_%'
                   AND curr.value != prev.value
                   AND prev IS NOT NULL
               ) AS pgh_diff,
               _pgh_obj_event.pgh_context_id,
               _pgh_obj_event.pgh_context
          FROM (
                SELECT pgh_id,
                       pgh_created_at,
                       pgh_label,
                       row_to_json(_event) AS _curr_data,
                       LAG(row_to_json(_event)) OVER ( PARTITION BY _event.pgh_obj_id ORDER BY _event.pgh_id ) AS _prev_data ,
                       pgh_context_id,
                       _pgh_context.metadata AS pgh_context,
                       pgh_obj_id::TEXT
                  FROM search_recapdocumentevent _event
                  LEFT OUTER JOIN pghistory_context _pgh_context
                    ON _pgh_context.id = _event.pgh_context_id
                 WHERE _event.pgh_obj_id = 372557163
                 ORDER BY _event.pgh_id
               ) _pgh_obj_event
       ) SELECT "pghistory_events"."pgh_slug",
       "pghistory_events"."pgh_model",
       "pghistory_events"."pgh_id",
       "pghistory_events"."pgh_created_at",
       "pghistory_events"."pgh_label",
       "pghistory_events"."pgh_data",
       "pghistory_events"."pgh_diff",
       "pghistory_events"."pgh_context_id",
       "pghistory_events"."pgh_context",
       "pghistory_events"."pgh_obj_model",
       "pghistory_events"."pgh_obj_id"
  FROM "pghistory_events"
 ORDER BY "pghistory_events"."pgh_created_at" DESC,
          "pghistory_events"."pgh_slug" DESC
```

**Comment by mlissner** [comment]
Yikes, well that's a heck of a query, but we don't actually need a list of all the events do we? I think what's most useful is to have a list of events for a given object. Can we do that?

**Comment by quevon24** [comment]
> Yikes, well that's a heck of a query, but we don't actually need a list of all the events do we? I think what's most useful is to have a list of events for a given object. Can we do that?

In theory when opening this page: http://localhost:8000/admin/pghistory/events/?method=tracks&obj=search.RECAPDocument:372557163&back=/admin/search/recapdocument/372557163/change/ it should only query the events of the specified object, for some reason it is doing the count with the giant query in addition to the query to see only the events of that object

I will check in more detail

**Comment by quevon24** [comment]
Here is an update:

By default we are using a subclass of pghistory.admin.EventsAdmin, we named it EventsAdminNoFilters.

When a filter is applied in the admin (e.g. view events of an object), two things happen in this order:

1. The get_queryset() method is called to get the base queryset
2. After that, the filter's queryset() method is invoked, which applies the additional filtering based on the user's selection in the admin filter.

If we go to the EventsAdmin class we see this in the get_queryset() method:

```python
    def get_queryset(self, request):
        return config.admin_queryset()
``` 

And if you go further to admin_queryset() method:

```python
return getattr(
        settings, "PGHISTORY_ADMIN_QUERYSET", admin_model().objects.order_by(*admin_ordering())
    )
``` 

It will query all the events from all the tables and ordered by `-pgh_created_at` whether you apply a filter or not. We set this `PGHISTORY_ADMIN_ALL_EVENTS` to False to not display all events in the page `pghistory/events/` and it works because we can't see anything there but still it is executing a count for the pagination (Paginator class by default)

So it doesn't matter if you go to: http://localhost:8000/admin/pghistory/events/ or to http://localhost:8000/admin/pghistory/events/?method=tracks&obj=search.RECAPDocument:372557163&back=/admin/search/recapdocument/372557163/change/, before applying the filter you will always have that big queryset as a base because of the count.

I tweaked the subclass of EventsAdmin to totally get rid of that behavior, it will still run that big query that i shared before but with an extra where to avoid retrieving everything:

`WHERE ("pghistory_events"."pgh_obj_id" = '372557163' AND "pghistory_events"."pgh_obj_model" = 'search.RECAPDocument')`

This allowed me to greatly reduce time:

![Image](https://github.com/user-attachments/assets/c822c848-50d2-4f9b-97e2-ef07c594f6d5)

**Comment by grossir** [comment]
Great news! After the merge the admin page loads, and very fast too

**Comment by mlissner** [comment]
Neat! Here's Miranda v. Arizona (a popular case):

https://www.courtlistener.com/admin/pghistory/events/?method=tracks&obj=search.OpinionCluster:107252&back=/admin/search/opinioncluster/107252/change/

It looks like it has about 2000 updates, each updating the citation count. Sort of feels like we might want to exclude that field? 

Is there an opportunity to feed our changes back into pghistory?

**Comment by grossir** [comment]
Sure, I think we can improve it by:
- excluding updates that only update the "citation_count" field (are there any other fields that make non interesting diffs?)
- ordering by creation date. For some reason it's not the default order, check this [one](https://www.courtlistener.com/admin/pghistory/events/?method=tracks&obj=search.OpinionCluster:197095)
- try a slightly better formatting for `pgh_diff`. I think doing a `json.dumps(pgh_diff, indent=4)` will do the trick to make it nice to read

About proposing changes to pghistory: I think the maintainers of pghistory know it has performance problems, and they do recommend ways to make it work with big databases, the changes to solve our problem were [a few](https://github.com/freelawproject/courtlistener/pull/4611#pullrequestreview-2414249092) lines, we were missing a detailed read of their documentation

**Comment by mlissner** [comment]
Nice. Can you create an issue or three for these, please?
