### ISSUE TITLE
Allow users to select which webhook version they want to use for Opinions Search Alert endpoints

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4657]
Sub-issue for parent card #4540 

"For Opinions, where V1 and V2 of the Webhooks will differ, you mentioned that users who don't want to migrate to V2 should be prepared for changes in V1. Does this mean we need to implement a mechanism that allows users to select which webhook version they want to use for the Opinions Search Alert webhook endpoint?"

"I think so, yes, unless you can think of a simpler way."

**Comment by albertisfu** [comment]
@mlissner Since the selection of the webhook version to use will apply only to Opinion Search Alerts Webhooks, as this is the only endpoint for which migration to V2 of the webhooks will be optional, I think it makes sense to store this setting in the User profile table, right?

However, regarding the UI, here are some proposals that I think would make sense

1 This option will display the toggle to select the Opinion Search Alert Webhook version only if the user has a Search Alert Webhook endpoint.
![Image](https://github.com/user-attachments/assets/3bab5ffd-d380-44f6-99e0-51691392758c)

2 Similar to the previous option, but the setting is placed within the Webhook modal.
![Image](https://github.com/user-attachments/assets/d464f5ba-87e1-4fe1-b36d-86d945196652)

3 Alternatively, we can show the setting regardless of the added webhook endpoints.
![Image](https://github.com/user-attachments/assets/29fdbf2e-15c7-4697-9b6d-ebbb4bc824d2)

In any of these options, choosing the webhook version would be updated using HTMX.

4 Since this could be a user setting, we could also display it in the user profile form.
![Image](https://github.com/user-attachments/assets/c01b2625-d12c-4e96-a027-1e57fae51d53)


What do you think?

**Comment by mlissner** [comment]
Hm, shouldn't the version number should go along with the webhook object and don't we already have a version number field in that object? 

From there, I think the easiest thing is to modify the Event Type drop down to list Seach Alert v1, Search Alert v2, etc. And then on the pages that list webhooks (like picture one, above), there could be a new column for the version number. 

 Could that work?

**Comment by albertisfu** [comment]
> Hm, shouldn't the version number should go along with the webhook object and don't we already have a version number field in that object?

> From there, I think the easiest thing is to modify the Event Type drop down to list Seach Alert v1, Search Alert v2, etc. And then on the pages that list webhooks (like picture one, above), there could be a new column for the version number.


If we add "Search Alert v1" and "Search Alert v2" to the dropdown, users will be able to enable both, resulting in duplicate alerts for the same queries: one in v1 and one in v2. Is that ok?

This change will also impact OA and RECAP alerts. From my understanding, OA alerts should always use v2 since there is no distinction between v1 and v2 serializers in OA, and RECAP alerts will exclusively use nested results, making v2 the only possible serializer.

An alternative could be to keep a single option in the dropdown, labeled "Search Alerts," and allow users to choose the version within the modal:

![Image](https://github.com/user-attachments/assets/ebcd4747-94ff-4e24-95e0-c0de5e8e9a79)

However, this could be confusing since this setting will impact only Opinion Search Alerts, while OA Alerts and RECAP Alerts will always use v2.

Perhaps this field could be named "Opinion Search Alerts Webhook Version," and we could document that OA and RECAP Alerts will always use v2.


And for other webhook endpoints, such as RECAP Fetch or Docket Alert, the Version field should not be shown, as they will always use v2 due to no changes in the serializers?

**Comment by mlissner** [comment]
> If we add "Search Alert v1" and "Search Alert v2" to the dropdown, users will be able to enable both, resulting in duplicate alerts for the same queries: one in v1 and one in v2. Is that ok?

Yeah, sure, that's fine. I could see somebody wanting to have both while they do an upgrade.

For the rest, I see it a bit differently. I think we should support v1 and v2 of all the webhooks, and allow people to create them. Even if v1 is the same as v2, they can set it up and use it. There is one distinction, which is that the `webhook` key will show v1 in v1 and v2 in v2. 

This is a lot like v3 vs. v4 of the API, which are largely the same. In that case, when v4 was launched, we launched it for all endpoints, even though most of them hadn't changed. For example, we didn't tell people to keep using v3 for some endpoints and to migrate to v4 for others. To the contrary, v4 became the recommendation for all endpoints including those that hadn't changed. In this case, we launch webhook v2 for all event types even though most haven't changed.

So I think what we do is we allow people to select from v1 or v2 of all the webhooks, and we send events accordingly, even if they're almost identical most of the time.
