### ISSUE TITLE
Import people from ballotpedia into people_db

### ISSUE THREAD

**Issue by ellliottt** [freelawproject/courtlistener#470]
Maybe the folks at ballotpedia.org would be nice and let us use all of their data on judges and politicians.

**Comment by mlissner** [comment]
I'd be willing to don my Executive Director hat and reach out to them, but it's always a tricky thing because some people regard this kind of a request as devaluing their empire -- "I spent years building this up and you expect me to just *give* it to you?"

It'd be helpful to know what data in particular we were after, and it'd probably be good to identify if there's anything they're already giving away (I haven't looked).

I'm also not opposed to scraping the data, if it exists in a structured manner somewhere on their site.

**Comment by karlnicholas** [comment]
I wrote some java code a while back that scrapes parts of Ballotpedia. Perhaps it is helpful?

**Comment by mlissner** [comment]
@karlnicholas What kind of info were you scaping? Seems hard -- it's pretty much totally unstructured. 

@ellliottt, I realize I never reached out to Ballotpedia because I wasn't sure what data we were looking to get from them. 

I did do some research though, and I don't think they have data in any structured form, though they do have [a partnerships page](https://ballotpedia.org/Ballotpedia:Partnerships). Seems like they don't make many copyright claims either, which is good.

**Comment by karlnicholas** [comment]
I picked out the bio information from the left hand side, under the photo. E.g. https://ballotpedia.org/Greg_Reed = tenor, last_election, education, DOB, etc.

**Comment by mlissner** [comment]
Nice. Yeah, that might be useful to check out. If you have that data, that might be even more useful though.

**Comment by karlnicholas** [comment]
Well, it was only bio data for state legislators for 2012. CourtListener isn't interested in state legislator biographies from 2012, is it? I didn't attempt to RIP the whole site or anything like that.

**Comment by mlissner** [comment]
-------------------

# New start to this issue

Looks like we have a new Ballotpedia data set that we can import. Let's do that!

**Comment by jonashleyo** [comment]
I reached out to Ballotpedia and they offered to provide judge data for a price and may be interested in other collaborations.  The sample data they provided is attached.  The sample does not include prior career history but this apparently can be cobbled together.  
[Ballotpedia_judges_sample.txt](https://github.com/freelawproject/courtlistener/files/3317056/Ballotpedia_judges_sample.txt)

**Comment by mlissner** [comment]
This data looks pretty so-so. Seems like we could massage it into something useful.

**Comment by mlissner** [comment]
Seems like we can't add their data without their permission and getting it otherwise would be costly. Closing for now.
