### ISSUE TITLE
California bulk downloads.

### ISSUE THREAD

**Issue by karlnicholas** [freelawproject/courtlistener#508]
UPDATE: 
I've done an analysis of the latest (April 2016) California bulk downloads of the Clusters and Opinions Files: 

Records in Cluster calctapp  file: 86,976
Records in Opinion calctapp file: 86,976
All ids in cluster are found in opinion file.
Unpublished opinion records: 19,649.

Records in Cluster cal file: 10,936
Records in Opinion cal file: 10,936
All ids in cluster are found in opinion file, all records matched up.
All records "published".

This changes my "not cited number" that I originally posted about. 
The total matched (cluster+opinion) published records number: 78,263
There are 3,366 records that have no cite. Only 4.3%. Not so bad. Breakdown as to source is:
{C=Cite:0 noCite:3112, LC=Cite:57 noCite:0, L=Cite:74840 noCite:254}
PS> of these 3,366, 254 have a "Rptr" cite but no official "Cal." cite. Presumably from the "L" source.

The total matched (cluster+opinion) and cited and published records number: 74,897.
Number of these records with duplicate citations: 353.

So, total number of "useful" records: 74,544.
Useful, to me, is "published" with citations. I deal with the 353 duplicates by "merging" them.
All of which is pretty good. My original concern was because I was not paying attention to my tests for published or not. My bad. I did the close analysis because I have a follow-up question, but I need to work the data a bit more before I post it. Thanks.

**Comment by mlissner** [comment]
Citations are a constant struggle. I don't have a strong intuition about why *these* in particular are missing citations, but we almost never get citations from content that we crawl. It might be interesting to see the numbers for items that were crawled vs ones that weren't. 

As for fixes, there's a version of a parallel citation finder that I wrote that can theoretically identify secondary citations where primary ones are already available, but that doesn't fix this, and I haven't ever run that on the live data. The other solution is to try to identify the citations as people use them and pull them out of the text that way.

Finally, if it turns out that these items have citations in their body, just not in their metadata, we should target extracting that data -- that's often the easiest solution, but generally it's already done.

**Comment by karlnicholas** [comment]
Well, I just want to be clear. I'm talking about the citation of the opinion itself. I'm not talking about citations within the text of the opinion. Since the citation is the de facto industry "primary key", not having the citation of the opinion is tantamount to having a library with all the covers taken off of the books. Hope that's not too harsh.

Where did you get the ones you didn't crawl? Can that source be updated?

The citation of the opinion won't be in the opinion text itself because the opinion's citation is assigned later when the opinion is published. The citation just represents its location in the "catalog." So, for example, 254 Cal.App.4th 1024 is the 254th volume of the Cal.App.4th set on page 1024. You may already know this, but this is how you find the opinion. You go to the 254th volume of the Cal.App.4th set and look on page 1024.

So, if you're crawling slip opinions, those opinions that are published on the California Court website, you are getting them before they have been assigned official citations. Attorneys almost never look up an opinion by its title and you have to use a citation in a brief if it's available. I don't know exactly how long it takes for an opinion to get an official citation after being issued by the court for publication, but its only a matter of months. 

So, CourtListener has a design issue. Since I presume the non crawled source of opinions is a regularly published CD from the California courts (actually, I think they delegate it to Lexus or Thomson/Reuters), then arrangements have to be made to update the data with this source which will have the official citations for the opinions, otherwise there really is no way to make effective use of the data.

**Comment by mlissner** [comment]
We are intimately familiar with citations and how they work. More than any mortal should be really. 

> I'm not talking about citations within the text of the opinion. 

Some sources of data say the citation of the item within the text of the source, if, for example, it's an XML file -- that's why I suggested that.

> Where did you get the ones you didn't crawl? Can that source be updated?

There have been a variety of sources over the years. You can generally see the source of something by looking in the...`source` field.

> So, CourtListener has a design issue.

Yes, this is a big problem that we have some ideas for solving, one of which are neutral citations, another of which is extracting citations as they're used in subsequent cases. So long as the legal system continues publishing the way it does, we'll be playing catch up. It's a problem.

We haven't ever worked with the CDs. That might be an interesting avenue to pursue. I can't imagine it's cheap though.

**Comment by karlnicholas** [comment]
http://www.lexisnexis.com/clients/CACourts/

There used to be a link for getting a CD, but I don't know what the cost would be. I only see this site at the moment for "free public access". A scraper could be written for it, if it's not where CourtListener is already getting CA opinions. It might be, in that case there may well be the opinion citation within the text. I'll have a further look at the data and see 1) what the source is and how the citations compare to that, and 2) see if citations can be parsed from the text. 

If the citations can be parsed from the text it might be a good idea to send them back to CourtListener to be updated in the database.

**Comment by mlissner** [comment]
> If the citations can be parsed from the text it might be a good idea to send them back to CourtListener to be updated in the database.

We get a good number of our citations in this kind of a way.

For the Lexis portal, that's not where we get our opinions. You can find that in the Juriscraper library, but I know it's not from Lexis because I'm almost positive their TOS forbid scraping.

**Comment by karlnicholas** [comment]
Hi, I found the issue I was having and have update my original comment and deleted the other comments. I think you can close this issue since there isn't as many uncited opinions as I originally thought there was.

**Comment by mlissner** [comment]
Ah, right, sorry I forgot to mention that. That'd make a big difference. Glad you caught it.
