### ISSUE TITLE
Cases missing SCDB IDs

### ISSUE THREAD

**Issue by Colinstarger** [freelawproject/courtlistener#542]
The following 2015 Term cases are missing SCDB Ids
(1) FERC v. Electric Power- https://www.courtlistener.com/opinion/3171727/ferc-v-electric-power-supply-assn/
-Should have ID 2015-008 - http://supremecourtdatabase.org/analysisCaseDetail.php?sid=&cid=2015-008-01&pg=0

(2) Montgomery v. LA- https://www.courtlistener.com/opinion/3177217/montgomery-v-louisiana/
- Should have ID 2015-006 - http://supremecourtdatabase.org/analysisCaseDetail.php?sid=&cid=2015-006-01&pg=0

*Note* this appears to be an issue because the Court changed its opinion

**Comment by mlissner** [comment]
Looks like these are because of duplicates. Here's the FERC that has the SCDB ID: https://www.courtlistener.com/opinion/3177219/ferc-v-electric-power-supply-assn/

And the Montgomery: https://www.courtlistener.com/opinion/3177218/montgomery-v-louisiana/

Not sure what the best solution here is. I think in the past we've just chalked this up to duplicates being an annoying problem, and you've fixed them manually. I'd love to fix the citator so it picks one or the other more consistently, but I haven't found time for that yet.

**Comment by Colinstarger** [comment]
For now, I think I'll just add manually. That ok?

**Comment by mlissner** [comment]
No, I don't think so, actually, because then the SCDB ID would be associated with more than one case. I thought in the past, you just updated your vizes to reflect the correct case, rather than the duplicate?

**Comment by Colinstarger** [comment]
Solved by re-making maps to the updated "duplicate". Issue closed.
