### ISSUE TITLE
Clusters with multiple opinions should only occur once in search results

### ISSUE THREAD

**Issue by ellliottt** [freelawproject/courtlistener#550]
As of now, if a cluster has multiple opinions, the case shows up multiple times in search results. It should only show up once.

**Comment by mlissner** [comment]
For example, see: https://www.courtlistener.com/?q=Garnett+v.+Garnett%2C&type=o&order_by=dateFiled+asc&stat_Precedential=on&citation=521+P.2d+1054&cited_gt=0&cited_lt=60000

**Comment by mlissner** [comment]
This is now fixed in dev. Surprise: It was hard.

**Comment by mlissner** [comment]
Alas, this fixed the issue with the results list (which shows only one item), but not with faceting, which still shows two. Needs more work, apparently.

**Comment by mlissner** [comment]
This is fixed again, but in fixing it I discovered *another* bug in our upstream Solr library. Once that's fixed and released, we can upgrade our dependencies, and deploy this code.

Here's the bug, for posterity: https://github.com/lugensa/scorched/issues/45

**Comment by mlissner** [comment]
I took a deep look at this today. There was an issue that the facets were showing counts for ungrouped results. Solr provides a fix for this which is to use `group.facet = true` in your query. Alas, I didn't realize this until it was deployed, but using this feature tanks performance, bringing queries down to about 30s each.

So, I've spent some time looking around the Solr world today, and sure enough, there's a fix for this that should work. Instead of using result grouping, the feature that is designed for this, we need to use the "Collapsing query parser" and the "Expand component". Solr has two ways of doing this, and this is the one that's actually fast. Here's the documentation on that feature:

https://cwiki.apache.org/confluence/display/solr/Collapse+and+Expand+Results

For the moment, results are grouped, but facets have the wrong values. Stripping out the grouping code and swapping it for the "Collapsing query parser" should fix this. Hopefully that feature doesn't have rotten performance.
