### ISSUE TITLE
Bulk data not generating

### ISSUE THREAD

**Issue by t4777sd** [freelawproject/courtlistener#561]
You can see here that bulk data has not been generated in some cases as far back as may in the case of courts:

https://www.courtlistener.com/api/bulk-data/?C=M;O=A

**Comment by mlissner** [comment]
This process can take a while (several days) and as a result is sometimes interrupted. That said, some of these bulk files might not have been updated in a while because they haven't changed. 

Is there a bulk data file that you need? I'm fairly certain this month's generation failed due to out of memory errors on the server (OCR process in #546 was causing issues), but I can kick it off again if you need recent data. 

However, if this is for exploratory work, I'd suggest just using what's there for now, and we can get you a fresh dump of data when you're ready to finalize your results. The data doesn't change that much (in most ways).

**Comment by t4777sd** [comment]
Thanks for your response. If it is not troublesome I would definitely appreciate it if you can kick it off so the data is fresh. Some of the data is definitely not generating at all and is outdated. Look at this: https://www.courtlistener.com/api/bulk-data/courts/

That was not generated since June. I analyzed it to see if there has been updates. Looking at the file there is no "arkag" jurisdiction but looking at your site there is "Arkansas Attorney General Reports" which is the "arkag" jurisdiction. This has the effect that dockets and jurisdiction data is now out of sync.

I am creating word maps from different jursidictions to analyze language used in opinions at the moment. Part of this is I want to segment by time, so up-to-date data is good. Just doing it as a personal research project.

I wonder if the cron could be modified to avoid this issue in the future. Maybe run the cron once every day and to automatically exit if the output file has been modified in the last 30 days. This way it would have the effect of automatically restarting if the previous cron got interrupted.

**Comment by mlissner** [comment]
>  If it is not troublesome I would definitely appreciate it if you can kick it off so the data is fresh.

OK, I just triggered an update. Thanks for digging into this and giving me a shove. This *will* take a while, but it seems like you know how to monitor for when it's done, so that's good.

> I am creating word maps from different jursidictions to analyze language used in opinions at the moment.

Interesting. I'm just curious -- can you give an example of what a potential finding would be? 

> I wonder if the cron could be modified to avoid this issue in the future. 

That's a potential approach, yeah. If you're able to dig into the bulk data creator, the code is quite small. There's probably a fairly straightforward way to fix this. (Just watch out -- February has 28 days!)
