### ISSUE TITLE
Tests using create_temp_solr_core fails when /tmp/solr/opinion_test already exists

### ISSUE THREAD

**Issue by voutilad** [freelawproject/courtlistener#576]
After resolving some PhantomJS stuff on my machine I uncovered new errors, this time with the test cases requiring Solr cores. Multiple tests report issues like:

```
======================================================================
ERROR: test_general_homepage_layout (cl.tests.test_layout.LayoutTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/courtlistener/cl/tests/base.py", line 55, in setUp
    self._initialize_test_solr()
  File "/var/www/courtlistener/cl/tests/base.py", line 108, in _initialize_test_solr
    os.path.join(root, 'Solr', 'conf', 'schema.xml'),
  File "/var/www/courtlistener/cl/lib/solr_core_admin.py", line 24, in create_temp_solr_core
    symlinks=True,
  File "/usr/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/home/vagrant/.virtualenvs/courtlistener/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/tmp/solr/opinion_test'
```

Seems that we should either clean up `/tmp/solr/opinion_test`, clobber it before trying to re-create it, or generate unique temp directories per test run.

**Comment by mlissner** [comment]
I've seen this too. It happens when a test is killed or otherwise fails, and therefore the tearDown method isn't run, so the core continues hanging around.

> Seems that we should either clean up /tmp/solr/opinion_test...

That'd be best, but I'm not sure it's possible, since this is often the result of a killed test.

> ...clobber it before trying to re-create it...

I think this is my vote.

> ...or generate unique temp directories per test run...

We had code like this at some point that made the cores based on timestamps of the tests. Worked OK, but left a lot of litter on your system. I actually prefer the present situation (where you're aware of the little and have to delete it manually) to this solution.
