### ISSUE TITLE
Wrong case names on specific cases

### ISSUE THREAD

**Issue by LawGuy2000** [freelawproject/courtlistener#582]
I have noticed that many cases have wrong court names. Unfortunately, I did not record these as I browsed the data. However, I came across one today and it reminded me to create this issue. My guess is that these court case names were generated automatically via a scraper over the data. However, it appears it did not get all cases or it did it incorrectly for some cases. The court case is:

https://www.courtlistener.com/opinion/3268/for-the/?q=350+F.3d+6&type=o&order_by=score+desc&stat_Precedential=on&docket_number=02-9246

You can see the court case name is "For The" which is obviously wrong. The court case name should be "CARVEL CORPORATION v. Elizabeth A. NOONAN, John D. Noonan, Peter Marsella and Joseph A. Giampapa"

This court case is in marked HTML, so I assume you have a scraper that reads the paties section of the HTML and grabs the court case name and then strips the unncessary stuff.

If that is the case, that process may need to be re-run as it did not work across all cases and as a result some cases have strange names like this.

**Comment by LawGuy2000** [comment]
Another court name with wrong name: https://www.courtlistener.com/opinion/1012269/mcdermott-v/?

**Comment by LawGuy2000** [comment]
Here is some more: https://www.courtlistener.com/opinion/822743/file/?

**Comment by LawGuy2000** [comment]
Essentially look for any case names that are <= 2 words and you will find lots of ones with these errors

**Comment by mlissner** [comment]
Thanks for sending these in. I've fixed them all, however follows is some analysis:

> https://www.courtlistener.com/opinion/1012269/mcdermott-v/?

This one previously had the case name `McDermott v`. It's a scraped case from 2004 in CA4. It should have had `In Re: Elizabeth Pawlak`. This was wrong on CA4's site:

![screenshot from 2016-10-11 09-04-15](https://cloud.githubusercontent.com/assets/236970/19278363/c08c834e-8f91-11e6-9c2e-6a9e7d704de2.png)

> https://www.courtlistener.com/opinion/822743/file/?

This one had the case name `File` instead of `The People v. J.E.`. It is scraped and from California Court of Appeal in 2013. I don't see any issues with the data on the court website, but this was scraped a while ago, we can't be sure of anything.

> https://www.courtlistener.com/opinion/3268/for-the/

This is a curious problem. This document is from Resource.org and was created very early in our history. It's unclear where the erroneous case name came from, but I've fixed it now. 

### Wrap Up

So, looking at these three examples, we have two that are from scrapers and one from Resource.org. One of the scrapers was wrong on the court website, and the other I can't find the issue. The Resource.org example seems like an error in our import code. 

I'm not sure what to do here. It might be worth looking at how many one-word case names we have, and looking for patterns. The other solution is to continue fixing them in this one-off fashion, as I did for these three examples.

**Comment by LawGuy2000** [comment]
I am going to compile a list of court cases and see if I can try to determine which ones are probably wrong and needing review.

Btw, why do both dockets and cluster contain the cases name? It seems like it should only be in one of the API objects and not both of them. Is the docket or cluster the authority of the case name?

**Comment by mlissner** [comment]
Sounds like a great plan, thank you for your help! 

The case name in clusters/dockets thing is because a single docket can have multiple opinions, and multiple opinions can have different case names. Say you're suing the AG. In the district court you're suing Eric Holder and you lose, so you appeal. But when you appeal Loretta Lynch has taken over, so now you're suing her. In that case, you'd have two opinions with different case names, but the docket would be the same. In practice, at this point there is always a one-to-one relationship between the two, but eventually, we hope that'll change.

**Comment by LawGuy2000** [comment]
Okay, so right now which one do you consider the authority? There are a few cases I found where they were not exactly the same names. So, in the current code base is the docket API object or the cluster API object names the one you use for displaying on site, searching, etc?

**Comment by mlissner** [comment]
Generally, the dockets are not implemented, so the opinion is the authority. But hopefully the number of differences is fairly small. They should only happen in the case of human editing.
