### ISSUE TITLE
Delay in syncing documents from IA to RECAP Archive (N.D. Ohio)

### ISSUE THREAD

**Issue by harlanyu** [freelawproject/courtlistener#615]
About 24 hours ago, I added documents 92 and 93 in this OHND case to RECAP: 

https://ia800509.us.archive.org/9/items/gov.uscourts.ohnd.217993/gov.uscourts.ohnd.217993.docket.html

The IA docket looks up-to-date, with links to the PDFs for those two documents (and their attachments).

But as of right now, the CourtListener / RECAP Archive docket still only goes up to docnum 69:

https://www.courtlistener.com/docket/4360576/united-states-v-city-of-cleveland/

**Comment by mlissner** [comment]
So, I don't know what to do here. I just went and re-ran the code that should have run every 12 hours since you posted this, and it worked flawlessly. There's a multistep system that logs along the way:

1. Get the sorted list of changed items from the RECAP server.
1. Iterate over the list, downloading the docket, and any new PDFs.
1. Parse, do a bunch of other stuff.

Somehow, we never log that step 2 was accomplished, neither in the RECAP scraper log nor in the download log. Also, the new items were never downloaded, which indicates a very early failure. 

My current theory is that somehow the RECAP server didn't respond with the items. This is entirely possible, but it sure responded with them when I just made the request. Could be a timezone issue between the servers, but I don't know. I'm going to continue pondering, but these are my first steps.

**Comment by mlissner** [comment]
PS - As a result of my tests, your content is loaded into CourtListener. Sorry about the delay on this...

https://www.courtlistener.com/docket/4360576/united-states-v-city-of-cleveland/

**Comment by mlissner** [comment]
So this was a timing issue and I'm blaming Python's horrible datetime semantics. At the end of the day, we were hitting the old server with a PST timestamp instead of a UTC timestamp. This created a gap and your content happened to fall right in it. 

Annoying situation right here, but thanks for filing it and I'm glad to say it's fixed!
