### ISSUE TITLE
opinions with incorrect filed date

### ISSUE THREAD

**Issue by idc9** [freelawproject/courtlistener#617]
The following opinions' **filed** year does not match the  **decided year** (by a lot)

https://www.courtlistener.com/opinion/2418062/armstrong-v-united-states/
https://www.courtlistener.com/opinion/2621050/murphy-v-utter/
https://www.courtlistener.com/opinion/1088051/the-robert-w-parsons/
https://www.courtlistener.com/opinion/98556/southern-railway-company-piff-in-error-v-samuel-j-campbell/
https://www.courtlistener.com/opinion/103919/district-of-columbia-v-pace/

e.g. ARMSTRONG v. UNITED STATES was filed January 8th, 2009 but the case was decided decided May 27, 1901. I assume that such a drastic difference in year is an error.

**Comment by mlissner** [comment]
Thanks for these. I recognize this kind of error. It happened when we did an import *years* ago, and we had to use some heuristics to figure out the date because it wasn't properly in the metadata. It was a darker time and we weren't clever enough to put some simple bounds checks to keep things reasonable. 

Anyway, thanks for filing this. If you see any other anomalies, we'll keep patching them.
