### ISSUE TITLE
Add "Docket May Need Updating" + "Update Docket" to Ongoing Cases in RECAP

### ISSUE THREAD

**Issue by Colinstarger** [freelawproject/courtlistener#658]
In cases currently under litigation, dockets on PACER change with some frequency. Right now, a user looking at a current docket on RECAP may not realize that the docket he/she sees could be out of date. The way to update it is to go to PACER.

How about putting a warning to this effect on the Docket page -- perhaps to the right of "Docket Entries"? And maybe also provide a button that takes the user to PACER, similar to the "Buy it on PACER" button in other contexts"?

**Comment by mlissner** [comment]
We can probably use the `date_terminated` field to decide which cases should get this notice. Perhaps with a date cut off if we know that 90% of cases terminate within X years.

**Comment by brianwc** [comment]
Keep in mind that many dockets have a lot of activity AFTER the supposed
"date terminated".

I think Colin's idea is best implemented by RECAP keeping track of the last
time it retrieved that docket and just displaying that to the user: Docket
last archived by RECAP on DATE. Then give users an update button and users
can decide if they think an update is warranted. I think this is precisely
what the extension does (or used to do).

**Comment by mlissner** [comment]
Oof. Well, we don't currently have that information in CourtListener and it's not in the XML that we get from RECAP. Hm, so that means our only hope is to modify the data we're getting from the RECAP server when we fetch new content, since it's not in there currently either.

It might be easiest, at least for now, just to have a generic statement on cases fitting some heuristic:

 - no date terminated value and last filing within 2 years
 - date terminated within last year

If we meet either of those criteria, we suggest the person might want to do an update.

That'd get us close?

**Comment by Colinstarger** [comment]
I do like Brian's general idea of a "last time retrieved" statistic and a "Check for Update" button (or whatever). I think that would be relevant and useful all the time. Perhaps Mike's heuristic would make the text turn red or something to signal that you really ought to consider updating. Maybe worth mocking up a couple of potential looks?

**Comment by brianwc** [comment]
Does RECAP not surface these messages anymore? If it does, then a
screenshot of that is the mock I would suggest. I'm also puzzled how RECAP
supports/supported this message if we aren't storing the data anywhere...
that's just... impossible? So confused.

**Comment by mlissner** [comment]
It's architectural. The RECAP server has this info, but the API we use to get the info from the RECAP server to the CL server doesn't have this info. So for CL to have it, we'd have to add it to CL and to the API that the RECAP server is providing. I'm disinclined to tweak anything on the RECAP server though, since the plan is to make it go away very soon and take it out of the loop.

**Comment by mlissner** [comment]
I'm going to close this in lieu of #1037, where we're talking about the on-demand updates part of this. Providing the date modified time stamp has been done for a while.
