### ISSUE TITLE
Make Sankey diagrams for parties/attorneys/firms

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#725]
@jraller and I talked about this around Feb 14th in Slack, but the crux here is that the relationships between parties, attorneys, and firms is complicated, and best displayed as a viz.

Here's a sketch of how I imagine this working:

![img_20170214_145720](https://user-images.githubusercontent.com/236970/29676683-8ebd6372-88ad-11e7-8c17-c64d60df66f2.jpg)

And if you prefer ascii art:

```
party 1-------------\ 
party 2--------------+--atty1 ------------------\ 
party 3-------------/                           |
party 4-------------\                           |---Firm 1
party 5--------------+--atty2-------------------/
party 6-------------/
party 7-------------\ 
party 8--------------+--atty3-----------------------Firm 2
party 9-------------/
```

There's also this image that shows how multiple charts could be used for each type of party:

![img_20170214_153247_720](https://user-images.githubusercontent.com/236970/29676912-4c0903dc-88ae-11e7-85d6-f6cbb018a4ba.jpg)

And this image shows how the charts could be integrated into the UI:

![screenshot_from_2017-02-14_15-35-00_480](https://user-images.githubusercontent.com/236970/29676927-5dd07028-88ae-11e7-8c8b-e0462317523e.png)

Eventually, the nodes could be clickable too, so that you could click on a firm, attorney, or party and see their other stuff as a fresh webpage.

This is a corner case that has thousands of attorneys:

https://www.courtlistener.com/docket/4166723/in-re-tft-lcd-flat-panel-antitrust-litigation/

We should do this as soon as possible, if we can. We just got an email from somebody that pointed out that firm data isn't displayed *anywhere* on CourtListener. That's obviously pretty bad.

**Comment by johnhawkinson** [comment]
As diagramed above this seems to imply a party has a single attorney, which is frequently not the case.

How do law professors represent these relationships in scholarship?

**Comment by mlissner** [comment]
> As diagramed above this seems to imply a party has a single attorney, which is frequently not the case.

I haven't seen this to be the case in PACER, but it seems solvable via the diagram.

> How do law professors represent these relationships in scholarship?

That's a great question. I confess I have *no* idea!

**Comment by johnhawkinson** [comment]
> I haven't seen this to be the case in PACER, but it seems solvable via the diagram.

Errr, except for pro se litigants, I can't think of case where it is *not* the case. Let's pick a case with you in it!:

http://ia801505.us.archive.org/0/items/gov.uscourts.dcd.178502/gov.uscourts.dcd.178502.docket.html

NATIONAL VETERANS LEGAL SERVICES PROGRAM is represented by Narwold, Smith, and Gupta.
And then NATIONAL CONSUMER LAW CENTER by the same three.

Pretty much the only place it doesn't happen is pro se litigants. I guess there are solo practioners in small cases, but anybody represented by a major firm has multiple attorneys filing appearances...

I'm surprised you're not used to seeing the `(See above for address)`

I'm sure it's solvable, but I'm not quite sure *how* you would solve it. It might be good to give a sample diagram.


>  That's a great question. I confess I have no idea!

I think it's a trick question.

**Comment by mlissner** [comment]
I'm sorry, brain fart. Yes, I've seen that, and I've spent days getting the `See above` thing working. Brain fart.

Take a look here: http://bl.ocks.org/d3noob/c9b90689c1438f57d649

If we imagine multiple parties going into the one attorney in the middle named "Elvis" in the example, does that clarify?

**Comment by mlissner** [comment]
Lines crossing should be minimized, but it's OK if they cross a bit — you can experiment with this a bit in the link in my last comment by sliding things around. 

Even in the complex case you gave, a Sankey diagram should be able to handle it fairly well, I think.

**Comment by johnhawkinson** [comment]
Hrmm. if you say so.

http://ia601404.us.archive.org/17/items/gov.uscourts.nysd.273913/gov.uscourts.nysd.273913.docket.html

is an example of irregular situations, where Mark Edward Avsec  represents Canadian Standards Association. But Bruce P. Keller also represents them. But Keller represents other parties too (John R. Wiley) who Avsec does not represent. &c.

**Comment by mlissner** [comment]
Yeah, I think this is the **perfect** use case for the Sankey diagrams. This complex interaction of people is almost impossible to understand in the current table-based approach. In a Sankey it'd be fairly obvious (if a bit messy).

**Comment by johnhawkinson** [comment]
This is not my area of expertise, but it seems like:

* The primary benefit of Sankey diagrams is suppose to be an indication of flow volume based on width of the band. That's not something you've suggested using, so you're sacrificing the alleged design feature of the visualization.

* If there is an issue of overlap, it would seem like a visualization designed to deal with overlap is merited. Maybe that's a 3 dimentional visualization, or something with thinner lines that can more easily expressing crossing lines.

**Comment by mlissner** [comment]
> The primary benefit of Sankey diagrams is suppose to be an indication of flow volume based on width of the band. 

Actually, we do use them for this, to an extent. If an attorney is representing a lot of clients, that seems like an interesting insight, and one that we'd show nicely. But point taken, we're not dealing with crude oil or something. 

I'm totally game to try different approaches to this. The idea is to show the relationships of the people in a way that makes it easier to see who's connected to whom. It could be Sankey, it could be a node and spoke network, I'm game if there's another way forward that makes more sense. We sort of backed into Sankey after doing some sketches and noticing that it seemed like a nice fit.

**Comment by johnhawkinson** [comment]
> Actually, we do use them for this, to an extent. If an attorney is representing a lot of clients, that seems like an interesting insight, and one that we'd show nicely. But point taken, we're not dealing with crude oil or something.

I would challenge this.
Within the context of a single case (which is what I think we're talking about), number of clients is not generally an indication of merit.

For instance, let's take a possibly-typical case I intervened in: http://ia601509.us.archive.org/28/items/gov.uscourts.mad.189311/gov.uscourts.mad.189311.docket.html.

Petitioner sued five government agents (2 officials of a local sherif's dept, and 3 federal officials: director of ICE and ICE's Boston Field office, and also the DHS secretary), all of whom are represented by a single government attorney. Petitioner is represented by 3 ACLU attorneys and outside counsel for the ACLU. (And to be fair, I should _s/represented by/filed an appearance in/_, because we can imagine there is more going on in the DOJ about this than one attorney, even though there's only one appeared.)

It is not true that the government parties are five times more important than petitioner, because there are five times as many parties (although you did not suggest this was what the flow width would be). [And it's definitely not true that I am twice as important as the petitioner, because confusion about CM/ECF accounts lead to one with my middle initial and one without.)

It is also not true that the petitioner is 4 times as important as the government respondants because he has 4 times as many attorneys.

Using any of those as a proxy for importance would seem to be wrong many more times than it would be right.

I think trying to force Sankey to do this is going to lead you down the wrong path. It might be better for us to stop and think what the information that could be visualized here is, and then what should be done about it. It is also possible that there is no interesting visualization of the parties alone that is really worth doing -- it might be much more interesting to see visualizations of the relationships between parties among different cases (there Sankey could show a lot, as some firms or attorneys handle many more cases than others. But I'd still think that would limit the Sankey x-axis to 3, which seems like another indicator that it's not right). Or to show a visualizaiton of which parties are involved in which docket entries.

> The idea is to show the relationships of the people in a way that makes it easier to see who's connected to whom. It could be Sankey, it could be a node and spoke network, I'm game if there's another way forward that makes more sense. 

I do think node and spoke is a better fit. If it's boring, that may mean the data is boring.

As an exercise, I went and sat down with the [D3 Gallery](https://github.com/d3/d3/wiki/Gallery), something I am not super-familiar with and have not looked at recently.  I didn't have great results.

I will try to sit down with my Tufte VDQI and friends and see if anything in there spurs my imagination.

Anyhow, from my review of the D3 gallery, here's what stuck out for me:

* Node-and-spoke variants like [Force-Directed Graph](https://bl.ocks.org/mbostock/4062045) and [Fish-eye distortion](https://bost.ocks.org/mike/fisheye/) seem like the nominal best fit, but they are boring and do goofy things that don't really make sense. And the D3 examples do not show labelling.

<img width="715" alt="screen shot 2017-09-13 at 10 40 20" src="https://user-images.githubusercontent.com/1270718/30383581-0320c3ea-9870-11e7-8569-0b17441ff11f.png">
<img width="730" alt="screen shot 2017-09-13 at 10 40 12" src="https://user-images.githubusercontent.com/1270718/30383609-1783ed8a-9870-11e7-8449-0159fe0fe881.png">

* [Collapsible indented tree](https://bl.ocks.org/mbostock/1093025) and [Hierarchical Classification Tree](http://www.bitjuice.com.au/research/#hierarchicalclassificationexample) seem examples that show labelling, but are kind of utilitarian and have some of the same hiearachy mismatch issues that Sankey does with this kind of dataset.
<img width="883" alt="screen shot 2017-09-13 at 10 41 53" src="https://user-images.githubusercontent.com/1270718/30383664-333c274a-9870-11e7-89a2-25c2c73d5c38.png">
<img width="773" alt="screen shot 2017-09-13 at 10 41 47" src="https://user-images.githubusercontent.com/1270718/30383672-37331d90-9870-11e7-9b30-7f1edf74275f.png">


* [Co-currance matrices](https://bost.ocks.org/mike/miserables/) could be interesting in showing what parties have interacted with what other parties in complex multi-mega-party cases, although parsing this out of docket descriptions would be a Chore.
<img width="1087" alt="screen shot 2017-09-13 at 10 42 30" src="https://user-images.githubusercontent.com/1270718/30383706-487c7786-9870-11e7-9514-a83996e3712e.png">

**Comment by mlissner** [comment]
Thanks for doing some research on this. 

> I do think node and spoke is a better fit. If it's boring, that may mean the data is boring.

Yeah, I could see node and spoke being a good way forward. Maybe we create three columns, and use those to align the nodes horizontally in each column. I think that'd still look roughly like:

![img_20170214_153247_720](https://user-images.githubusercontent.com/236970/29676912-4c0903dc-88ae-11e7-85d6-f6cbb018a4ba.jpg)

That'd be a pretty minimal design and would be something between the chaos of most of the graph vizes (which I find to be fairly useless although fun), and the Sankey's (which you rightly point out can give emphasis where it doesn't belong).

The other benefit (from a tech perspective) is that this could probably use graphing techniques like we use in our SCOTUS visualizations: https://www.courtlistener.com/visualizations/scotus-mapper/.

**Comment by johnhawkinson** [comment]
One more observation. The filing side of CM/ECF diagrams parties in a hierarchical tree with expand/contract buttons. Shown here after clicking Expand All.

<img width="303" alt="screen shot 2017-09-21 at 13 30 27" src="https://user-images.githubusercontent.com/1270718/30709847-9bc36988-9ed1-11e7-8f25-ea492cb576da.png">

I don't propose we do it this way, but it's helpful to give examples of the prior art for this display and that's a significant one, esp. since it's how the system itself represents it in its UI.

**Comment by mlissner** [comment]
That's great, thanks John. 

I like that this also shows the annoying thing about that kind of an approach. Check out Kathleen Connolly. She's all over the place. A better viz could show all of her relationships together in one place without repetition.

**Comment by saizai** [comment]
Related to this would be conflict checking — has an attorney, or their firm, or their previous firms, ever represented a party adverse to the party they are now representing?

(That's not a perfect determination, because you don't know whether they were firewalled appropriately to avoid this, but it's a good flag.)

**Comment by mlissner** [comment]
I'm actually going to close this as a wontfix. Four reasons. 

1. I don't think I understand the use case of the parties page well enough to know how well any visualization would work. There's still a lot of duplication on this page, and that bugs me a lot, but I don't know exactly how people are looking at this information. Maybe it doesn't bug them. Right now it's very easy to answer the question, "Who's the lawyer for this party?", but it's hard to know "How many people is that lawyer representing?" and other questions of that sort. Sankey (or another network-style graph) would fix that. But I'm not sure people are *asking* that.

1. This data is super dirty and complex. I did a lot of the work for the Sankey diagram, but stopped part way through to see what the data looked like in a traditional party listing. There's a lot of complexity and a lot of dirty data. Getting that into a viz will be hard.

1. Visualizations are hard and hard to maintain, and we have a lot of priorities. Should this be one of them? I'm not sure.

1. After doing the traditional layout, I'm actually pretty happy with it. I'm less convinced a Sankey is needed.

I'll post a useful diff to pick up this work again in a moment.
