### ISSUE TITLE
CL document page: more links to docket page

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#751]
CL document pages reference their parent docket in multiple places, but don't always make that reference a link. For instance:

<img width="761" alt="screen shot 2017-11-08 at 03 59 53" src="https://user-images.githubusercontent.com/1270718/32540153-c4a574e4-c439-11e7-82cd-ac70d380a347.png">

There is a "back to docket" link on the left, but "United States v. Manafort" also refers to the parent docket page -- it should also be a link.

**Comment by mlissner** [comment]
I don't think there's anywhere else on the site that headers are links. It would probably need to be blue to be a link so people would knot to it's a link. 

Maybe we need another "Back to docket" link directly under the title? I understand the problem you're trying to solve. Clicking the title does make sense to go back.

Maybe we should swap things so that the top level header is "Document #19", and then the next line can say, "From $case_name". That might make it work better.

**Comment by johnhawkinson** [comment]
It is not necessary that people *KNOW* it is a link for it to be a link.
It is nice-to-have. But the experience should be that if you click on it, and it makes sense to take you somewhere, then it works.

I'm skeptical you should change the page design. I tend to think not.

**Comment by johnhawkinson** [comment]
Looks good. And for clarity, was there reason not to make it blue? [If so fine.]

**Comment by mlissner** [comment]
Just aesthetics. It looked pretty gaudy.
