### ISSUE TITLE
Unable to find logs of what happened.

### ISSUE THREAD

**Issue by theochino** [freelawproject/courtlistener#773]
Downloaded the transcripts of a case (expensive since they are 500 pages long) and they don't upload. 

Please allow a way to upload them manually so they can be shared with the world. I am not paying a few hundred bucks just to upload them a second time.

The Recap file I am working with is the combined case:
1:15-cr-00769-AJN All Defendants USA v. Murgio et al
Date filed: 11/05/2015
Date of last filing: 11/17/2017

The files that never uploaded are the transcript at 470 (about $22 each) !

[screen shot 2017-11-18 at 11 30 34 pm](https://user-images.githubusercontent.com/5959961/32987395-9e854b4a-ccb8-11e7-9d49-1afdcafa7816.png)

There should be a way to upload them manually and checkmark as Manually Uploaded until someone else want to re-download it from Pacer.

**Comment by johnhawkinson** [comment]
Yes. See also https://github.com/freelawproject/recap/issues/210 and https://github.com/freelawproject/courtlistener/issues/769 for more on feedback to the user for failures.

With respect to your upload failures, given that a [CL search](https://www.courtlistener.com/?type=r&q=&type=r&order_by=score+desc&docket_number=1%3A15-cr-00769)  returns 7 different CL cases, it's almost certainly the case that is an instance of https://github.com/freelawproject/courtlistener/issues/767.

The upshot is that documents in cases like that (potentially any criminal case) won't show up.
The good news is that they are being kept on the CL server and when this problem is addressed, they can re-processed and published.

I'm not sure what MIke's priority level for fixing this is, but I think it's fairly high given that we recognize it's a regression over the version that pushes to the Internet Archive.
