### ISSUE TITLE
Review five or so financial disclosure reports from each available year

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#793]
Just to be sure that there aren't any redaction issues. Identified issues so far that we want to look for are:

 - Home addresses
 - Name of friends that might have given personal gifts to a judge
 - SSNs
 - Watermarks from other organizations?

What else?

**Comment by GabeR4** [comment]
In addition to looking for identification errors, we could look for instances in which lower court judges shouldn't have participated in certain cases due to their stock ownership. 

There's an advisory opinion ([scroll to no. 63](http://www.uscourts.gov/sites/default/files/vol02b-ch02.pdf)) by the Judicial Conference that says, "Any interest [including owning stock in an _amicus_] that could be substantially affected by the outcome of a proceeding **is a disqualifying interest**."

It may take a little bit of time, but I'm sure we could find instances in which judges heard cases despite owning shares of an _amicus_. (The same proscription doesn't apply to SCOTUS.)

**Comment by mlissner** [comment]
@flooie can you comment on the privacy parts of this issue. We want to be able to say that we have done some sampling of the disclosures and that we didn't find any private information when we did. I feel like you've probably looked at enough disclosures at this point that we can check this off as done, but perhaps you weren't thinking about them this way and we should do a little sampling. 

@GabeR4, we'll be doing a lot of that soon. More details to come.

**Comment by flooie** [comment]
@mlissner @GabeR4 Sounds like a plan to me. I haven't seen any information that makes me think we are going to find any private information.  I'm not sure about watermarks?  Could you elaborate on that @mlissner

**Comment by mlissner** [comment]
The watermarks was a worry somebody expressed about getting content from Judicial Watch. I'm not going to sweat it, though I'd hate to be on the receiving end of their shtick.

**Comment by mlissner** [comment]
OK, this is on hold until we have PDFs for everything.
