### ISSUE TITLE
Add missing appellate fields to CourtListener

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#846]
In scraping the circuit court PACER dockets, we have discovered a lot of information we didn't previously have:

 - Panel:
    *Contains*: the initials of a bunch of judges
    *Example1*: `["SLL", "KVL", "RT"]`
    *CL Field*: `Docket.panel_str` as a comma separated string. These could also be put into a normalized table, but that's more complicated, and it would create duplication with our judge DB (which we already have a m2m join with).
    *Other*: At this time, normalizing these is out of scope. In other words, we aren't going to write code to look up judge initials and do all that mess. Note also that we already have a field at `Cluster.panel`. That would denote the panel on a specific opinion cluster, whereas this denotes the judges assigned to a case. On the docket we have fields for `assigned_to` and `referred_to`. Perhaps we should do `Docket.assigned_to_panel_str` instead of `Docket.panel_str`. This is getting messy.

 - Appeal from:
    *Contains*: The name of the court where the case was appealed from.
    *Example1*: `"Board of Immigration Appeals (BIA)"`
    *Example2*: `"District of Massachusetts, Boston"`
    *CL Field*: `Docket.appeal_from` would be a foreign key to `Court` table. 
    *Notes*: We should be able to parse every court out there at this point. For ones that fail, we throw an error, which we catch and fix.

 - Fee status:
    *Contains*: whether or not filing fees have been paid
    *Example1: "filing fee paid"
    *CL Field*: `Docket.fee_status`
    *Notes*: Pretty useless information, but here we are.

 - Case Type Information:
    *Contains*: A variety of comma separated tags about a case?
    *Example1*: `"civil, private, bankruptcy"` 
    *CL Field*: `Docket.case_type_information`

 - Originating Court Information
    *Contains*: An entire table of information about the case in the lower court.
    *Example*: 

        "originating_court_information": {
          "assigned_to": "F. Dennis Saylor IV",
          "court_id": "mad",
          "court_reporter": "",
          "date_disposed": "2009-06-11",
          "date_filed": "2009-10-23",
          "date_filed_noa": "2010-01-20",
          "date_judgment": "2009-12-21",
          "date_judgment_eod": "2009-12-21",
          "date_received_coa": "2010-01-21",
          "disposition": "Affirmed",
          "docket_number": "1:09-cv-11783",
          "ordering_judge": "Rya W. Zobel"
         },

    *Notes*: Not sure how best to proceed here. In an ideal world, we could use the docket number and court information to look up the lower court information and add all of the originating court info there. For example, it seems fairly wrong to have the assigned to judge on the appellate docket (or attached to it via some kind of `OriginatingCourtInfo` table when it should just be a part of the lower court docket. OTOH, we might not *have* that docket, so we might be forced to create one based only on the info that we get from the appellate docket. I'm not sure it'd be enough info, but it might be. And then there's the question of matching things up by docket number alone. Would it work? Maybe! All in all, this is a tricky thing: One way provides accurate duplicated fields and data. The other way risks less accurate data, but avoids duplicating fields and data.

    Another consideration is that because of PACER's federated design, I'd bet good money that PACER itself has this information duplicated, for example, it's likely that the district/lower court just provides the case file to the appellate court, and it all gets re-entered. The way appellate PACER connects to district PACER is essentially just by a search for the docket number. Maybe we do the same.

All of these need to get added to:

1. The models
1. The recap upload tasks
1. The HTML
1. New API for OG court, or embed it in an older one?

**Comment by mlissner** [comment]
Updates:

1. Re panel information, I added the following two fields to the Docket:

    ```python
    panel = models.ManyToManyField(
        'people_db.Person',
        help_text="The empaneled judges for the case. Currently an unused "
                  "field but planned to be used in conjunction with the "
                  "panel_str field.",
        related_name="empanelled_dockets",
        blank=True,
    )
    panel_str = models.TextField(
        help_text="The initials of the judges on the panel that heard this "
                  "case. This field is similar to the 'judges' field on "
                  "the cluster, but contains initials instead of full judge "
                  "names, and applies to the case on the whole instead of "
                  "only to a specific decision.",
        blank=True,
    )
    ```

1. Re `appeal_from`, this is kind of a duplicated field, though it'll depend on what information is on the docket. When we have the originating court HTML table, we will have both this value as a string and the OG court value as an ID. We should use both and then store this in only one place.

**Comment by johnhawkinson** [comment]
Many comments inline:

• Panel

> These could also be put into a normalized table, but that's more complicated, and it would create duplication with our judge DB (which we already have a m2m join with).

The former is a legitimate reason to defer, but the latter is not, I think. What happens when there is duplication and/or different choices made courts for the same person (judges can sit by designation in different circuits, and it happens frequently)? I would be wary about presuming you could look up initials information in the `people_db`; but certainly  when we know with certainty we should link that in. 

• Appeal from

> Contains: The name of the court where the case was appealed from.

Well, it's not a court, necessarily. It's very easily not. See `/html/body/form/center/table/tbody/tr[4]/td[2]/select` of [the ca1 advanced search form](https://ecf.ca1.uscourts.gov/n/beam/servlet/TransportRoom?servlet=CaseSearch.jsp&advancedSearch=Advanced):

```xml
<select name="origin" multiple="multiple" size="3">
	<option value="378">Alcohol and Tobacco Tax and Trade Bureau</option>
...
	<option value= "53">Benefits Review Board (BRB)</option>
	<option value= "51">Board of Contract Appeals (BCA)</option>
	<option value= "95">Board of Immigration Appeals (BIA)</option>
	<option value= "52">Bonneville Power Administration (BPA)</option>
	<option value="182">Bureau of Alcohol, Tobacco and Firearms (ATF)</option>
	<option value= "54">Civil Aeronautics Board (CAB)</option>
	<option value= "60">Civil Service Commission</option>
	<option value= "56">Commissioner of Internal Revenue (CIR)</option>
	<option value= "55">Commodity Futures Trading Commission (CFTC)</option>
	<option value= "58">Consumer Product Safety Commission (CPSC)</option>
...
```

you get the picture. All 217 of them. (369 for the Ninth Circuit)

>  Notes: We should be able to parse every court out there at this point. For ones that fail, we throw an error, which we catch and fix.

So... no. Of course, appeals from district courts are (I think) much more common than agency appeals, but agency appeals are certainly not rare.



• Fee status 

> Contains: whether or not filing fees have been paid

It also reflects whether it will ever be paid, because:

> Notes: Pretty useless information, but here we are.

Not entirely. It distinguishes _in forma pauperis_ cases and cases where the government is the appellant so the fee is waived.

I'm not sure what the stats are like at the appeals court level, but e.g. at the Supreme Court the IFP cases are definitely not treated the same as other cases. Of course, the appeals courts don't have a discretionary docket like scotus does, so hopefully that doesn't happen in the same way, but there's probably a minor effect. And certainly it effects things like case timing when there is time to submit an affidavit in support of the IFP motion prior to setting ab riefing schedule and stuff like that. So you'd want to use this in calendar reporting, etc.

• Case Type Information

> Contains: A variety of comma separated tags about a case?
> Example1: "civil, private, bankruptcy"

This is hierarchical. The first field is relatively narrow `/html/body/form/center/table/tbody/tr[3]/td[2]/select`: 

```xml
<select name="casetype" multiple="" size="3">
	<option value=      "">&nbsp;</option>
	<option value=  "1292">1292</option>
	<option value= "1292b">1292(b) petition</option>
	<option value= "1453c">1453(c) petition</option>
	<option value=  "158d">158(d) petition</option>
	<option value=   "23f">23(f) petition</option>
	<option value=    "9a">9a</option>
	<option value=    "ag">agency</option>
	<option value="atydis">attorney discipline</option>
	<option value=   "bkp">bankruptcy appellate panel</option>
	<option value=   "bkb">bkb</option>
	<option value=   "bkd">bkd</option>
	<option value=    "cv">civil</option>
	<option value=   "cjm">complaint judicial misconduct</option>
	<option value=    "cr">criminal</option>
	<option value=  "misc">miscellaneous</option>
	<option value=  "msop">miscellaneous original proceed</option>
	<option value=    "op">original proceeding</option>
	<option value=    "pr">prisoner</option>
	<option value= "pr-dp">prisoner-death penalty</option>
	<option value=   "tax">tax court</option>
</select>
```

I'm less sure about whether the 2nd and 3rd fields are peers.

Also, given `  u'case_type_information': u'Miscellaneous, Permission to Appeal - 23(f)',`, I'm not sure if I am wrong above or if Rule 23(f) class action determination appeals can be coded in different ways. 

An argument could be made that these should be given as 3 seperate fields rather than a list. Note the court basically does it that way, marking them 1, 2, 3:

```
Case Type Information:
     1) agency
     2) review
     3) board of immigration appeals
```

• Originating Court Information

> For example, it seems fairly wrong to have the assigned to judge on the appellate docket (or attached to it via some kind of `OriginatingCourtInfo `table when it should just be a part of the lower court docket. 

It seems like a lot could go wrong with this, in addition to just lacking data. For instance, on Friday I was at a district court hearing where the assigned judge was not available so the duty judge filled in; she issued a TRO. If that TRO was appealed, I expect the OGC data would have the temporary judge in there rather than the assigned judge for the district court docket. These are not semantically equivalent.

> One way provides accurate duplicated fields and data. The other way risks less accurate data, but avoids duplicating fields and data.

I think you should not be "avoid[ing] duplicating fields and data." By all means, make intelligent choices and attach warnings and descriptions and such, but don't fail to collect data because you think it is identically kept elsewhere, because then you'll be screwed when it turns out not to be.

**Comment by mlissner** [comment]
> New API for OG court, or embed it in an older one?

Both. Done in 793d60537cb1c2d79dac631bc71324f896785156

**Comment by mlissner** [comment]
Model updates are done in 9e1732920467794a14f1a51c0eb4d748dc5c648c and 031c462aba248eea3a99722470c6af0870e84baa

**Comment by mlissner** [comment]
Template updates in https://github.com/freelawproject/courtlistener/commit/08c2bcf14280781035f8c036265ebd23babd363b

Merging code up next. Can it get done before the weekend? Maybe.

**Comment by mlissner** [comment]
@brianwc Yep. We won't be doing this automatically and will instead be just keeping track of the data we'll need to do the lookups (and exposing that to users), but we've finally got all the pieces.

In any case, the merging code is in place in 21c3e7776db9ce3b49414e2d09b67014b46477f9
