### ISSUE TITLE
Disable SSL verification in PACER scrapers

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#848]
Some PACER sites suck and don't provide valid certificate chains for their HTTPS. This breaks our scraper. Since it's better to scrape with unverified SSL and get something than it is to scrape and get nothing because it's not verified properly, and because getting the court to fix this would be annoying at best, just disable our verification stuff and be done with it.

**Comment by nbastin** [comment]
At the very least it seems better to download the cert the first time you see it and pin it so you can identify when it changes.

**Comment by mlissner** [comment]
That's probably a reasonable approach. Not sure what we'd do when it changed though.

**Comment by johnhawkinson** [comment]
If a valid cert replaces an invalid one, log it and do nothing.
If an invalid cert replaces an invalid cert, draw it to human attention with low priority.
If an invalid cert replaces a valid cert, draw it to human attention with high priority.

**Comment by bseidenberg** [comment]
@mlissner When you say "don't provide valid chains" do you mean they're presenting a certificate that does not ultimately chain up to a publicly trusted root, or do you mean they are presenting such a certificate, but are not including the intermediates in the ServerHello?

If it's the latter, it should be possible to pre-load the intermediates into the trust store (either as "trusted" after vetting them, or sometimes as just "untrusted but able to be used during path building" depending on the implementation) so that the connection will still be trusted without compromising security.

**Comment by mlissner** [comment]
Not sure, actually. I just know that requests is having trouble validating.
I'd have to go recheck to be sure exactly what the issue was/is.

**Comment by bseidenberg** [comment]
@mlissner If you can give me some sample endpoints, I'll be happy to take a look!

**Comment by mlissner** [comment]
I wish I had made a note, but I didn't. The only way to check that I can think of is to either test every PACER endpoint or use the SSLLabs API to test every endpoint. I don't think either is terribly hard. Just need to generate the URLs from, say, the website here: https://www.pacer.gov/psco/cgi-bin/links.pl

**Comment by bseidenberg** [comment]
@mlissner Cool, thanks for the pointer.
 
So, I pulled every endpoint from there that had ecf in the name. There are 205 total. With a quick invocation of OpenSSL's command line and a bit of grep magic, it looks like all but 3 present a 2-cert chain, with a server cert and an intermediate of
`s:/C=US/O=DigiCert Inc/CN=DigiCert Global CA G2`
`i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2`

The three exceptions:
ecf.arwb.uscourts.gov presents an intermediate of
`s:/C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA`
`i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA`

ecf.nmd.uscourts.gov presents an intermediate of
`s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=Thawte RSA CA 2018`
`i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA`

Both of these chain up to the same root. It's an older one, but it's likely valid in most trust stores. (Assuming they're valid intermediates - I didn't actually verify the signatures against the real root, I'm just trusting the subjects for this quick research)

That leaves us with the likely one problem child of the bunch. ecf.jpml.uscourts.gov presents a server certificate signed by /C=US/O=DigiCert Inc/CN=DigiCert Global CA G2 but doesn't actually present an intermediate. That should be able to be verified by what I described above. Can you point me at the trust store code and I can take a look?

Let me know if you want my raw data.

Cheers!

**Comment by mlissner** [comment]
Nice work! That sounds familiar now that you've done it, yeah. The easiest way to check is just install the latest version of `certify` and Python `requests` and try all of the above weird-cases to see if they work with(out) `verify=False`?

**Comment by bseidenberg** [comment]
A quick spot check with just the requests I have on my system (Debian Stretch) python2.7 has the 2 with alternate intermediates working fine but the one not presenting one failing, which seems to match expectations.

End of my day, I'll poke more at this later (whenever I remember it's pending, most likely).

**Comment by bseidenberg** [comment]
My apologies for letting this sit stale. I did some initial investigation and couldn't find a way to carry out my plan, and then life got in the way. I've now done a deeper investigation and confirmed my plan is infeasible. 

My hope was that we could inject additional certificates into the trust store in a way that they were available for PKIX path building but not actually trusted themselves. I've done this before in Java. However, after much digging, there's no way to do this with requests. Requests has just enough code to take an alternate trust store, but delegates SSL verification to urllib3. urrlib3 in turn delegates to the built in ssl library, which then delegates to OpenSSL under the hood (at least in CPython). As far as I can tell, there's actually no way to inject additional untrusted certs into the path building algorithm without access to the code that invokes X509_STORE_CTX_init(), which is internal to OpenSSL.

Since that path's infeasible, it looks like there are a few paths forward:

1.) Leave things as-is and just not worry about SSL verification. This is the current state, but leaves the potential for a MITM attack to either present false results or to steal our PACER creds.
2.) Build a custom trust store that adds the  /C=US/O=DigiCert Inc/CN=DigiCert Global CA G2 intermediate. This should be safe, since we trust the issuer and do trust this cert just fine when it's presented as part of the chain; however there is effort involved. (The level of effort depends on our level of paranoia and correctness - for example, do we want to ensure we only insert the extra certificate if the parent is present in the trust store we'd otherwise use?)
2*) Do (2) but only enable the custom trust store for the District of New Mexico. This would involve special casing at whatever places we make connections. I haven't looked at the structure of the code to see how centralized this is.
3.) Convince the sysadmin for the District of New Mexico to fix their servers.

(2) Seems like the most reasonable.

@mlissner Thoughts? Especially interested in your thoughts between (2) and (2*).

**Comment by bseidenberg** [comment]
(As a side note, I was reminded to re-start all of this investigation after finding curl wouldn't retrieve a different court's RSS feed. After doing that investigation and writing the findings above, I went back into that and found that at least the Court of Fed. Claims refuses to do any better than TLS 1.0 and the OpenSSL on my system (1.1.1d w/ Debian patches) won't talk to it without special instructions that Curl refuses to pass.

So, that's another thing to keep our eyes open for.

**Comment by mlissner** [comment]
Have we established that this is only an issue for New Mexico? If so I suppose a phone call would be easiest, but I'm also inclined, hearing all of the above just to keep things as they are. 

I don't particularly want to build a custom trust store that we'd have to maintain, and the risk of losing our credentials seems unlikely — even if we did, the worst they could do is make PACER charges for us.

Dumb stuff. Too bad browsers put up with this. That'd be the real fix, if Chrome or FF started throwing errors about this.

**Comment by bseidenberg** [comment]
Yes. See previous comments. It's only NMD that has the issue. If you can make that phone call, that'd be the best for everyone!

Browsers mostly have all the intermediates and stuff stored even if not directly rooted as trust, so they can build the trust path that way. I was hoping to go that path, but alas.

The custom trust store wouldn't be that bad. You'd take the existing one, then just insert one extra cert. Entirely on you how to proceed.

**Comment by mlissner** [comment]
I was getting ready to call NM, but I wanted to make a URL I could share with them before I did, so I ran:

https://www.ssllabs.com/ssltest/analyze.html?d=ecf.nmd.uscourts.gov

It looks...OK? Am I missing something?

**Comment by bseidenberg** [comment]
Hey! Looks like they fixed it! The certificate was issued about a month ago, so I suspect when they installed that one they fixed the chain.  I'll go confirm tonight, and try to rescan the rest of the courts. 

On November 15, 2019 2:56:56 PM PST, Mike Lissner <notifications@github.com> wrote:
>I was getting ready to call NM, but I wanted to make a URL I could
>share with them before I did, so I ran:
>
>https://www.ssllabs.com/ssltest/analyze.html?d=ecf.nmd.uscourts.gov
>
>It looks...OK? Am I missing something?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/freelawproject/courtlistener/issues/848#issuecomment-554561396

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by mlissner** [comment]
Progress‽

**Comment by bseidenberg** [comment]
Would you believe sanity has broken out in the US Court system?

```
$ curl -s https://www.pacer.gov/psco/cgi-bin/links.pl | grep 'href=https://ecf.' | cut -d = -f 2 | awk '{print $1}' | cut -d / -f 3 | sort -u > endpoints
$ for endpoint in `cat endpoints`; do openssl s_client -connect $endpoint:443 </dev/null 2>&1 | grep 'Certificate chain' -A 20 | grep -B 99 -- '^---$' > $endpoint.chain; done
$ for f in *.chain; do grep i: $f | tail -1; done | sort | uniq -c
    187    i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
```

That implies that all 187 endpoints are using the exact same certificate chain, and presenting it correctly.

The only problem is:
```
$ wc -l endpoints
203 endpoints
```

Which means that 16 sites failed. Turns out they're talking TLS 1.0 only.

Running this all again on a system with an older OpenSSL that doesn't block TLS 1.0 because the behavior of the version flags doesn't seem to match the manpage, and we get:
```
$  for f in *.chain; do grep i: $f | tail -1; done | sort | uniq -c
      1    i:/C=US/O=DigiCert Inc/CN=DigiCert Global CA G2
    201    i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root G2
```

So, there is still a broken district I must have missed last time, and it is ecf.jpml.uscourts.gov.

Further, ecf.laeb.uscourts.gov appears to be hard down, so I can't verify it at this time.

So... not quite sanity, but we're closer.

**Comment by mlissner** [comment]
JPML came up earlier in the thread. They're doing bad things, IIRC, and I don't think they'll want to change. My vote is to call this good enough and to close things.

**Comment by bseidenberg** [comment]
And turn on the verifier?

**Comment by mlissner** [comment]
I was afraid you'd say that. The thing that gives me pause though is that if we do, we still don't have monitoring for if/when these break again. Up thread, @johnhawkinson had a suggested plan for that. Do you think you could take a stab at adding that functionality in a separate issue on that topic?

**Comment by divergentdave** [comment]
FWIW, I did a spot check, and 204 of 204 domains are providing two certificates in their chain, and the intermediates all chain to "DigiCert Global Root G2".

```bash
!/bin/bash
curl -s https://pacer.uscourts.gov/file-case/court-cmecf-lookup | grep 'href="https://ecf\.' | cut -d '"' -f 8 | awk '{print $1}' | cut -d / -f 3 | sort -u > endpoints
for endpoint in `cat endpoints`; do openssl s_client -connect $endpoint:443 </dev/null 2>&1 | grep 'Certificate chain' -A 20 | grep -B 99 -- '^---$' > $endpoint.chain; done
for f in *.chain; do grep i: $f | tail -1; done | sort | uniq -c
```

If this continues to be an issue in the future, one workaround with less state would be to take the root store from [certifi](https://pypi.org/project/certifi/), append the currently applicable DigiCert intermediate certificate, write it out to a file, and then pass the path to that file as the verify keyword argument to requests or ssl. This would silently fix the issue if a server ever gave out a leaf-only chain for a few years, until they or their CA starts using a different intermediate.

(Better solutions, such as using Mozilla's cache of intermediate CAs for chain building, are ruled out by the limitations of Python's ssl module, because you cannot provide a certificate for chain building without also trusting it. There has not been sufficient motivation for better APIs because OpenSSL's path building algorithm was broken for many years, and those versions are still working their way out of the ecosystem.)

**Comment by mlissner** [comment]
This hasn't been a problem for a few years. I think we can safely close this. Thanks for the discussion and help, everybody.
