### ISSUE TITLE
Get munin up and running again

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#853]
@brianwc set this up originally so I'm not sure how to do it again, but I'd like to get Munin going again. I just had bad performance on the front end, and I'm pretty sure it's apache's fault. Being able to actually *see* that would have been useful. 

A few weeks ago we had downtime due to solr being swamped. That's not good either.

Will our disks fill up tomorrow? Who know! (I keep an eye on this, but...)

**Comment by mlissner** [comment]
Well, Munin's documentation is worse than terrible. Like, it doesn't even mention that you have to have an Apache configuration to make Munin work, and seems to have no explanation of the configuration files themselves. And they say they used Postgres's docs as their starting point! Oy. Anyway, I'm sorting it out through old Digitial Ocean tutorials like these two:

 - https://www.digitalocean.com/community/tutorials/how-to-install-the-munin-monitoring-tool-on-ubuntu-14-04
 - https://www.digitalocean.com/community/tutorials/how-to-install-munin-on-an-ubuntu-vps

The first seems to be a bit better. Here are my notes from what it took:

## On the main server

1. Install Munin:

        sudo apt-get install munin

1. Munin is a bunch of perl, so you need to have perl utilities in your apache:

        sudo apt-get install libcgi-fast-perl
        sudo a2enmod cgi
        sudo service apache2 restart

    At this stage, you get a Forbidden error if you go to https://www.courtlistener.com/munin . (Normally you'd get a 404 instead.)

1. Make apache work:

 - Replace the references to `/var/cache/munin/www` in `/etc/munin.conf` and `/etc/munin.conf` so they point to `/var/www/munin`, make that directory, and `chown` it to www-data.

 - Rename the server in the example config, so it doesn't refer to us as `localhost.localdomain`

 - In `/etc/munin/apache.conf`, tweak the directory configurations to actually work:

    - Remove the first four lines and add:

            Require all granted
            Options FollowSymLinks SymLinksIfOwnerMatch

    - Repeat this for the remaining various directory configurations


## On the node server(s)

1. Install munin node:

        sudo apt-get install munin-node

1. Configure `/etc/munin-node.conf` with the IP of the master and vice versa

1. Restart Apache (apparently!)

**Comment by mlissner** [comment]
This is now working at: 

https://www.courtlistener.com/munin/

I'm undecided if we want to hide it. Doesn't seem like it needs to be hidden.

Next step is to do plugins and alerts.

**Comment by mlissner** [comment]
Well, I spent way too much time today trynig to figure out all of munin's various plugins and alerts. In the end, I've concluded that munin is...bad. Sure, maybe it works, and maybe it's been around for 15 years, but damn, the documentation is terrible, and damn, a lot of stuff takes custom work to do fairly basic things. 

Some examples, since I'm calling it good enough even though I didn't hit very many of my goals with it:

1. I didn't get apache working because it has an issue with certificates from LetsEncrypt. You can see the issue if you run:

        sudo munin-node-configure --suggest

    Whereupon, it emits this line:

        apache_accesses            | no   | no [Port 80: Can't connect to 127.0.0.1:443 (certificate verify failed)]

1. I didn't get postgres working because, well, I don't know why. I had to install some special perl dependency for it, but after I did that, it said a message like this for all the postgres-related plugins:

    ```
    # The following plugins caused errors:
    # pgbouncer_requests:
    # 	Junk printed to stderr
    ```

1. I wanted to get Celery monitoring going, but two of the three plugins for that have broken URLs, and the third looked complicated.

1. I didn't get as far as looking for plugins for Redis or Solr, both of which would have been nice. 

As for alerts, they have a documentation page for that, but it's really hard to understand:

http://guide.munin-monitoring.org/en/latest/tutorial/alert.html

That says you just need to set up one line in the configuration so that you'll get alerts, but then you'll get all the *default* alerts. What are the defaults and how do you change them? Good luck with that; it isn't clear or it doesn't say, and frankly, I don't even understand the config line I'm supposed to set up. So that's no good either.

---------

With that many failures, I got pretty frustrated and I started looking for other options. Seems like [collectd][1] is where the action is these days, BUT it doesn't believe in shipping a front end and wants other people to do that. So...you can go and try to figure that out yourself. Do you want the one written in Go that uses HTML canvases to display rdd files? Or do you want the one that's using flashy charts, but doesn't support `FLUSH`, whatever that is?

I think next time I've got energy for this kind of crap, I'll see if I can figure that out, but for now Munin is up, for the most part, even if we're missing some of the critical plugins like apache and postgres. 

[1]: https://collectd.org/wiki/index.php/First_steps

**Comment by mlissner** [comment]
Can I just add that my favorite munin feature is how it just refreshes the web page every few minutes. Oh, I'm sorry...were you reading that?

**Comment by mlissner** [comment]
Aaargh!

> On 32-bit systems the data source for this plugin uses 32-bit counters, which makes the plugin unreliable and unsuitable for most 100-Mb/s (or faster) interfaces, where traffic is expected to exceed 50 Mb/s over a 5 minute period.

**Comment by mlissner** [comment]
Anyway, I'm closing this. Other suggestions for further improvement include moving this off of the main CL server so it's more robust.

**Comment by mlissner** [comment]
I got apache working after applying the random setting described here: https://github.com/munin-monitoring/munin/issues/892#issuecomment-422220353

**Comment by sumpfralle** [comment]
Are you sure, that you are using a properly maintained package for munin?
I am co-maintaining the Debian package and I have to admit, that I am confused by the file locations you mention (e.g. `/etc/munin-node.conf` instead of `/etc/munin/munin-node.conf`).

# apache configuration
Your tweaks of directories for the apache configuration are not necessary for the Debian package. Which package did you install from which location?

# apache plugins
The problem with the apache plugins seem to be caused by using an HTTPS URL, that fails certificate validation (e.g. due to using `localhost` instead of the hostname matching the URL). The default URL of the apache plugins use `http` instead of `https`. Did you change these?

# postgres plugins
I took a look at the plugins and cannot see a reason, why the `pgbouncer_requests` plugin should emit errors messages during `autoconf` (this action is caled by `munin-node-configure`). What is the output of `munin-run pgbouncer_requests autoconf`? How about `munin-run pgbouncer_requests`?

# celery plugins
The [two celery plugins in the contrib repository](https://github.com/munin-monitoring/contrib/tree/master/plugins/celery) use `http://localhost:8989`. Is this an unreasonable default?

# alerts
Automatically sending alerts for all configured plugins seems like a reasonable approach to me. E.g. you will get informed by the `df` plugin, if disk usage exceeds 92% (configured in `/etc/munin/plugin-conf.d/munin-node`). I think, there are only a few (reasonable) warning/critical levels configured by default. Would you recommend to change/remove some of them?


btw: I think, it is always a good approach to report issues to your distribution or upstream. And (for me) it is way more fun to read reports without the word *crap* :)

Have fun!

**Comment by mlissner** [comment]
So we've been getting alerts from SMART every five minutes for our SSDs and I spent a few hours today trying to learn if these alerts were relevant or not. I'm pretty convinced they're not, and so I disabled them by creating a new file in `/etc/munin/plugin-conf.d/smart` that contained:

```
[smart_sdg,smart_sdh,smart_sdi,smart_sdj]
env.ignoreenv 4
```

This makes it so that when the smart util returns an exit code of zero, we don't send an email. And, so that when it returns to sending an exit code of 0, we don't send *another* email (see: https://github.com/munin-monitoring/munin/issues/1085).

**Comment by mlissner** [comment]
Thanks for coming and chiming in @sumpfralle. It really means a lot to me to get your expertise, even though I know I've been not so nice to `munin` in this thread. Sorry for that — I didn't think you'd read it, and I find it kind of useful to try to capture my frustration in these issues so that if I come back later, I can say, "Oh, right! That was making me feel crazy!" Anyway, sorry about that.

A few responses:

1. Re Apache and needing to tweak things, sorry, I had a typo in my comment above. I installed on an old-ish version of Ubuntu, so perhaps I didn't need to tweak those values. I was following a guide and didn't want to mess around too much. Seemed useful to put munin in `/var/www/munin` in any case.

2. Re Apache, I think the issue was that I was accessing using localhost, not my domain name, so that broke the SSL, like you suggested. I wonder if it's time to update these defaults in munin itself, since [more than 50% of the top million websites are now on HTTPS][1m]?

3. Re postgres, I haven't gotten it figured out. `pgbouncer` was a bad example to paste in the issue, but the rest of the postgres commands do the same. So, trying one of those:

    ```
    ↪ sudo munin-run postgres_bgwriter autoconf
    # Unknown service 'postgres_bgwriter'
    ```

    Seems like probably a simple fix, but I haven't gotten to googling around and seeing what's dependency is missing there. Alas, there's no program called `postgres_bgwriter`. 

4. Not sure about the celery plugins. Going to have to take another look. By the time I got there, I was too frustrated to really dig in beyond the exploration that revealed two of the three links on [the celery site were broken](http://docs.celeryproject.org/en/latest/userguide/monitoring.html#munin). 

Anyway, thank you again, and sorry again. I feel like I'm getting closer on each of these (discovering the ~documentation~ gallery was very useful!).

[1m]: https://scotthelme.co.uk/alexa-top-1-million-analysis-august-2018/

**Comment by mlissner** [comment]
OK, putting the `env.ignoreexit` command in `/etc/munin/plugin-conf.d/smart` didn't work. Trying it in `/etc/munin/plugin-conf.d/munin-node`, where there are lots of other files like this one.

**Comment by mlissner** [comment]
Nope. Still nothing. Asking on Stack Overflow: https://stackoverflow.com/questions/52415716/how-do-you-make-munin-stop-sending-alerts-for-smart-exit-statuses, and continuing to try various things...

**Comment by mlissner** [comment]
Trying again with `[smart_*]`. Maybe that'll work.

**Comment by mlissner** [comment]
OK, figured out the problem. The version of munin that's on my system is from, drumroll please, 2006:

```
↪ munin-node -v
Version:
    This is munin-node v2.0.19-3ubuntu0.3

    $Id$

Copyright:
    Copyright (C) 2002-2006 Audun Ytterdal, Jimmy Olsen, and Tore Anderson /
    Linpro AS.
```

And, as you might expect, the `ignoreexit` parameter is from after that. The patch is from 2014 or so:

http://lister.munin-monitoring.org/pipermail/commits/2014-September/003327.html

We've got an older version of Ubuntu, but not *this* old. Dang it.

**Comment by mlissner** [comment]
OTOH, the `smart_` plugin is from February 2012, apparently:

```
 66 # v2.1 2012-02-14 - Add support for Darwin (Mac OS X).
 67 #                 - Print the last line of smartctl output to verbose
 68 #                   log to aid in understanding why smartctl exited with
 69 #                   a nonzero status.
```

Still...not new enough. I think I'll apply the patch manually if it's not too different.

**Comment by mlissner** [comment]
OK, I've replaced the plugin with the one from master. I think this may have worked.

**Comment by sumpfralle** [comment]
Thank you for your diligence and for taking the time to write down your findings in order to improve munin (and future experiences of fellow users)!

> Re Apache, I think the issue was that I was accessing using localhost, not my domain name, so that broke the SSL, like you suggested. I wonder if it's time to update these defaults in munin itself, since more than 50% of the top million websites are now on HTTPS?

I agree with your statement about the usage of HTTPS. But still the *proper and universal* approach to reach apache's *status* seems to be `http://localhost/server-status` (apache's default) since https against localhost will inevitably fail due to the mismatch of the hostname and the certifcate. Users may feel free to change this to `https://example.org/server-status` - but the domain name is hard to guess / discover for a munin plugin.

Regarding `postgres_bgwriter`: indeed I forgot, that the plugin was not activated due to the autoconf failure. Thus your test should be:
```shell
/usr/share/munin/plugins/postgres_bgwriter autoconf
```

(since you noticed, that you somehow stumbled upon a quite dusted munin package, I would recommend to update to a newer release, instead of looking for detailed problems)

Celery plugins: thanks for the link! I opened a [pull request](https://github.com/celery/celery/pull/5064) for updating the documentation links.

> The version of munin that's on my system is from, drumroll please, 2006:

:)
Indeed it is old, but not *that* ancient - 2.0.19 was released in 2013.
This explains a good deal of the mysteries you encountered :)

Good luck on your future journey!

**Comment by mlissner** [comment]
Thank you again for looking at this. Re apache, this should probably be over on a Munin bug report, but why not just allow certificate failures by default? That'd have avoided my issue and I'm not sure I see a downside. (I'm not suggesting that Munin switch to preferring https by default.)

>  Indeed it is old, but not that ancient - 2.0.19 was released in 2013.

Yeah, I think I was looking at munin-node, not munin, but I did file https://github.com/munin-monitoring/munin/issues/1087, which would have made it a lot easier to figure this out in the future.

Thanks again. I'm making progress!
