### ISSUE TITLE
Break up the CourtListener monolith

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#936]
Currently CourtListener does a LOT of things: Search, task processing, DB work, batch jobs, alerts, on and on. This is problematic:

 - The code base is getting big and kind of disorganized

 - Upgrades to single components have to be done in place because nearly everything lives on one server. If we pull things apart, we can do upgrades on new guest virtual servers and then use a load balancer (or even a human) to slowly move traffic from one thing to another.

 - When we do use multiple servers, we just install the whole honking code base regardless of if it's needed. 

    For example our second Solr server (which literally has an HTTP interface and doesn't know anything about our code) has the entire CourtListener code base installed. Why? Because it needs the init scripts, obviously! 

This issue is to think about ways to break up the beast. I think the most obvious things to do first are:

 - A new repo for Solr. 

 - A new repo for task processing (this will probably continue using Celery, but I could *totally* see some other system being used instead (kafka? other suggestions?)

 - A new repo for Apache (I think this might only be one file, but OTOH, I think this might have to pull in the Django code, so not sure).

Anyway, pulling all this stuff apart is going to be and feel good. Let's do so.

**Comment by mlissner** [comment]
Dave, Dave, and John, I'd love to have you guys chiming in and adding your input if you can spare a moment to follow along and guide my foolish hands. 

This is a pretty wide open ticket involving some big decisions about the system's architecture. I don't feel great making these decisions on my own (but we all know I will if I have to!).

I appreciate and respect all of your opinions and expertise if you can lend it.

**Comment by mlissner** [comment]
Dave, Dave, and John, I'd love to have you guys chiming in and adding your input if you can spare a moment to follow along and guide my foolish hands.

This is a pretty wide open ticket involving some big decisions about the system's architecture. I don't feel great making these decisions on my own (but we all know I will if I have to!).

I appreciate and respect all of your opinions and expertise if you can lend it.

@johnhawkinson @voutilad @davidxia.

**Comment by davidxia** [comment]
@mlissner Sorry for the delayed reply. Your rough plan sounds like the right way to go. I don't see anything that are obvious no-nos. But keep in mind I'm not familiar with all parts of the code base and definitely not familiar with the operational aspects.

General best practices for any type of migration or change like this are

* incremental changes
* always have a way to rollback

Please keep me posted if you want feedback as you start to implement various parts of this, e.g. at-mention on PRs, ping me on Slack, etc.

P.S. Here's a great talk by a great software engineer who's pretty well known in the FOSS community. ["High Reliability Infrastructure Migrations" - Julia Evans](https://youtu.be/obB2IvCv-K0?t=1026). This 20-minute talk has a lot of good insights. Evans gave this talk as a keynote at KubeCon. I'll be delivering a keynote at KubeCon Barcelona on May 21-23. Let me know if anyone is going.

**Comment by willglynn** [comment]
[The `cl.scrapers.tasks` module](https://github.com/freelawproject/courtlistener/blob/98638d6902e62108f0226200a59be6090e3abcdd/cl/scrapers/tasks.py) has a pile of unique dependencies and seems ripe for splitting off. The interface is "here's a file, tell me what it says" which maps neatly to RPC, and as far as I can tell, nothing else in CL needs `pdftotext` (patched per #937 or otherwise), `antiword`, `docx2txt`, `wpd2html`, `tesseract`, or `gs`. If there was a service responsible for conversions, these dependencies could all live there without affecting the rest of the application.

I'm a big fan of packing weird tools into containers, particularly ones with lots of dependencies. `Dockerfile`s aren't the only way to package software but they sure are handy for reliably delivering tangled webs. In particular the separation of build-time and runtime is extremely useful, since it lets one e.g. replace `pdftotext` and validate the new container image by running a test suite without affecting the deployed environment. Does CL plan to use containers in the future? If so, how?

**Comment by mlissner** [comment]
For the moment, I'm planning to use VMs because I don't understand containers well enough and I don't think I have time to really get into them properly. I understand the big picture, but I've witnessed other orgs lose a lot of time containerizing. Seems like the corner cases can be brutal. 

That said, I think it'd be pretty great to split out the document conversion junk. You're right that it's a lot of the complexity as far as our dependencies go, and yeah, the interfaces are pretty simple for the most part. 

My plan currently is to have a VM or two running tasks. I suppose it wouldn't be incredibly crazy to have a container for that kind of thing *inside* the task VMs? Or would it make more sense to have that container available on the host VM as a microservice or something? Hm.

**Comment by willglynn** [comment]
That's not crazy at all! Containers and VMs play very well together. The technologies focus on different layers: VMs can do what VMs do best (isolating hardware/OS/security failures), containers can do what containers do best (software packaging and operations via a uniform interface).

The easiest way to approach containers is that they're just a funny way to run a process. [`rkt run`](https://coreos.com/rkt/) is literally just that – a process that starts by asking the kernel to do a beefed up `chroot()`, and then runs the target process in that environment. This new environment talks to the same kernel, but it shares nothing else, decoupling it from the host.

A container image is just a tarball of a `chroot` environment plus some metadata. A container image registry is just a file server that serves those tarballs. A `Dockerfile` is just a set of instructions to make a container image. None of the pieces are interesting, which is _wonderful_. It's all boring stuff until you put it all together.

The result is a uniform way to take an application, build and pack it into an image, ship that image over the network, and confidently execute that image once or a million times as needed. This is powerful because of the workflows it enables: build the image, test the image, then deploy the tested image. It's powerful for separating concerns: everything's just a process running in a container image, providing a clear interface for both developers and operators. It's powerful because standing up new servers isn't scary: retrieve the current image and run the container, same as every routine deployment.

If you're considering containerization, definitely start with anything stateless. It's easy enough to make a server run a container and expose some service on a fixed port; there needn't be any extra moving pieces. Things get complex when you want _exactly one_ of a service running anywhere in your infrastructure, or when you want your database service to spawn replicas which can take over when the primary fails, etc.

**Comment by mlissner** [comment]
Appreciate the comments, @willglynn. Great insight. I think this means that the plan is:

 - Pull out Solr (vm)
 - Pull out Task Servers (vm)
 - Pull out Apache (vm)
 - Pull out document processing (container in task server)

This...may take a while....have I mentioned I've yet to ever play with Xen? :)

**Comment by mlissner** [comment]
I'll be working on Solr in #939.

**Comment by mlissner** [comment]
I'm working on task servers in #945, and in freelawproject/courtlistener-task-server.

**Comment by mlissner** [comment]
OK, so during our Python 3 conversion, I took a stab at dockerizing apache in #1419 and utterly failed. Read that one if you're interested. I wound up switching to a dockerized Nginx in #1429. So that's that. 

Task processing was deemed infeasible in #945.

Solr is done in #939. 

Document conversion utilities are getting wrapped up by @flooie in #941. 

I think that's a enough to say this is done. Pretty much everything is dockerized or about to be.

Redis and postgresql remain undockerized but I think dockerizing postgresql is probably a bad idea, and redis is so small and easy to move around I just don't care that much about it. 

I'm ready to call this one done-enough. ☮️
