### ISSUE TITLE
Usage of IP addresses in replication is fragile

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#938]
I've written about this on Stackoverflow, AWS Forums, and to friends. We're currently using RDS IP addresses to make replication SUBSCRIPTIONs and to do authorization. These IPs aren't reliable and can change. I think this only happens when the DB servers are rebooted, but when that happens, things go offline and all our replication connections have to be restored.

There are three solutions to this:

1. Set up a VPN that all of our replicated databases live within. 

2. Set up a proxy that all of our replication traffic flows through.

3. Automatically detect IP address changes and have a script running all the time that can update things as needed.

Number 3 seems horrid, but it's been suggested twice now. Number 1 seems doable, but complicated, and it involves setting up a new machine to serve as a gateway between every server. Not great.

Number 2 seems simple enough. The suggestion I've heard is to use AWS Elastic Load Balancers in front of an EC2 server running HAProxy:

 - ELB provides secure connections to the outside world
 - ECS provides a server to run stuff on
 - HAProxy does the real work.

I wish this extra architecture weren't necessary, but it sure seems to be. Pretty lame.

**Comment by mlissner** [comment]
Here's the stackoverflow: https://stackoverflow.com/questions/54953887/how-to-authenticate-aws-user-on-specific-host-inside-private-cloud

And the AWS forums post: https://forums.aws.amazon.com/message.jspa?messageID=892809#892809

**Comment by mstrofbass** [comment]
Option #4, maybe: Using a dynamic DNS provider. I didn't think of this before because it's basically only used when you want to host a server at home using a connection that uses DHCP.

Essentially:

1. Sign up with ddns provider like DuckDNS.org.
2. They give you a subdomain at one of their domains, like flp.duckdns.org.
3. You install an update client on the server.
4. The update client (basically a daemon) checks for IP address updates and then notifies the provider when the IP address changes.
5. The provider updates the A record on their name servers to reflect the change.

I think the update should be nearly immediate, but I'm not sure if propagation delay is limited to hostnames or if A records are actually cached along the way (thus bypassing name server lookups).

A couple of potential issues (besides propagation delays):

1. Would the update client be persisted between reboots, migrations, or other AWS actions? This is mainly a question I have because I don't know how one configures/manages the actual ec2 instances used for RDS. Is it even possible to install something extra on the server?
2. There may be issues with reverse DNS lookups when the IP address resolves to multiple hostnames. This could potentially be solved via multiple network interfaces with different external IPs, but we're back into more infrastructure changes.

**Comment by mlissner** [comment]
This is indeed resolved by #949. I'm hoping to wrap up that issue, finally now.
