### ISSUE TITLE
Add latest data from FJC

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#958]
@ellliottt reminds me that we actually have a script for this:

https://github.com/freelawproject/courtlistener/blob/c5be31fc2216eaabfdbe64df3aab2e8acc6a42f3/cl/people_db/import_judges/populate_fjc_judges.py

The idea here is to get some low-hanging fruit and to update our DB with the latest data from FJC.

**Comment by jonashleyo** [comment]
Once this goes through (see:  [https://github.com/freelawproject/courtlistener/pull/968](https://github.com/freelawproject/courtlistener/pull/968 ) I can submit a pull request that takes care of additional minor issues, namely:

- Reading in gender correctly.
- Reading the FJC CSV's as CSV's instead of Excel.  Also, the FJC has cells of purely white space and there's a line of code to take care of this.
- Updating court regexes to handle FJC Court of Appeal names (no space between U. S.)
- Correctly reading in numbered variables (i.e. "Appointment Title (1)")

If there's some other way I should proceed please let me know.

**Comment by jonashleyo** [comment]
Looking at education here are 5 schools that don't have an entry in the Schools database:

American University, Washington College of Law
Arizona State University
Brigham Young University
Brigham Young University, J. Reuben Clark Law School
Columbia Law School

For some of these, the Schools db has the location listed at the end (i.e. Arizona State University-Tempe) but that's not how the FJC data is structured.  Unless there are reservations, I'll update Schools db with the FJC school names that are missing.  For entries like "Arizona State University" I'll create an alias (titled "Arizona State University") that points to the flagship campus (i.e. "Arizona State University-Tempe").  Does that make sense or is there another way to approach this that's better?

**Comment by mlissner** [comment]
Yeah, feel free to use aliases liberally. The goal is that we have a canonical entry for every school we need as well as an alias for whatever weird ways we need to lookup that school sometimes.

**Comment by jonashleyo** [comment]
Posting a file for upload here:
[missing.zip](https://github.com/freelawproject/courtlistener/files/3403943/missing.zip)

Some of the data has been tweaked.  The first column "cl_id" doesn't appear in the FJC data for obvious reasons.  But, for a handful of judges born outside the U.S., the country of birth was removed.  The city of birth was left in as it doesn't seem to generate any errors.

**Comment by jonashleyo** [comment]
Submitted a pull request ('add-offset-limit') that adds 'offset' and 'limit' args to cl_import_judges.py.  Let me know if there's something else I should be doing on this.

**Comment by mlissner** [comment]
Done!
