### ISSUE TITLE
Change default donate option to "monthly" not "once"

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#975]
Defaults matter and I think it's OK to push our donors a little towards doing monthly donations. It's what we prefer so we should suggest it.

This will surely affect the JS on that page, but should be fairly easy to get right.

**Comment by nathreed** [comment]
Is this still open? It seems like it can be easily implemented by changing cl/donate/forms.py line 112 from "once" to "monthly" - I'm happy to sign a CLA and submit a PR for this, but that seems like a lot of effort for a one line change...

**Comment by mlissner** [comment]
There's probably a js/HTML component to this too, IIRC. Want to try getting
it set up in  a dev environment and see what it takes? If you want to sign
digitally or take a picture and email the license agreement, that shouldn't
be too hard, I hope. (I know it's annoying.)

**Comment by mlissner** [comment]
Well, that's a pretty simple fix then, I suppose. Though it's a bit hacky, I can live with it, I think. You have interest in continuing to improve this page? You probably have fresher eyes than I do, but, for example, what about switching the pills for Once / Monthly so monthly comes first...or, I don't know, there's probably a good bit that could be done here, if you're interested.

**Comment by mlissner** [comment]
@nathreed wanted to make sure you saw my comment above.

**Comment by nathreed** [comment]
I did - I've been extra busy so far this week (college student). I'll probably have some time tomorrow or Friday to swap the pills...other than that, I actually think the page is good as-is. I think it already has a nice, clean, simple design that gets all the info necessary and makes it as easy as possible to donate.

**Comment by mlissner** [comment]
@nathreed I'm just doing some housekeeping and thought I'd check in. Is this still on your radar? It'd still be a nice fix if you're interested. 

I hope you're doing OK with everything. I imagine it's a bit chaotic for students atm.

**Comment by nathreed** [comment]
I might have some time this weekend to swap the pills (which I know I said earlier...) but yes, things are quite chaotic at the moment - I have a lot of schoolwork in addition to adapting to remote classes, etc. 

So I will try my best to find time this weekend to swap the pills, but if I can't get it done by then, I likely won't be able to do so in the foreseeable future.

**Comment by nathreed** [comment]
Hey, just wanted to follow up on this. This change came to my mind after the controversies surrounding the last US election and political organizations automatically opting people in to recurring donations in a predatory way. While I don't think the impact of this change is predatory (since it's only a monthly recurrence, and not weekly like some of the political organizations were doing), I do notice that you've kept monthly as the default. There's been a lot of media coverage of this issue, and I wouldn't want it to negatively impact FLP if this change were to be highlighted for some reason.

Do you think that possibly some warning/more conspicuous text should be added to the donation page to make absolutely clear to users that they are making a monthly recurring donation? The styling makes it sort of clear, but I think it could be clearer (like for example by changing the donate confirmation button to say "Make a recurring donation" instead of "Donate to Free Law Project" or adding a red warning text or something like that). Just something to make sure the user is 100% aware and okay with making a recurring donation.

Obviously, this is a business decision for you, not just a technical one, and I have no idea if defaulting to monthly has actually increased your recurring donations by a meaningful amount. I just wanted to bring up this issue again, given the context of the recent media coverage surrounding recurring donations.

**Comment by mlissner** [comment]
Since this change, we've had a couple people who were surprised by it. We send an email whenever somebody donates (monthly or otherwise), so it gets caught and cleaned up pretty quickly. So far, when somebody has a monthly donation they don't want, they email, I stop it, and they haven't ever asked for their money back, so it's not in the same league as some other donate forms out there.

That said, it's surprising people and double charging them — none of which is good — so that's not great even if they don't ask for their money back. 

I'd be very much in favor of tweaking the button like you describe. Want to take a stab at it?

**Comment by nathreed** [comment]
Ordinarily, I would like to take a stab at changing it, but I have just started a new job as a software engineer and I am not yet 100% certain of the intellectual property policies of my new employer w.r.t. whether code I write outside of work is owned by the company. I wouldn't want to violate employer policy or encumber your code base.

Glad to hear that it isn't causing too many problems, and it sounds like there is a robust process for dealing with issues as they do arise.

**Comment by mlissner** [comment]
Oh shoot. Well, that's good to know. FWIW, back when I was in the corp world, I asked for an exception about open source contributions and it wasn't a big deal. Obviously depends on your employer. It'd be good to revisit this though. It bugs me that we surprise people like we do, even if we can fix it pretty quickly.
