### ISSUE TITLE
Forced early evaluation of ALL_COURTS query

### ISSUE THREAD

**Issue by malteos** [freelawproject/courtlistener#980]
I just stumbled upon this piece of code, because my database was out of sync and I couldn't execute `manage.py runserver` nor `manage.py showmigrations` without an error:

https://github.com/freelawproject/courtlistener/blob/8119034960b85575d1ae08f6c7a6024a961ae776/cl/citations/find_citations.py#L22-L31

It looks a bit hacky. Maybe it's better to add at least a try-catch block around the query to give a hint that the db might be out of sync.

**Comment by mlissner** [comment]
Yeah, on the one hand, it's not horrible that things fail in weird ways when the DB isn't synced, but on the other, we could do a better job telling people what action they should take, instead of just crashing. Or maybe there's a larger fix here that doesn't hit the DB at import time?

Happy to have a fix; low on my list otherwise.

**Comment by mlissner** [comment]
The `ALL_COURTS` variable is no longer in the code. This must be fixed.
